### ISSUE TITLE
URL fetch failure in plaidvision example on MacOS

### ISSUE THREAD

**Issue by borderlineinteractive** [plaidml/plaidml#100]
Hi, I am getting the following output when I try the plaidvision example as described on the website:

(plaidml) MacBook-Pro:plaidvision user$ python ./plaidvision.py mobilenet
Using PlaidML backend.
/Users/user/plaidml/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:plaidml:Opening device "intel(r)_iris(tm)_graphics_650.0"
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf.h5
Traceback (most recent call last):
  File "./plaidvision.py", line 314, in <module>
    main()
  File "./plaidvision.py", line 264, in main
    model = Model(args.model, args.weights)
  File "./plaidvision.py", line 206, in __init__
    self.model = ModelClass(weights=weights)
  File "/Users/user/plaidml/lib/python2.7/site-packages/keras/applications/mobilenet.py", line 520, in MobileNet
    cache_subdir='models')
  File "/Users/user/plaidml/lib/python2.7/site-packages/keras/utils/data_utils.py", line 222, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf.h5: None -- [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)

My configuration is as follows:

MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)

Python 2.7.14

(plaidml) MacBook-Pro:plaidvision user$ openssl version
LibreSSL 2.2.7

I installed plaidml as described in the instructions and configured it to use the built in Intel GPU. It seems to me that the problem is related to incompatibility between the server that provides the URL and the python library that is used by the framework to access the URL. However, I don't know how to fix this. Could anyone help?

Best wishes,

Leif

**Comment by earhart** [comment]
I'm not sure how to fix the fetch problem, but you might be able to download the model file by hand -- store it as ~/.keras/models/mobilenet_1_0_224_tf.h5

**Comment by borderlineinteractive** [comment]
Thanks, this fixed the problem.

**Comment by faddey-w** [comment]
Your problem is in python's openssl version, most probably. Please see this SO question:
https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version
