### ISSUE TITLE
Is that possible plaidml targeting to spirv(Vulkan) as backend

### ISSUE THREAD

**Issue by lygstate** [plaidml/plaidml#104]

**Comment by earhart** [comment]
This would be pretty straightforward (and personally, I think it'd be pretty fun); we don't have any plans to do it soon, though.  Our thinking is that it might provide a few more optimization opportunities, and it might compile kernels more quickly than OpenCL, but it's a non-trivial amount of work, and it doesn't seem high-priority yet.

If you're interested in giving it try: the OpenCL backend is in `tile/hal/opencl`.  There's an emitter class that understands how to translate the semtrees created by the Tile compiler into OpenCL C.  You'd want to add a separate emitter that translates to SPIR-V.  It might be useful to look at the code in `tile/hal/cpu`, which uses LLVM to translate semtrees into code for general-purpose processors.

**Comment by bhack** [comment]
It could be part of Plaidml roadmap to MLIR:
https://github.com/tensorflow/mlir/blob/master/g3doc/Dialects/SPIR-V.md
https://drive.google.com/file/d/1FLdhNgTii9x5o1rMgN4ibB7Wkuq6Pyye/view?usp=drivesdk

**Comment by salvatorepellitteriastroit** [comment]
Hi,
thanks for make Plaidml so awesome. I also would like to see plaidml on top of vulkan. I'm very sick of how opencl implementations are so bad even today. I have 2 powerfull AMD gpus and I can't even use it for Blender or Luxrender, with nvidia better we don't talk about it.
Vulkan is modern and designed the right way (for graphics) but the best thing is that almost every vendor released drivers at day one with very little to none bugs. This is incredible if you think compared to opengl and opencl drivers out there.
Vulkan it's not exactly as opencl but do you really need OpenCL? you can generate spirv code and run it with vulkan. Do you need more than this?
Opencl should burn and fall ones and for all, it's doesn't make any sense a tecnology that no one get right or don't want to support.
Best Regards,
Salvatore.
