### ISSUE TITLE
model.fit() issues: Unknown: Additional parameters to PRNG call must be constant integers

### ISSUE THREAD

**Issue by fbalocco** [plaidml/plaidml#106]
Dear plaidml team,
I'm encountering an issue upon calling model.fit():

>Traceback (most recent call last):
>
>File "<ipython-input-12-b8ce4c08464e>", line 1, in <module>
>    runfile('/dev_3/external_learn.py', wdir='/dev_3')

>  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
>    execfile(filename, namespace)
>
>  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
>   exec(compile(f.read(), filename, 'exec'), namespace)
>
>  File "/dev_3/external_learn.py", line 427, in <module>
>    E.rout('training/',True,100)

>  File "/dev_3/external_learn.py", line 329, in rout
>    self.timer(self.returns[j],self.epi_prices[j],rounder) #here the actual learning
>
>  File "/dev_3/external_learn.py", line 308, in timer
>    self.train_agent(price,rounder)
>
>  File "/dev_3/external_learn.py", line 295, in train_agent
>    self.agent.Q_update(minutes,actions,rewards)
>
>  File "/dev_3/external_learn.py", line 420, in Q_update
>    self.model_.fit(x=[minutes,actions],y=actions*rewards[:,None],batch_size=len(minutes))
>
>  File "/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1598, in fit
>    validation_steps=validation_steps)
>
>  File "/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1183, in _fit_loop
>    outs = f(ins_batch)
>
>  File "/anaconda3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 145, in __call__
>    for name in self._output_names
>
>  File "/anaconda3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 145, in <listcomp>
>    for name in self._output_names
>
>  File "/anaconda3/lib/python3.6/site-packages/plaidml/__init__.py", line 1416, in get_output_shape
>    return _Shape(self._ctx, _lib().plaidml_alloc_invoker_output_shape(self, name.encode()))
>
>  File "/anaconda3/lib/python3.6/site-packages/plaidml/__init__.py", line 716, in _check_err
>    self.raise_last_status()
>
>  File "/anaconda3/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
>    raise self.last_status()

>  Unknown: Additional parameters to PRNG call must be constant integers

The model compiles without problems. I figured it might have something to do with how my output shape is broadcasted. The model works fine with TensorFlow backend.
What am I missing here?
Thanks a lot!

Francesco

**Comment by tzerrell** [comment]
Hi @fbalocco,

Interesting, thanks for the report! Can you send us code that reproduces this error? Without knowing the structure of your model there's not much we can do to debug this.

**Comment by tzerrell** [comment]
Closing this as stale

**Comment by unclewaltr** [comment]
I saw the same error message when I put a floating point number as a size or dimension. Eg.
`    model.add(Dense(64.0, input_dim=512, activation='relu')
`
