### ISSUE TITLE
Mobilenet problem: RuntimeError

### ISSUE THREAD

**Issue by davidbp** [plaidml/plaidml#109]
Hello

I have upgraded `plaidml` to 0.3.2 but I still get  problems when trying to use a model from keras.

```
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import plaidml
>>> import plaidml.keras
>>> 
>>> import plaidml.keras
>>> plaidml.keras.install_backend()
>>> from keras import applications
>>> 
>>> base_model = applications.MobileNet()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidbuchaca1/anaconda3/envs/keras_opencl/lib/python3.6/site-packages/keras/applications/mobilenet.py", line 367, in MobileNet
    raise RuntimeError('Only TensorFlow backend is currently supported, '
RuntimeError: Only TensorFlow backend is currently supported, as other backends do not support depthwise convolution.
>>> plaidml.__version__
'0.3.2'
```

**Comment by tzerrell** [comment]
Thanks for the report. We're looking into a fix for this (and the issue you reported in the comments to #103); in the meantime, you should be able to work around these issues by using
```
import keras.backend as K

K.backend = lambda: 'tensorflow'
base_model = applications.MobileNet()
K.backend = lambda: 'plaidml'
```
in place of just using `base_model = applications.MobileNet()`. Let us know if this workaround doesn't work for you.

(Note: I expect that which of these issues you run into without the workaround will depend on what version of Keras you're using)

**Comment by tzerrell** [comment]
Thanks for your patience. We're putting together a release that will be compatible with Keras 2.2.0+ without the need for such workarounds. We'll update this issue when it's out.

**Comment by tzerrell** [comment]
Our latest release (0.3.5) is now compatible with Keras 2.2.0+ without workarounds, resolving this.
