### ISSUE TITLE
Keras > 2.0.8 not compatible message with every update

### ISSUE THREAD

**Issue by danbricedatascience** [plaidml/plaidml#110]
Hi,

Everytime I upgrade plaidml, the Keras version is forced to 2.0.8, so I reinstall last Keras and I get this message:

`plaidml-keras 0.3.2 has requirement keras==2.0.8, but you'll have keras 2.1.6 which is incompatible.`

As this is happening with every update, do you plan to fill the gap soon and get a compatibility with the most recent Keras version ? 

Or at least can you list the most important incompatible features we have to take care of in a doc ?

Thank you

**Comment by edmondja** [comment]
same problem

**Comment by jamesbsilva** [comment]
Tried deleting everything and restart to no luck. Does anyone have any ideas ?

**Comment by znmeb** [comment]
You have to set aside a separate virtualenv / conda environment for PlaidML as it stands now. And after then install, you may have to remove the "enum34" package.

**Comment by tzerrell** [comment]
Our latest release (PlaidML 0.3.5) is now compatible with Keras 2.2.0+, which should fix this
