### ISSUE TITLE
LSTM Error when using lots of timesteps

### ISSUE THREAD

**Issue by TimFelixBeyer** [plaidml/plaidml#112]
Hi, when using a large Input (more than 77 timesteps in this particular case) I get the following error:

I'm using plaidml 0.3.2 and Keras 2.1.6 on a Mac.
With the tensorflow backend, everything works fine even with large Inputs.

```
INFO:plaidml:Opening device "amd_radeon_r9_m395_compute_engine.0"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
main_input (InputLayer)      (None, 78, 88)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 256)               353280    
_________________________________________________________________
frame_output (Dense)         (None, 88)                22616     
=================================================================
Total params: 375,896
Trainable params: 375,896
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/1
INFO:plaidml:Analyzing Ops: 5557 of 7191 operations complete
Traceback (most recent call last):
  File "lstm.py", line 98, in <module>
    train_loop()
  File "lstm.py", line 94, in train_loop
    history = combined_model.fit_generator(train_data_gen, epochs=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/training.py", line 2230, in fit_generator
    class_weight=class_weight)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/training.py", line 1883, in train_on_batch
    outputs = self.train_function(ins)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaidml/keras/backend.py", line 151, in __call__
    self._invoker.invoke()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaidml/__init__.py", line 1426, in invoke
    return Invocation(self._ctx, self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaidml/__init__.py", line 1432, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaidml/__init__.py", line 716, in _check_err
    self.raise_last_status()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Unable to initialize OpenCL kernel: CL_INVALID_KERNEL
```

**Comment by tzerrell** [comment]
Thanks for the report, we'll look into it!

**Comment by nmurali2002** [comment]
@tzerrell Any new info? I got a `self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
OSError: exception: access violation reading 0x0000000000000018` under similar circumstances, but using a CNN for image classification. Still fails on first epoch roughly 1500 operations in.

**Comment by cgodfreyUW** [comment]
Getting a similar error - tried to run a LSTM with 2 layers, each with 96 time steps and a 100-dimensional hidden state. Got 

`Epoch 1/3

INFO:plaidml:Analyzing Ops: 1573 of 18852 operations complete
INFO:plaidml:Analyzing Ops: 5378 of 18852 operations complete
INFO:plaidml:Analyzing Ops: 9842 of 18852 operations complete
INFO:plaidml:Analyzing Ops: 15195 of 18852 operations complete
INFO:plaidml:Analyzing Ops: 17913 of 18852 operations complete
`
and then after running journalctl -xe:
`Dec 03 23:48:38 charles-ThinkPad-T480 kernel: python[24448]: segfault at 404000003fe8 ip 00007fcf017e2053 sp 00007ffc696dc508 error 4 in libst ...
`

**Comment by rutrilla** [comment]
Hi!
I have a similar problem when using LSTM layers from Keras in my models. My laptop has a Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz and the GPU is an Intel(R) HD Graphics 5500. I tried plaidML with [this example](https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py), and it works perfectly, but with the following model it gives the error: "plaidml.exceptions.Unknown: Unable to compile Tile program"

`model = Sequential()`
`model.add(LSTM(128, return_sequences=True, input_shape=(128, 2)))`
`model.add(Dropout(0.8))`
`model.add(LSTM(128, return_sequences=False))`
`model.add(Dense(11, activation='softmax'))`
`model.compile(optimizer=keras.optimizers.adam(), loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])`
`model.summary()`
`model.fit(x_train, y_train, batch_size=400, epochs=80, verbose=1, validation_data=(x_test, y_test))`

This is the full log:

[log.txt](https://github.com/plaidml/plaidml/files/3322569/log.txt)

I've also tried the [examples/imdb_lstm.py (from keras)](https://github.com/keras-team/keras/blob/master/examples/imdb_lstm.py), which is on your [validated networks list](https://github.com/plaidml/plaidml), but I got the same error. Any idea? Thanks in advance!
