### ISSUE TITLE
the tensor which pass to plaidml::op::concatenate have to cast first.

### ISSUE THREAD

**Issue by XingHongChenIntel** [plaidml/plaidml#1122]
In a very simple tile example, such like below:    
 
    auto order = mv::Order("NCHW");
    std::vector<int64_t> I_shape{1, 1, 16, 16};
    auto I = Placeholder(DType::FLOAT16, I_shape);
    auto B = I * 1.5;
    auto R = plaidml::op::concatenate({I, B}, 2);
    auto program = ProgramBuilder("test_concatenate", {R}) 
                       .floatx(DType::FLOAT16)
                       .compile();

we will get the compile **error**:

**error: 'affine.store' op first operand must have same type memref element type**
terminate called after throwing an instance of 'std::runtime_error'
  what():  conversion to the LLVM IR dialect failed

but if we cast tensor(B) to DType::FLOAT16, then it would compile successfully.

   `auto B = cast( I * 1.5, DType::FLOAT16);`

because the ProgramBuilder::floatx() method is used for specifying which data type constants will actually have. 
since we already set it to FLOAT16. why we still need to cast tensor(B)?

**Comment by flaub** [comment]
I'll have a fix for this shortly.
