### ISSUE TITLE
Cannot legalize operation 'eltwise.round'

### ISSUE THREAD

**Issue by LiyangLingIntel** [plaidml/plaidml#1129]
I'm trying to do some Tensor computation like this
```c++
std::vector<int64_t> I_shape{1, 3, 16, 16};
auto I = Placeholder(DType::FLOAT16, I_shape);
auto O = round(I * 0.5);
auto program = ProgramBuilder("tensor_round", {O}).floatx(DType::FLOAT16).compile();
```
Then it gets a compile error:

**error: failed to legalize operation 'eltwise.round'**
terminate called after throwing an instance of 'std::runtime_error'
  what():  conversion to the LLVM IR dialect failed

**Comment by flaub** [comment]
@mars1026 @tzerrell Is this still an issue?

**Comment by tzerrell** [comment]
Resolved, see `plaidml/edsl/tests/edsl_test.cc` for the "Round" test which tests this.
