### ISSUE TITLE
Add eltwise logical operations

### ISSUE THREAD

**Issue by tzerrell** [plaidml/plaidml#1143]
We do not yet have the logical `and`, `or`, `not`, and `xor` elementwise operations.

**Comment by flaub** [comment]
@jbruestle Are these equivalent to the bitwise versions with caveats? Do you think we should add new ops or just ensure that the logical versions use the bitwise versions underneath?

**Comment by flaub** [comment]
Some of these fixed in #1169

**Comment by flaub** [comment]
Is this done?

**Comment by tzerrell** [comment]
Yes, see pmlc/conversion/tile_to_pxa/tests/logical.mlir
