### ISSUE TITLE
Add eltwise sinh and cosh

### ISSUE THREAD

**Issue by tzerrell** [plaidml/plaidml#1184]
We do not yet have the elementwise sinh and cosh operations. Note that these can be expressed in terms of exp.

**Comment by flaub** [comment]
Is this done?

**Comment by tzerrell** [comment]
@mars1026 I believe you did this, can you confirm?

**Comment by tzerrell** [comment]
Yes, see pmlc/conversion/tile_to_pxa/tests/eltwise.mlir
