### ISSUE TITLE
Add eltwise sin

### ISSUE THREAD

**Issue by tzerrell** [plaidml/plaidml#1186]
Add legalization for eltwise.sin. Note that sin(x) = cos(x - pi/2) (and cos already has a legalization).

**Comment by flaub** [comment]
Is this done?

**Comment by tzerrell** [comment]
@mars1026 I believe you did this, can you confirm?

**Comment by mars1026** [comment]
Yes indeed; there's a test for it in eltwise.mlir.

**Comment by tzerrell** [comment]
cool, I can look through that and grab the others of this type
