### ISSUE TITLE
Keras nadam optimizer does not work

### ISSUE THREAD

**Issue by shibe2** [plaidml/plaidml#123]
When trying to use nadam, I get:

AttributeError: 'tuple' object has no attribute 'dims'

Nadam uses `pow` operation [like this](https://github.com/keras-team/keras/blob/528542176f70f9a889e84e4494032f42a53bec67/keras/optimizers.py#L616):

```python
momentum_cache_t = self.beta_1 * (
    1. - 0.5 * (K.pow(K.cast_to_floatx(0.96), t * self.schedule_decay)))
```

Where `K.cast_to_floatx(0.96)` is a numpy array. In PlaidML, `pow(x,p)` [uses](https://github.com/plaidml/plaidml/blob/8a5ff0917b7247bc2c513096c62acb1d51736044/plaidml/op.py#L1261) `x.shape` which gives the numpy array shape as a `tpuple`, not `tile.Shape`. Later, this causes the observed failure when the `Value` constructor [does](https://github.com/plaidml/plaidml/blob/19706521d1b9e8c045de7c129076b19b2e1ab3dd/plaidml/tile.py#L672) `shape.dims`.

[Test case](https://gist.github.com/shibe2/1f4a3e5d01471f9dfefe16148e27eac6).

**Comment by tzerrell** [comment]
Thanks for the report! This should be fixed in 0.3.3rc3.
