### ISSUE TITLE
Question : WARNING:plaidml:Reached scheduler optimization timeout

### ISSUE THREAD

**Issue by x4080** [plaidml/plaidml#124]
I'm testing with https://github.com/keras-team/keras/blob/master/examples/addition_rnn.py

Seems to run but getting that warning, is it only in my system (GPU : Radeon R9 280x tahiti), and using this example seems only use GPU about 2% and CPU 45%

Thanks

**Comment by xxshazxx** [comment]
Hello, I'm also getting the same message using and AMD RX580. 

1152/1163 [============================>.] - ETA: 0s - loss: nan - mean_absolute_error: nanINFO:plaidml:Analyzing Ops: 2225 of 2391 operations complete
WARNING:plaidml:Reached scheduler optimization timeout

Is there anything to fix this ?

**Comment by rajasrijan** [comment]
looks like timeout needs to be adjusted.
https://github.com/plaidml/plaidml/blob/19706521d1b9e8c045de7c129076b19b2e1ab3dd/tile/platform/local_machine/loose_scheduler.cc#L14
