### ISSUE TITLE
Move affine.load + affine.vector_load into pxa

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1242]
Currently there are a number of issues with and affine.load and pxa.reduce (which are basically the 'read' and 'write' of pxa) being in distinct code bases.  Specifically: we currently cannot fix typing issues related to memref-state, we cannot add memory analysis / memref-state tracing interfaces, and generally the two operations are at slightly different levels of abstraction.  By moving the affine.load -> pxa.load we will be able to address these issues.

**Comment by adstraw** [comment]
Create a WIP PR here for affine.load here:
https://github.com/plaidml/plaidml/pull/1265/files

**Comment by adstraw** [comment]
Down to 2 failing test cases:

```
//pmlc/dialect/pxa/tests:strides.mlir.test                               FAILED in 1.4s
//pmlc/target/x86/tests:xsmm_stencil.mlir.test                           FAILED in 1.8s
```

Focusing on strides.mlir.test first.  The @simple test case is failing:

```
func @simple(%arg0: memref<100x100xf32>, %arg1: memref<100x100xf32>, %arg2: memref<100x100xf32>) {
  affine.parallel (%i, %j, %k) = (0, 0, 0) to (100, 100, 100) {
    %0 = affine.load %arg1[%i, %k] : memref<100x100xf32>
    // CHECK: strides: 0:[^bb0:%arg0=100, ^bb0:%arg2=1]
    %1 = affine.load %arg0[%k, %j] : memref<100x100xf32>
    // CHECK: strides: 0:[^bb0:%arg1=1, ^bb0:%arg2=100]
    %2 = mulf %0, %1 : f32
    pxa.reduce add %2, %arg2[%i, %j] : memref<100x100xf32>
    // CHECK: strides: 0:[^bb0:%arg0=100, ^bb0:%arg1=1]
  }
  return
}
```

When I run the test I see the following strides in the MLIR:

```
strides: 0:[^bb0:%arg0=100, ^bb0:%arg1=1]
strides: 0:[^bb0:%arg0=8, ^bb0:%arg1=1, ^bb1:%arg0=16, ^bb1:%arg1=2]
strides: 0:[^bb0:%arg0=55, ^bb0:%arg2=1, ^bb1:%arg0=110, ^bb1:%arg1=11]
```

Versus expected:

```
    // CHECK: strides: 0:[^bb0:%arg0=100, ^bb0:%arg2=1]
    // CHECK: strides: 0:[^bb0:%arg1=1, ^bb0:%arg2=100]
    // CHECK: strides: 0:[^bb0:%arg0=100, ^bb0:%arg1=1]
```

It's not obvious to me what is going wrong here so I am planning to debug side-by-side with the plaidml-v1 branch to pinpoint the divergence in the PXA StrideInfo pass.  Posting the failure details here for others to weigh in with theories.

**Comment by adstraw** [comment]
Above PR is merged.  Next step is to move affine.vector_load to pxa.

**Comment by adstraw** [comment]
AffineVectorLoad PR:
https://github.com/plaidml/plaidml/pull/1272

**Comment by adstraw** [comment]
Both PRs merged.  Closing
