### ISSUE TITLE
Subgroup transformation

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1243]
Add a PXA transformation the rewrites an affine.parallel in a similar fashion to the v0 subgroup pass.  The transformation takes a 'plan' produced by an analysis method (still to be ported), and performs the following transformations:

1) Tile the affine.parallel (where the inner tile memory usage for both read + write will be registers)
2) Vectorize on the primary subgroup index
3) Perform a vector load transform on secondary subgroup indexes
4) Tile via TileAccumulations
5) Cache loads inside the accumulate loop
6) Cache reduces outside the accumulate loop

**Comment by adstraw** [comment]
@jbruestle This is done, I believe, with the following PRs.  Can we close?

https://github.com/plaidml/plaidml/pull/1278
https://github.com/plaidml/plaidml/pull/1296
https://github.com/plaidml/plaidml/pull/1330
