### ISSUE TITLE
Create 'TileAccumulation' pass and add to the GPU pipeline.

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1244]
Currently lowering to GPU has bugs due the racing writes cause by invalid kernel outlining of serial affine.for into parallel code.  While this bug need to be addressed, it highlights the need for ordering affine.parallel loops into two sets of indexs, one that is parallel safe post lowering of pxa.reduce, and one that is not.  To perform this function, we will add a new transform function as well as a pass.

Steps:

- Move the utility function TileAccumulation (prototyped here: https://github.com/plaidml/plaidml/blob/be4c0cb7e102b14bf3653226372c52fc514b6fa6/pmlc/dialect/pxa/transforms/subgroups.cc#L127), into a free function in a new header/c++ pair pmlc/dialect/pxa/transforms/tile_accumulation*

- Add a pass (and add to the gpu pipeline) which performs TileAccumulation followed by a CacheWrite (see https://github.com/plaidml/plaidml/issues/1239)

This will make the outermost affine.parallel thread safe.

**Comment by jbruestle** [comment]
@YangleiZouIntel, let me know if you are working on this, if not I can reassign.  Please followup with any questions.  I hope to land the CacheWrite support by Thursday.

**Comment by YangleiZouIntel** [comment]
> @YangleiZouIntel, let me know if you are working on this, if not I can reassign. Please followup with any questions. I hope to land the CacheWrite support by Thursday.

Yes, we are working on this.
