### ISSUE TITLE
Initial OpenCL/SPIRV lowering

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1245]
OpenCL/SPIRV lowering and support for some correctness testing to CI.  This may require https://github.com/plaidml/plaidml/issues/1244. 

Current WIP: https://github.com/plaidml/plaidml/pull/1237

Additionally, consider updating kernel outlining to upsteam version https://github.com/llvm/llvm-project/blob/master/mlir/lib/Dialect/GPU/Transforms/) which now outlines ParallelOp rather than the code in https://github.com/plaidml/plaidml/tree/plaidml-v1/pmlc/conversion/SCFToGPU.

Or alternately, we should consider doing outlining directly from PXA (which may be simpler).  Regardless, outlining from affine.for can potentially produce incorrect code as it fails to consider races.

**Comment by jbruestle** [comment]
@kdobros, let me know if you need any help on this or would like to split up the work somehow.  @earhart on the core team has been looking at this problem, and @YangleiZouIntel has some experience in this area as well.

**Comment by kdobros** [comment]
@jbruestle Thanks for creating the issue, it's a great step towards organizing the work

I will keep the status updates here and start splitting WIP PR into more manageable and ready to merge chunks.
I have already started upstreaming required llvm changes: https://reviews.llvm.org/D85196

Recently, I was wondering how this effort may relate to HAL concept you mentioned. On master branch I see it shares some similarities with comp dialect I'm working on. Do you think this something that may be connected?

**Comment by jbruestle** [comment]
Great work on the upstream commit (sorry I missed this comment until now, I need to figure out what is wrong with my notification settings).  Regarding the HAL, yes, I think the 'comp' dialect is a good step in the right direction of supporting asynchronous launching of computations, device allocation + DMA, and tracking of execution dependencies.  And it seems to me that it would be applicable across multiple accelerator platforms.  Given the size of the commit, it is a bit hard to review in detail, so I think staging it would be great.  It might be interesting to put together some RFC style documentation (in the more relaxed sense of RFC as used on the MLIR discourse) for some of the core bits, such as the comp dialect to provide more insight into the specific design choices, but that's not mandatory.

**Comment by kdobros** [comment]
Since OpenCL + SPIRV have achieved sign of life I'm closing this issue.
I have split remaining work on optimizations and functionality into separate tasks:
- #1407 [OpenCL] SPIRV Extended Instruction Set for ResNet
- #1408 [OpenCL] Add sub-groups lowering
- #1409 [comp] ExecEnv reuse optimization
- #1410 [comp] Add allocated memory reuse
- #1411 [comp] Add pass to remove redundant memory transfers
- #1412 [comp] Add pass to recalculate event dependencies
