### ISSUE TITLE
Implement / verify subgroup broadcast lowering for SPIRV to Gen9

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1247]
Currently it does not appear the the MIR SPIRV dialect has support for subgroup broadcast: https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpGroupBroadcast

This will be required (along with a representation of the same and a lowering) for the results of the subgroup pass to be lowered, which is critical to performance on the Gen9.

In addition to the appropriate upstream changes to SPIRV dialect, some form of tests that verify correctness on real hardware would be great.  Preferably these tests would end up in CI post https://github.com/plaidml/plaidml/issues/1246.

**Comment by jbruestle** [comment]
@abialas1, not sure if you are the appropriate person to assign this to, so feel free to reassign/deassign.

**Comment by jbruestle** [comment]
Also, heads up to @earhart

**Comment by abialas1** [comment]
@jbruestle , yes, let me work on that.
Regarding code lowering, let me know how you are going to implement it in the subgroups pass. As we do gpu->spirv dialect conversion then it make sense to have the GroupBroadcast instruction also added to GPU dialect (where other workgroup/subgroup functions are currently) and emit the gpu.GroupBroadcast directly from your pass. Not sure if we want to have such dialect mixture in pxa though.

**Comment by abialas1** [comment]
Added code review for OpGroupBroadcast addition to SPIRV dialect: https://reviews.llvm.org/D85435

**Comment by jbruestle** [comment]
Currently, the plan is to to have the output of the subgroup pass model the threads within the same subgroup as a single thread operating on a subgroup sized vector unit, and per-subgroup-thread scalar registers are modeled as a single vector register.  A subgroup broadcast is modeled as a vector.extractelement followed by vector.broadcast (i.e. extract from one of the subgroup registers and broadcast to all).  I intend customize the lowering to SPIRV to reintroduce the subgroup threads and to pattern match the two instruction pattern back to a subgroup broadcast in addition to transforming the vector instructions back.  That allows the PXA level optimizations to not require introducing new ops or semantics.
