### ISSUE TITLE
Fix various small lowering bugs in backend tests

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1249]
Fix all the test that do not involving a missing feature (i.e. gather).

**Comment by jbruestle** [comment]
@mars1026 This is basically a placeholder ticket, feel free to expand on the details, etc.

**Comment by mars1026** [comment]
testPow - fails to legalize eltwise.pow when one of the arguments is integer rather than float
testSparseCategoricalCrossentropy (& friends) - lowers to std.cmpi with condition as f32 instead of integer type
testSwitch - fails when eltwise.select condition is f32 instead of boolean

**Comment by flaub** [comment]
Are these all done now?

**Comment by mars1026** [comment]
indeed they are, looks like I just forgot to close it
