### ISSUE TITLE
What's the backend engine on Mac?

### ISSUE THREAD

**Issue by PhoenixShield** [plaidml/plaidml#126]
What's the backend engine the framework use while running on macOS with AMD GPU?
Is it OpenGL, Metal, or RoCM?

**Comment by choongng** [comment]
We recommend Metal for Mac due to better performance but OpenCL will work as well.

**Comment by PhoenixShield** [comment]
Thanks all! I'll try both.

**Comment by lesves** [comment]
This should be in an FAQ or something like that.
