### ISSUE TITLE
NotImplementedError: ArgMax is not directly implemented.

### ISSUE THREAD

**Issue by PhoenixShield** [plaidml/plaidml#127]
Dear Team,

While I'm using Plaidml, an NotImplementedError coming up:

`print model.evaluate(X_test,y_test,verbose=1)`

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-22-7ec798b542f6> in <module>()
      5 model.compile(loss='sparse_categorical_crossentropy',optimizer=opt,metrics=['accuracy'])
      6 #make sure weights are loaded correctly:
----> 7 print model.evaluate(X_test,y_test,verbose=1)
      8 #for i in range(10):
      9 #    y = model.predict(x=X_test, batch_size=batch_size,verbose=1)

/Library/Python/2.7/site-packages/keras/models.pyc in evaluate(self, x, y, batch_size, verbose, sample_weight)
    894                                    batch_size=batch_size,
    895                                    verbose=verbose,
--> 896                                    sample_weight=sample_weight)
    897 
    898     def predict(self, x, batch_size=32, verbose=0):

/Library/Python/2.7/site-packages/keras/engine/training.pyc in evaluate(self, x, y, batch_size, verbose, sample_weight, steps)
   1650         else:
   1651             ins = x + y + sample_weights
-> 1652         self._make_test_function()
   1653         f = self.test_function
   1654         return self._test_loop(f, ins,

/Library/Python/2.7/site-packages/keras/engine/training.pyc in _make_test_function(self)
    980                                             updates=self.state_updates,
    981                                             name='test_function',
--> 982                                             **self._function_kwargs)
    983 
    984     def _make_predict_function(self):

/Library/Python/2.7/site-packages/plaidml/keras/backend.pyc in function(inputs, outputs, updates, name)
    718     if name == None:
    719         name = ''
--> 720     return _Function(inputs, outputs, updates, name)
    721 
    722 

/Library/Python/2.7/site-packages/plaidml/keras/backend.pyc in __init__(self, inputs, outputs, updates, name)
    121                                    _device(),
    122                                    list(zip(self._input_names, inputs)),
--> 123                                    list(zip(self._output_names, outputs)), updates)
    124         self._invoker = plaidml.Invoker(_ctx, self._func)
    125 

/Library/Python/2.7/site-packages/plaidml/tile.pyc in compose(ctx, dev, inputs, outputs, updates)
   1006             to_be_bound.extend(reqs)
   1007             continue
-> 1008         bindings.insert(op, op.bind(bindings))
   1009         updates.extend(op.side_effects)
   1010 

/Library/Python/2.7/site-packages/plaidml/tile.pyc in bind(self, bindings)
    246         if not self.code:
    247             raise NotImplementedError('{} is not directly implemented.'.format(
--> 248                 self.__class__.__name__))
    249         applier = plaidml.Applier(bindings.ctx, plaidml.Function(self.code))
    250         for input_name, input_value in self.inputs.items():

NotImplementedError: ArgMax is not directly implemented.

Could anybody kindly help on this? Thanks!

Best regards,
Fang

**Comment by Rod-gt** [comment]
Hi,

Having the same issues as well when running model.fit_generator. 

Traceback (most recent call last):

  File "<ipython-input-11-385451daacd6>", line 8, in <module>
    verbose=0)

  File "/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)

  File "/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 39, in fit_generator
    model._make_train_function()

  File "/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 508, in _make_train_function
    **self._function_kwargs)

  File "/anaconda3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 661, in function
    return _Function(inputs, outputs, updates, name)

  File "/anaconda3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 137, in __init__
    name=name)

  File "/anaconda3/lib/python3.6/site-packages/plaidml/tile.py", line 1052, in compose
    bindings.insert(op, op.bind(bindings))

  File "/anaconda3/lib/python3.6/site-packages/plaidml/tile.py", line 276, in bind
    self.__class__.__name__))

NotImplementedError: ArgMax is not directly implemented.

**Comment by brianretford** [comment]
Apologies for letting this sit for this long. Implementing ArgMax required that we add the 'index' operation to tile, which we did, but we haven't added ArgMax yet. We'll add it into the next release (should be coming this week / early next week).

**Comment by tuenral** [comment]
Thanks for this great product which fills the gap for ML / DL on Macbook Pro devices.
Still, the argmax function was mandatory for my work and I did not manage to use PlaidML because of that.
I had to go for a cloud solutions in the meantime...

Hope to be able to use PlaidML (and its Argmax distributed function) soon!

**Comment by brianretford** [comment]
Hey, sorry about that, the release is coming soon, we're just dotting some i's and crossing some t's as it were related to releasing it via the Intel release process. Once that's done our release cadence will pick up.

**Comment by samw3** [comment]
Was this release?  I'm still getting this error.  Thanks.

**Comment by brianretford** [comment]
It hasn't actually been released, but we did push the code. If you pull from github and rebuild the plaidml-keras wheel and install that, it should work. The actual release should be coming very soon. Holidays + process.

**Comment by Sioxas** [comment]
How to build from source?

**Comment by brianretford** [comment]
Actually, this should be fixed now! Upgrade to 0.5.0
