### ISSUE TITLE
arm a72 platform

### ISSUE THREAD

**Issue by kaishijeng** [plaidml/plaidml#129]
I have RK3399 which is running ubuntu with Aarch64.
I can build plaidml successfully, but not able to install *.whl. Below is the error when I run pip2 install.

plaidml-0.0.0.dev0-py2.py3-none-manylinux1_x86_64.whl is not a supported wheel on this platform

Not sure why aboyt whl file is x84_64 instead of arm Aarch64. What do I need to change in the build script for Arm platform to fix this issue?

Thanks,

**Comment by tzerrell** [comment]
We've released 0.3.5 which includes the build configuration change described above. Let us know if it works for you.
