### ISSUE TITLE
Can't save model weights: issue with duplicate layer names

### ISSUE THREAD

**Issue by dilpreetsingh** [plaidml/plaidml#130]
I'm running into trouble with saving my auto-encoder model. When I run:
```python
model.save_weights(filepath)
```
I hit a runtime error in h5py:
```bash
RuntimeError: Unable to create link (name already exists)
```

Tracking down the issue, it seems to be a problem when one Model is embedded within another as a layer. Here is the source to replicate the issue:

```
from keras.layers import Input, Dense
from keras.models import Model

input_x = Input(shape=(100,), name='encoder_input')
x = Dense(50, activation='relu', name="dense_1")(input_x)
x = Dense(2, activation='relu', name="dense_2")(x)
encoder = Model(input_x, x, name='encoder')
outputs = encoder(input_x)

vae = Model(input_x, outputs, name='vae')
vae.save_weights('logs/temp.h5')
```

The issue can be seen when we print out operation/weight names for the `vae` model:
```
symbolic_weights = [layer.weights for layer in vae.layers][1] # Only interested in 2nd layer because first layer is input & has no weights
print([weight.name for weight in symbolic_weights])
```
The output is: `['kernel', 'bias', 'kernel', 'bias']` - the duplication in the names is the issue.

Comparatively, this is the output with the TensorFlow backend: `['dense_1/kernel:0', 'dense_1/bias:0', 'dense_2/kernel:0', 'dense_2/bias:0']` - TF prepends the name of the layer.

It's easy (in my case) to get around the issue, but thought it'd be important to raise.

My environment is:
- Python 3.6.4
- plaidml-keras==0.3.2
- keras==2.0.8

I tried to replicate this issue with the pre-realease version (0.3.3rc1) but ran into other issues (`AttributeError: module 'plaidml.tile' has no attribute 'convert_np_dtype_to_pml'`)

**Comment by tzerrell** [comment]
Thanks for the report! I believe we have fixed this in 0.3.3rc3 (along with the 0.3.3rc1 issue you mention), but let us know if you see either problem again in 0.3.3rc3 or later.
