### ISSUE TITLE
About Version-5 reshape 

### ISSUE THREAD

**Issue by YUIAZU000** [plaidml/plaidml#135]
I run onnx-plaidml on my model and got an error：
“Version-5 reshape() is not yet implemented by the PlaidML ONNX backend”
I find it caused by the function pixelshuffle I used. Do you have an incomplete implement of this operation?

**Comment by tzerrell** [comment]
This is discussed in https://github.com/plaidml/onnx-plaidml/issues/13. I'm closing this issue in favor of that one.
