### ISSUE TITLE
[edsl] Add sort intrinsic

### ISSUE THREAD

**Issue by flaub** [plaidml/plaidml#1442]
Should include:

* Ascending vs. descending option
* Partial sort (i.e. for TopK)
* Selection of axis to sort along.
* argsort semantics (returns indices rather than sorted tensor): https://www.tensorflow.org/api_docs/python/tf/argsort

**Comment by flaub** [comment]
Part 1 implement in #1455

**Comment by tzerrell** [comment]
I believe we want this to include:
* Ascending vs. descending option
* Partial sort (i.e. for TopK)
* Selection of axis to sort along.
