### ISSUE TITLE
[core] Constant buffer management

### ISSUE THREAD

**Issue by flaub** [plaidml/plaidml#1492]
We need a way to store constant buffers on a per-module basis. Constant buffers need to have a lifetime that matches their usage within a module. So there are two invalidation events:

1. When there are no longer any ops referring to a constant buffer.
2. When a module is destroyed, all constant buffers in that module should be destroyed.

A new `ConstantBufferMgr` singleton is proposed with the following API:

- `int64_t createBuffer(ModuleOp module, BufferPtr buffer)`: returns a unique ID
- `void destroyBuffer(ModuleOp module, int64_t bufferId)`: destroy the specified buffer
- `void destroyModule(ModuleOp module)`: destroy all buffers on the specified module
- `BufferPtr resolveBuffer(ModuleOp module, int64_t bufferId)`: resolve the specified buffer

Also create a new `OwningModuleRef` which calls `mgr->destroyModule(*this)` in the destructor of the module.

Add a cleanup pass which makes a sweep of all constant ops and calls `mgr->destroyBuffer(module, bufferId)` on each unreferenced buffer.

Modify existing EDSL constants so that they come in as `ConstantOp` rather than a program argument.

**Comment by earhart** [comment]
It might be useful to model a constant buffer as a function that fetches the data; that way the compiled code could release buffers that aren't needed in system memory any longer (e.g. after loading them onto a device).

**Comment by flaub** [comment]
@earhart It needs to work with non-LLVM targets

**Comment by earhart** [comment]
@flaub Definitely; do you think we'd want to implement the loading function as an interpretable instruction?
