### ISSUE TITLE
Very slow running CNN for Sentence classification

### ISSUE THREAD

**Issue by hongjuny** [plaidml/plaidml#151]
Thank you very much for your wonderful works, which makes me run jobs on my iMac. Still, few issues running some models, but I think it is manageable.
But, there is one thing I need your help. I am running CNN for Sentence Classification.
https://github.com/alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras
which works very fast with TensorFlow backend, but very slow with PlaidML. I guess it is even slower than TensorFlow CPU runs.
Presumably, the current version is not considered running that kind of model. Please advise.

**Comment by Sioxas** [comment]
It seems doesn't to be faster than Tensorflow CPU when using Metal.
Example code:
```python
# TensorFlow backend
# import tensorflow as tf
# from tensorflow import keras

# PlaidML backend
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
import keras

import numpy as np

fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

print("Train images shape:",train_images.shape)
print("Train labels:",len(train_labels))

print("Test images sharp",test_images.shape)
print("Test labels:",len(test_labels))

train_images = train_images / 255.0
test_images = test_images / 255.0

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=keras.activations.relu),
    keras.layers.Dense(10, activation=keras.activations.softmax)
])

model.compile(optimizer=keras.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5)

test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)
```
Using PlaidML Metal backend:
![image](https://user-images.githubusercontent.com/9740581/52985064-14e16800-342d-11e9-9b70-8b8aa9d98cca.png)
Using TensorFlow CPU backend:
![image](https://user-images.githubusercontent.com/9740581/52985095-2e82af80-342d-11e9-9973-e61dba66d0ee.png)
The TensorFlow CPU is about 5x faster than PlaidML .

**Comment by brianretford** [comment]
Your network is so small that launch & memory transfer overhead is going to exceed any possible gain from the GPU. Additionally GPUs really benefit from a reasonable minibatch size - try with a reasonable batch size and a more realistic network and you should see some very noticeable differences.

**Comment by brianretford** [comment]
@hongjuny sorry for not seeing this long ago - currently plaidml is very slow training anything w/ embeddings due to the lack of a mechanism to produce high performance scatter/gathers. This is something we'll be addressing in 1.0, it's also in issue #96
