### ISSUE TITLE
Pseudo-random generation from tiles

### ISSUE THREAD

**Issue by vermorel** [plaidml/plaidml#155]
Random number generation is used for weight initialization in deep learning. It is also used for all sort of learning techniques (eg. dropout) during the execution itself. Yet, it does not seem that the tile language offers any support for pseudo-random number generation. This feature would be useful.

Also, such a feature was to happen, I would suggest (difficult) to make it possible to ensure that the execution remains deterministic. Indeed, real randomness complicates debugging, as bugs become Heisenbugs. Thus, it would be nice to have control on the _seeding_ mechanism of the pseudo-random generator.

**Comment by tzerrell** [comment]
Tile has PRNG support already, offered via the functions `prng_value`, `prng_state`, and `prng_step`. See the `dropout` and `random_uniform` functions from the [Keras backend](https://github.com/plaidml/plaidml/blob/master/plaidml/keras/backend.py) for examples of how to use them, and `_make_rng_state` for an example of how to seed them.

**Comment by vermorel** [comment]
@tzerrell Thanks a lot for the  link!
