### ISSUE TITLE
Why package version on PyPI more higher than in Github?

### ISSUE THREAD

**Issue by ivan-achlaqullah** [plaidml/plaidml#156]
On PyPI [plaidml](https://pypi.org/project/plaidml/#history) currently listed as version 0.3.4 and released on  6 June 2018.

Meanwhile, the latest commit on this repo are #121, which is in 15 May 2018, and the last release on this repo are 0.3.3rc1.

**Comment by tzerrell** [comment]
Sorry about the out of sync versions, we're putting together a release that will clean this up.

**Comment by tzerrell** [comment]
PyPI and GitHub releases are back in sync with 0.3.5 release
