### ISSUE TITLE
CNN training fails with wrong shape

### ISSUE THREAD

**Issue by OliverUrbann** [plaidml/plaidml#159]
I'm trying to train the following model:

    model = Sequential()
    model.add(Convolution2D(32, (3, 3), padding='same', activation='relu',
                            input_shape=(img_shape[1], img_shape[0], img_shape[2])))
    model.add(Convolution2D(32, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Convolution2D(64, (3, 3), padding='same', activation='relu'))
    model.add(Convolution2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(2, activation='softmax'))

    model.summary()

    model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['categorical_accuracy'])
    model.fit_generator(generate_xy(img_db, img_shape), steps_per_epoch=len(img_db), nb_epoch=10)

However, training failed with:

ValueError: Error when checking target: expected dense_2 to have 2 dimensions, but got array with shape (4650, 1, 2)

Using tensorflow this model works. My platform is macOS 10.13.6 with following versions:

plaidml 0.3.4, Keras 2.0.8, Python 3.6

I've tried CPU, OpenCL and Metal, all the same. Also changing the model does not help. Trying to reshape or flatten the output also fails as it already has dim 2.

**Comment by tzerrell** [comment]
This looks like the same problem as in #149; we're putting together a release to address this, but you can also find a workaround there.

**Comment by OliverUrbann** [comment]
I noticed this ticket but the workaround does not help but I will wait for the fix of this bug and try again. Thx!

**Comment by tzerrell** [comment]
Hopefully this is fixed in the 0.3.5 release -- let us know if that works for you (and feel free to reopen if it doesn't)!
