### ISSUE TITLE
Check fails after installation

### ISSUE THREAD

**Issue by itsoryo** [plaidml/plaidml#160]
user$ plaidbench keras mobilenet
Running 1024 examples with mobilenet, batch size 1
INFO:plaidml:Opening device "metal_amd_radeon_pro_560x.0"
could not broadcast input array from shape (3,2048) into shape (6144)
Set --print-stacktraces to see the entire traceback

**Comment by tzerrell** [comment]
This looks like the same problem as in #149; we're putting together a release that should address this, but you can also find a workaround there.

**Comment by fishhf** [comment]
Is there an older version that actually works out of the box?

**Comment by tzerrell** [comment]
This should be fixed in our 0.3.5 release! Let us know if it works for you.
