### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by ljppro** [plaidml/plaidml#161]
Hi,

When I building plaidml with:
bazel build --config linux_x86_64 plaidml:wheel plaidml/keras:wheel

It reports:
Error downloading [https://storage.googleapis.com/external_build_repo/llvm-3.8.1.src.tar.gz] to /home/***/.cache/bazel/_bazel_liujp/2b73c00b6288de6c8a6b4664edf1c171/external/llvm_archive/llvm-3.8.1.src.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

It seems this is a notorious issue in bazel or in java. But do you have a workaround there?

Thanks!

**Comment by tzerrell** [comment]
I don't believe we've encountered this ourselves and so don't have a specific workaround. Just off the top of my head, perhaps try manually downloading that file to that location before running the build? (I gave this less than a minute of thought though, use at your own risk and honestly you're probably better off looking at the general purpose bazel/java workarounds.)

If you learn something about this that would be useful on our end please reopen and let us know.
