### ISSUE TITLE
Issues when using keras.max and keras.argmax 

### ISSUE THREAD

**Issue by hawajka76** [plaidml/plaidml#1634]
Hi, I'm getting errors whilst using these functions when running with plaidml as the backend. 

For example as a result of running the following code:

a=[[1,2,3,6,2,1]]
print(a)
print(K.argmax(a,axis=-1))

I should obtain the output:

[[1, 2, 3, 6, 2, 1]]
Tensor("ArgMax_8:0", shape=(1,), dtype=int64)

Instead I'm getting the following output and errors:

Using plaidml.keras.backend backend.

[[1, 2, 3, 6, 2, 1]]
Traceback (most recent call last):
  File "C:xxx/PycharmProjects/ml3/main.py", line 24, in <module>
    print(K.argmax(a,axis=-1))
  File "C:xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\tile.py", line 257, in function
    operation = cls(*args, **kwargs)
  File "C:xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\op.py", line 1035, in __init__
    shape, axes, subs = tile.compute_aggregation_axes(value.shape.dims, [axis], False)
AttributeError: 'list' object has no attribute 'shape'

Do you think there is a way to fix this?

**Comment by brianretford** [comment]
There definitely is  - the PlaidML be should be coverting lists to tenaors in this case but it's not happening. If you do that first it should work

________________________________

**Comment by hawajka76** [comment]
Thank you, that seems to be at least part of the solution! However the output appears to be in the plaidml.tile.value and not Tensor format and using the keras.max function causes an error.

For example when I input: 

      a=[[1,2,3,6,2,1]]
      a1=tf.convert_to_tensor(a)
      print((K.argmax(a1,axis=-1).eval()))
      print(type(K.argmax(a1,axis=-1)))
      print((K.max(a1,axis=-1)))

I obtain:

    [3]
    <class 'plaidml.tile.Value'>

    File "C:/Users/xxx/PycharmProjects/ml3/main.py", line 30, in <module>
        print((K.max(a1,axis=-1)))
      File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\keras\backend.py", line 59, in wrapper
        return func(*args, **kwargs)
      File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\keras\backend.py", line 1004, in max
        return op.max_reduce(x, axes=axis, keepdims=keepdims)
      File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\op.py", line 2026, in max_reduce
        return MaxReduce.function(x, axes=axes, keepdims=keepdims)
      File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\tile.py", line 257, in function
        operation = cls(*args, **kwargs)
      File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\op.py", line 2015, in __init__
        super(MaxReduce, self).__init__(f, [('I', x)], [('O', tile.Shape(x.shape.dtype, shape))])
    AttributeError: 'TensorShape' object has no attribute 'dtype'

**Comment by tzerrell** [comment]
You can't use tensorflow functions (like `tf.convert_to_tensor`) when using PlaidML as the Keras backend. You can convert numeric list-of-lists like `a` from your example with the Keras native backend function `variable`, i.e.
```
import keras.backend as K
a = [[1, 2, 3, 6, 2, 1]]
a1 = K.variable(a)
print(K.argmax(a1, axis=-1).eval())
```
should print
```
[3]
```

**Comment by hawajka76** [comment]
Thank you for your help, that does work on the above example. However when I try using K.variable on something more complicated like in the code below:

    def filter (box_confidence, boxes, box_class_probs, threshold=.6):
    
        box_scores = box_confidence *  box_class_probs
        box_scores = K.variable(box_scores)
        box_classes = K.argmax(box_scores, axis=-1)
        box_class_scores = K.max(box_scores, axis=-1)
    
        filtering_mask = (box_class_scores >= threshold)
    
        scores = tf.boolean_mask(box_class_scores, filtering_mask)
        boxes = tf.boolean_mask(boxes, filtering_mask)
        classes = tf.boolean_mask(box_classes, filtering_mask)
    
        return scores, boxes, classes
    
    
    with tf.compat.v1.Session() as test:
        box_confidence = tf.compat.v1.random_normal([19, 19, 5, 1], mean=1, stddev=4, seed = 1)
        boxes = tf.compat.v1.random_normal([19, 19, 5, 4], mean=1, stddev=4, seed = 1)
        box_class_probs = tf.compat.v1.random_normal([19, 19, 5, 80], mean=1, stddev=4, seed = 1)
        scores, boxes, classes = filter(box_confidence, boxes, box_class_probs, threshold = 0.5)

I get an error referring to converting a symbolic tensor:

      Traceback (most recent call last):
        File "C:/Users/xxx/PycharmProjects/ml3/main.py", line 57, in <module>
          scores, boxes, classes = filter(box_confidence, boxes, box_class_probs, threshold = 0.5)
        File "C:/Users/xxx/PycharmProjects/ml3/main.py", line 40, in filter
          box_scores = K.variable(box_scores)
        File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\keras\backend.py", line 59, in wrapper
          return func(*args, **kwargs)
        File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\keras\backend.py", line 1937, in variable
          view.copy_from_ndarray(value)
        File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\plaidml\__init__.py", line 1223, in copy_from_ndarray
          np.copyto(dst, src)
        File "<__array_function__ internals>", line 6, in copyto
        File "C:\Users\xxx\PycharmProjects\ml2\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 855, in __array__
          " a NumPy call, which is not supported".format(self.name))
      NotImplementedError: Cannot convert a symbolic Tensor (mul:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
      
      Process finished with exit code 1

Without using K.variable I run into the "dtype" error with K.max. What could be a good way of overcoming these issues?

**Comment by tzerrell** [comment]
You can't use TensorFlow functions with the PlaidML backend. (These are the ones that look like `tf.[something]`.) Otherwise you are running partially in PlaidML and partially in TensorFlow, without either knowing the other exists or having a way to communicate to the other.

Generally speaking, you need to use entirely Keras functions (so functions that look like `K.[something]`); so rewrite your code using such functions to fix these errors. (It is also possible to directly write PlaidML Tile code that will interoperate with the Keras code when using the PlaidML backend. However, while this allows you to express operations that don't exist in Keras, it also adds complexity and prevents you from running the networks with non-PlaidML backends (e.g. TensorFlow).)

In your case, you will need to replace `tf.compat.v1.random_normal` and `tf.boolean_mask`. I haven't looked at the TensorFlow docs for those functions, but guessing by the names, you can probably use `K.random_normal_variable` and `K.switch` instead.

**Comment by hawajka76** [comment]
Thanks tzerrell for clarifying this! I understand now and will change the code.
