### ISSUE TITLE
TypeError: unsupported operand type(s) for ** or pow(): 'float' and 'str'

### ISSUE THREAD

**Issue by StudyCrec** [plaidml/plaidml#1703]
I am just a python beginner.
I tried to make a compound interest project
But i keep getting this error.
Could anyone tell me what the error means?

**Comment by tzerrell** [comment]
Without knowing details exactly what's going wrong is a bit unclear, but this generally means the code is doing something like `3.5 ** "example"`, i.e., raise `3.5` to the power `"example"`. This doesn't make sense and so isn't implemented, causing this error.

See e.g. https://stackoverflow.com/questions/17056264/typeerror-unsupported-operand-types-for-or-pow-str-and-int

I'm closing this issue as not being related to a PlaidML bug or feature, but if you trace this to something in the PlaidML code feel free to reopen.
