### ISSUE TITLE
Can PlaidML generate CUDA kernels?

### ISSUE THREAD

**Issue by kirliavc** [plaidml/plaidml#172]
I installed PlaidML in my server with NVIDIA GPUs, but PlaidML doesn't generate CUDA kernels with the examples (keras mobilenet and PlaidML API python code). So is there any way to launch CUDA kernels with plaidml?

**Comment by PeteSero** [comment]
Does the command plaidml-setup list any CUDA devices?

**Comment by kirliavc** [comment]
> Does the command plaidml-setup list any CUDA devices?

@PeteSero No, it lists my NVIDIA GPUs, but only OpenCL-xxx. No "CUDA" is shown in that list.

**Comment by PeteSero** [comment]
This document
docs/installing.md
has the steps for installing CUDA on Linux in a way that PlaidML can use it. 
No support on macos I would assume.

In addition you can check
vendor/cuda/configure.bzl
to see how CUDA is detected at build time -- try building from source to see whats going on.
(If you have just installed the Python modules before.)

**Comment by brianretford** [comment]
Thanks for the help PeteSero! Closing for now - kirliavc feel free to reopen if you have more questions. We've found OpenCL and CUDA to be basically equivalent performance wise. Is there a particularly reason you want to use CUDA?
