### ISSUE TITLE
Is it possible to generate optimized OpenCL kernel using PlaidML?

### ISSUE THREAD

**Issue by pyshpa** [plaidml/plaidml#174]
Hi,

I am using keras as frontend, is it possible to get optimized kernel code of my model using PlaidML?

**Comment by brianretford** [comment]
You mean, you would like to actually see the generated kernels? We currently support this for OpenCL (You can use nvidia's tools to get kernel code for the CUDA backend).

set PLAIDML_OPENCL_CACHE="./" (or wherever you want the kernels dumped), run your program, and you should get the kernels. If you set the logging level high enough, it will also dump them, I believe.
