### ISSUE TITLE
Is plaidml supported on eGPU AMD cards for newer MacBook Pro models? 

### ISSUE THREAD

**Issue by PatrickUtz** [plaidml/plaidml#175]
I am wondering if I will be able to use plaidml to run Keras (and Tensorflow, naturally) using an AMD card/eGPU set up with my MacBook Pro late-2017 model. Any indication of this working would be greatly appreciated. Thank you!

**Comment by brianretford** [comment]
It should work, definitely use Metal though, not OpenCL. PlaidML doesn't currently support tensorflow, only Keras and ONNX. We expect that to change in the near future though :-)

plaidml training resnet on my macbook 2017 (about 4x faster than CPU -- we should be able to do better than this --  we have ground to cover on lower memory GPUs)

Feel free to file a bug if things don't work.

```
$ kill -9 7696
bretford-mac01:plaidml bretford$ plaidbench --epochs 1 --batch-size 8 -n 1024 keras resnet50 --train
Running 1024 examples with resnet50, batch size 8
Loading CIFAR data
INFO:plaidml:Opening device "metal_amd_radeon_pro_560x.0"
Model loaded.
Compiling network...
Epoch 1/1
INFO:plaidml:Analyzing Ops: 260 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 813 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 1565 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 2279 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 2601 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 2797 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 2923 of 4641 operations complete
INFO:plaidml:Analyzing Ops: 3119 of 4641 operations complete
8/8 [==============================] - 33s 4s/step - loss: 7.7045 - acc: 0.0000e+00
Warming up ...
Epoch 1/1
32/32 [==============================] - 4s 121ms/step - loss: 6.3853 - acc: 0.0938
Main timing
Epoch 1/1
1024/1024 [==============================] - 124s 121ms/step - loss: 2.0899 - acc: 0.4297
Example finished, elapsed: 33.728490114212036 (compile), 124.18803906440735 (execution), 0.1212773818988353 (execution per example)
```

**Comment by PatrickUtz** [comment]
Fantastic, thank you!

**Comment by mikolajkania** [comment]
@brianretford 

> we have ground to cover on lower memory GPUs

It is great to hear that, is there any progress on that?

**Comment by brianretford** [comment]
Yes actually! We released a paper recently that describes the new compiler stack we are retrofitting into plaid. We are working on a new GPU backend that will be much more flexible and has a smarter scheduling algorithm. It's basically working now but not quite as fast as the old code. We'll have a blog post out soon with instructions on how to test the new system out.

https://arxiv.org/abs/1903.06498
