### ISSUE TITLE
Running on a Raspberry Pi cluster as Keras + Plaidml to do GPT-2 training in different language

### ISSUE THREAD

**Issue by rnbokade** [plaidml/plaidml#1775]
I am trying to train a GPT-2 in Hindi language using Raspberry Pi cluster as my Master's degree Project. I know this sounds foolish at first go and might not even be completely possible. But I want to try. Since if this works, however small the possibilities maybe right now, this will mean that ML can become more accessible, especially to underprivileged institutes which can't afford expensive hardware. Also if this works on above mentioned setup, then this may even be made to work on cluster of old smartphones which have powerful CPUs and GPUs. So yeah... anyone up for helping me and guiding on this??

**Comment by alheinecke** [comment]
stale issue, RPi is not supported by PlaidML-v1
