### ISSUE TITLE
Right way to negate bool tensors?

### ISSUE THREAD

**Issue by gyenesvi** [plaidml/plaidml#180]
I am using the following code for negating bool tensors:

```
func = plaidml.Function("function (I) -> (O) { O = (I == 0); }")
```

The input is set as follows:

```
input_data = np.ones([4], dtype=np.bool)
input = plaidml.tile.Value.from_python_value(input_data, ctx=context, dev=device).var

invoker = plaidml.Invoker(context, func, inputs={'I': input})
```

It works on metal_amd_radeon_r9_m370x, opencl_amd_amd_radeon_r9_m370x_compute_engine, opencl_cpu, llvm_cpu, but does not compile on opencl_intel_iris_pro and metal_intel_iris_pro_graphics backends on MacBook Pro. I get the error (while compiling the CL kernel):

"Cannot downconvert and widen scalar type 'int' to vector type '__char2'
      char2 LX_T1 = (LX_I_0 == 0);"

If I use `O = (I == 0.0)` instead, it works on opencl_intel_iris_pro but not on metal_intel_iris_pro_graphics.

Is this the best way to do negation? I also tried `O = cmp_eq(I,0)` with similar results.

**Comment by earhart** [comment]
That's a fine way to do negation (I used `cmp_eq(I,0)` in our ONNX frontend, anyway).  I think it's a bug; I know of at least one similar to this in the Metal backend that hasn't made it through to a release yet.  I'll add this to our unit test suite, and see if it still fails on any of our reference hardware; if so, I'll try to get a fix into our next release.

In the meantime, given the error, I suspect you can work around it by disabling vectorization.  If you look in `experimental.json`, there's a setting for each device, `vec_size`; if you set that to `1`, it won't use vector types.

**Comment by gyenesvi** [comment]
Thanks, let me know when it's fixed!

**Comment by brianretford** [comment]
Hey, sorry for the delay here, have you updated to Mojave? We've observed a lot of problems go away in Mojave. I'll check with Rob re: status

**Comment by gyenesvi** [comment]
Not yet, but I will try that, thanks!

**Comment by brianretford** [comment]
Have you given this a try yet?

**Comment by gyenesvi** [comment]
This seems to be working fine now.

**Comment by dgkutnic** [comment]
Thanks for following up. Closing this now as it is resolved.
