### ISSUE TITLE
Using plaidbranch and tensorflow as backend in Windows 10

### ISSUE THREAD

**Issue by darlanpj** [plaidml/plaidml#181]
Hello guys.  I'm using plaidml and plaidbranch for my postgraduate work. However, I have an impediment. I am not able to run the tensorflow as backend using the following command:

`python. \ plaidbench.py --no-plaid xception `

The following message appears:

> Using TensorFlow backend. Error: Missing needed packages for benchmark; to fix, pip install keras tensorflow

I am using the Windows 10 platform. I already have the tensorflow installed in the version of Python 3.6.6

tensorboard == 1.10.0 
tensorflow == 1.10.0
tensorflow-gpu == 1.10.0 
plaidbench==0.3.5
plaidml==0.3.5
plaidml-keras==0.3.5
Keras==2.2.2
Keras-Applications==1.0.4
Keras-Preprocessing==1.0.2

I have an AMD GPU in my notebook. I tried searching the internet but I have not encountered anyone with this problem so far, if anyone have any ideas could share??

Thanks

**Comment by brianretford** [comment]
We now support tensorflow through nGraph. You can build it yourself via the instructions in `docs/building.md`, or there will be an official release later this month

**Comment by vesran** [comment]
It looks like nGraph is not supported on Windows systems. Any suggestion for such a configuration ?
