### ISSUE TITLE
linalg dialect version of layout pass

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1830]
Add support for:
- [x] Recognize Conv2d and add pre/post reorders and blocking to Conv2d itself
- [x] Add a canonicalization to change reorder/eltwise + eltwise/redorder
- [x] Add a canonicalization to remove pairs of reorders which together form an identity.

**Comment by flaub** [comment]
First part implemented in #1865

**Comment by flaub** [comment]
Reorder fowarding thru eltwise ops is also implemented in #1865

**Comment by flaub** [comment]
Adjacent reorders are folded in #1881
