### ISSUE TITLE
AttributeError:  'ConvolutionGrouping'

### ISSUE THREAD

**Issue by rlong011** [plaidml/plaidml#186]
I'm getting this error AttributeError: module 'plaidml.op' has no attribute 'ConvolutionGrouping' when trying to run this code:

from keras.layers import Flatten, Activation
K.clear_session()
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(28, 28, 1)))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
~/plaidml-ven36/lib/python3.6/site-packages/plaidml/keras/backend.py in conv(x, kernel, strides, padding, data_format, dilation_rate, channelwise)
    448         grouping = op.ConvolutionGrouping.MAX
    449     else:
--> 450         grouping = op.ConvolutionGrouping.NONE
    451     return op.convolution(
    452         x,

AttributeError: module 'plaidml.op' has no attribute 'ConvolutionGrouping'

**Comment by rlong011** [comment]
That was the problem, sorry, don't know how that happened.  Thank you very much

**Comment by brianretford** [comment]
We could probably detect this and warn users.

Sent from my iPhone

On Oct 3, 2018, at 9:59 AM, rlong011 <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #186<https://github.com/plaidml/plaidml/issues/186>.

**Comment by wwwgui** [comment]
I happened to see the same issue. Later fixed by reinstall

pip install plaidml-keras plaidbench
