### ISSUE TITLE
Using multiple GPUs ?

### ISSUE THREAD

**Issue by fmichaud** [plaidml/plaidml#191]
Hello,

First, thank you for this great project ! I can finally process data with Keras using an AMD GPU...
Is it possible to use multiple GPUs during computing data ?

Regards from France,

**Comment by brianretford** [comment]
Hey François,

Currently PlaidML doesn’t support multi-gpu configurations. We are currently working on a very core refactoring of how we generate code that will enable multi-gpu support. We hope to start publishing public roadmaps and more information on the new system soon.

**Comment by SolankiAnand** [comment]
Do we have any update on this?

**Comment by brianretford** [comment]
We've completed the refactorings that we wanted to, yes. We're working on porting all of PlaidML to work on top of the new system, at which point adding multi-gpu support should straightforward.

**Comment by SolankiAnand** [comment]
@brianretford great, thank you! Could you please share the approximate timeline?

**Comment by brianretford** [comment]
We're hoping to have a prototype GPU stripe-backend out in 0.6, at which point multi-GPU support is pending hiring on the Intel side (underway) or a community member deciding to implement it :-)

**Comment by ClassyNinjaPirate** [comment]
Hello,
forgive me, but I don't understand  what "We're hoping to have a prototype GPU stripe-backend out in 0.6" means. When is it expected? 
sorry and thanks again.

**Comment by asheetal** [comment]
Hoping to see multi-gpu support on plaidml soon

**Comment by aviallon** [comment]
Hello,
is it already there ? I didn't find anything related to that in the docs.
Thanks for the good work anyway.

**Comment by gbrow004** [comment]
Will there be a limit on the number of GPU's that PlaidML will be able to use? Assuming the hardware side of things is setup properly, of course.

**Comment by brianretford** [comment]
Well, there might be a productive limit for a particular problem, but technically there probably won't be limits? To catch up with the questions above, the new backend will not inherently support multi-GPU but will make doing so more feasible. I imagine it will still be an intensive project, one that we haven't started yet but would like to start when we have resources available.

**Comment by aviallon** [comment]
That would be very nice :)

**Comment by brianretford** [comment]
Duplicate of #32
