### ISSUE TITLE
neural network doesn't output the results

### ISSUE THREAD

**Issue by ThChatz** [plaidml/plaidml#1948]
When i try to pass an example through my network it outputs something like '<tile.Value Add FLOAT32(1, 2)>'. I just want the numbers thx.

**Comment by chelini** [comment]
Can you be a bit more specific? What is your input? What commands are you using? Thanks.

**Comment by ThChatz** [comment]
My model

```
model = Sequential([Dense(4, input_shape=(4,))
                    , LeakyReLU()
                    , Dense(16)
                    , LeakyReLU()
                    , Dense(4)
                    , LeakyReLU()
                    , Dense(4)
                    , LeakyReLU()
                    , Dense(2)
                    ])               
```
and im running

``model(K.reshape(K.constant([1,2,3,4]), (1,4)))``

where K is keras.backend

I would like to see the numerical result of that inference

**Comment by ThChatz** [comment]
nvm found out that you can use K.eval().
