### ISSUE TITLE
plaidml with AMD RX570 working on Linux, but not Windows

### ISSUE THREAD

**Issue by gh-kb** [plaidml/plaidml#196]
I installed plaidml via pip in an environment on a Win10, Anaconda 3 machine with AMD RX570. 

The plaidml-setup (and plaid itself) works when I have the AMD RX570 disconnected and allows me to select the GPU built into the i7 6700. When I connect power to the RX570 and run the setup again, plaidml-setup shows the  Thanks and Notes, and goes to C: prompt without offering to select any GPU. Plaidml supposedly works with RX 570 on Linux.

**Comment by brianretford** [comment]
Hmmm. Can you try and get a dump from clinfo? https://github.com/Oblomov/clinfo
Our CI cluster has an nvidia / windows machine, we currently don't have coverage of AMD / windows, but it should work.

**Comment by brianretford** [comment]
(apologies for the delay in responding)

**Comment by gh-kb** [comment]
Thank you for the follow up. 
clinfo shows 2 AMD Accelerated Parallel Processing platforms(#1 and #3, Intel built in is #2), despite that I have one RX570 GPU.
clinfo > dump.txt shows the details of the AMD Accelerated Parallel Processing platform 1 (AMD) and 2 (Intel built in GPU)
running clinfo with an output to the terminal shows some info on Accelerated Parallel Processing platform 3, with errors in it, That portion of the dump is not present in the dump.txt. I manually copied it to dump2.txt

Is this a simple driver problem? I installed the standard AMD Radeon driver package
[dump.txt](https://github.com/plaidml/plaidml/files/2587945/dump.txt)
[dump2.txt](https://github.com/plaidml/plaidml/files/2587946/dump2.txt)

**Comment by gh-kb** [comment]
I tested with 3 different Win drivers available on AMD web site. 

The driver 18.9.3-oct5 (display driver version 24.20.13019.1008) seems to work. It allowed to select a nonexperimantal opencl device and passed the plaidbench

This issue is resolved. Thank you for the help.
