### ISSUE TITLE
Keras contrib DSSIM loss not working

### ISSUE THREAD

**Issue by igerryffed** [plaidml/plaidml#199]
I have tried (with no success), to compile a model with dssim loss but:
-DSSIM implementation use KC.extract_image_patches wich does not exist in plaidml (in theano and tf it does)
-I have tried removing the patches and correcting the code so that it still work (in dssim.py in keras-contrib), it doesn't: I get weird errors on K.mean
-I have tried using this implementation:
def DSSIM_coef(y_true,y_pred, c1, c2):
	u_true=np.mean(y_true, axis=-1)
	u_pred=np.mean(y_pred, axis=-1)

	var_true=np.var(y_true, axis=-1)
	var_pred=np.var(y_pred, axis=-1)

	std_true=np.sqrt(var_true)
	std_pred=np.sqrt(var_pred)

	ssim=(2*u_true*u_pred+c1)*(2*(std_pred*std_true)+c2)
	denom=(u_true*u_true+u_pred*u_pred+c1)*(var_pred+var_true+c2)

	ssim/=np.clip(denom, K.epsilon(),np.inf)
	return np.mean((1.0-ssim)/2.0)

def DSSIM_Loss(c1,c2):
	def DSSIM(y_true,y_pred):
		return DSSIM_coef(y_true,y_pred, c1, c2)
	return DSSIM
Same thing I get weird errors, actually you can see I wrote np.stuff and not K.stuff because I have tried using K and it didn't work, then I changed to numpy it still didn't work

**Comment by igerryffed** [comment]
sorry for the messy code, github didn't even let me insert code, and now I can't even edit my message, I will write here again (hopefully) with better insertion:

        def DSSIM_coef(y_true,y_pred, c1, c2):
                u_true=np.mean(y_true, axis=-1)
                u_pred=np.mean(y_pred, axis=-1)

                var_true=np.var(y_true, axis=-1)
                var_pred=np.var(y_pred, axis=-1)

                std_true=np.sqrt(var_true)
                std_pred=np.sqrt(var_pred)

                ssim=(2*u_true*u_pred+c1)*(2*(std_pred*std_true)+c2)
                denom=(u_true*u_true+u_pred*u_pred+c1)*(var_pred+var_true+c2)

                ssim/=np.clip(denom, K.epsilon(),np.inf)
                return np.mean((1.0-ssim)/2.0)


        def DSSIM_Loss(c1,c2):
                def DSSIM(y_true,y_pred):
                        return DSSIM_coef(y_true,y_pred, c1, c2)
                return DSSIM

**Comment by brianretford** [comment]
Sorry for the delay - what kind of errors are you seeing? If you can give us a complete file to repro we can dig in more quickly.

**Comment by aviallon** [comment]
Hello, I got exactly the same error : 
```python
Namespace(arch='large3', bsize=35, dataset='data', history=0, name='all-bigdataset-dssim', noises=['poisson', 'gaussian', 'wavelet', 'salt'], opencl=1, resume=0)                  │············
INFO:plaidml:Opening device "opencl_amd_ellesmere.0"                                                                                                                               │············
Traceback (most recent call last):                                                                                                                                                 │············
  File "train.py", line 447, in <module>                                                                                                                                           │············
    model.compile(loss=DSSIM_MSE(), optimizer=opt, metrics=['accuracy', 'mse'])                                                                                                    │············
  File "/usr/lib/python3.7/site-packages/keras/engine/training.py", line 342, in compile                                                                                           │············
    sample_weight, mask)                                                                                                                                                           │············
  File "/usr/lib/python3.7/site-packages/keras/engine/training_utils.py", line 411, in weighted                                                                                    │············
    score_array = fn(y_true, y_pred)                                                                                                                                               │············
  File "train.py", line 443, in loss                                                                                                                                               │············
    return 0.6*keras.losses.mean_squared_error(y_true,y_pred) + 0.4*dssim(y_true,y_pred)                                                                                           │············
  File "/usr/lib/python3.7/site-packages/keras_contrib/losses/dssim.py", line 45, in __call__                                                                                      │············
    patches_pred = KC.extract_image_patches(y_pred, kernel, kernel, 'valid',                                                                                                       │············
AttributeError: module 'keras_contrib.backend' has no attribute 'extract_image_patches'
```

**Comment by brianretford** [comment]
This should work now, extract image patches has been implemented

**Comment by aviallon** [comment]
Thanks!
