### ISSUE TITLE
Not able to select GPU with plaidml-v1

### ISSUE THREAD

**Issue by sagar-bhayani** [plaidml/plaidml#1991]
I am trying to use latest plaidml from plaidml-v1 branch but during plaidml-setup it doesn't show gpu devices.

```
PlaidML Setup (1.0.0)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0


Selected device:
    llvm_cpu.0

A target determines the compiler configuration and should be matched with your device.
Please choose a default target:
   1 : llvm_cpu

Default target? (1)[1]:


```

But if I use older version of plaidml 0.7.0 I can see gpu in listed devices.

```
PlaidML Setup (0.7.0)

Thanks for using PlaidML!

The feedback we have received from our users indicates an ever-increasing need
for performance, programmability, and portability. During the past few months,
we have been restructuring PlaidML to address those needs.  To make all the
changes we need to make while supporting our current user base, all development
of PlaidML has moved to a branch — plaidml-v1. We will continue to maintain and
support the master branch of PlaidML and the stable 0.7.0 release.

Read more here: https://github.com/plaidml/plaidml

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml/issues
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0


Default Config Devices:
   llvm_cpu.0 : CPU (via LLVM)
   opencl_nvidia_nvidia_geforce_rtx_3080.0 : NVIDIA Corporation NVIDIA GeForce RTX 3080 (OpenCL)

Experimental Config Devices:
   llvm_cpu.0 : CPU (via LLVM)
   opencl_nvidia_nvidia_geforce_rtx_3080.0 : NVIDIA Corporation NVIDIA GeForce RTX 3080 (OpenCL)
```

Can someone help selecting GPU devices to be used for plaidml-v1?

**Comment by sagar-bhayani** [comment]
Gentle reminder for issue. Can someone help to test plaidml-v1 on GPU devices?
Thanks.

**Comment by sagar-bhayani** [comment]
Gentle reminder.

**Comment by hfp** [comment]
Perhaps take a look at https://github.com/plaidml/plaidml/issues/1989 (specifically the conversation about ongoing development).

**Comment by sagar-bhayani** [comment]
Thanks for the response @hfp , Mentioned issue doesn't talk much about GPU usage.  Could you clarify if enabling GPU device is part of ongoing development or if I am missing some basic steps to enable and can be enable easily by some code/condition change?

**Comment by hfp** [comment]
Development of PlaidML generally stopped incl. GPU target. As noted in #1989, we take the idea of using/relying on MLIR further (and also targeting accelerators). However, ongoing/active work is not ready for production. To be fair, PlaidML v1 branch was also not marked as ready for production.

Since we still continue to use PlaidMLv1 as a baseline, there is still a chance for a fix. I will take a look at your issue, but cannot promise anything.

**Comment by hfp** [comment]
There is no GPU support in PlaidML v1, which is the reason for not listing any related device. The development on "v1" branch was not like "a new version" on top of v0.7 but rather research were to go next, and incorporating compiler technology like LLVM's MLIR. The latter is exactly what we do now but not based on PlaidML v1 branch. In any case, GPU codegen is not ready.
