### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [plaidml/plaidml#1996]
Hi!

Recently I checked Profile-Guided Optimization (PGO) improvements on multiple projects. The results are [here](https://github.com/zamazan4ik/awesome-pgo/). LLVM-related results are [here](https://github.com/llvm/llvm-project/issues/63486) could be also interesting to you since LLVM is a dependency for PlaidML.

Since PGO showed measurable improvements in compiler-like loads (CPython, Clang, Clangd, clang-format, GCC, Rustc, etc.) I think it could be useful to check PGO on PlaidML as well.

We need to perform PGO benchmarks on PlaidML. And if it shows improvements - add a note about possible improvements in PlaidML performance with PGO. Providing an easier way (e.g. a build option) to build scripts with PGO can be useful for the end-users too. Maybe testing Post-Link Optimization techniques (like LLVM BOLT from Facebook) would be interesting too but I recommend starting from the usual PGO.

Not sure where would be better to start in the case of PlaidML. Probably (but I could be wrong) compiler and JIT implementation are the good starting candidates.

**Comment by hfp** [comment]
PlaidML is a compiler infrastructure using LLVM as a framework. Our research moved on to LLVM/MLIR orphaning PlaidML or not coming up with new releases (no matter which branch we talk about).

In any case, PGO is well-known and I would like to understand if your suggestion is just based on "LLVM is a dependency". PlaidML is unlikely to benefit from PGO (as it uses runtime code generation aka JIT compilation).

We have bad experience with automatically derived conclusions (correct me if this is not the case here), and we prefer not to be involved into unspecific learnings or "make-work" projects.

**Comment by zamazan4ik** [comment]
> In any case, PGO is well-known and I would like to understand if your suggestion is just based on "LLVM is a dependency".

My suggestion is based on multiple factors:
* According to [multiple benchmarks](https://github.com/ZaMaZaN4iK/awesome-pgo#compilers-and-interpreters) PGO helps a lot with optimizing compilers and interpreters' performance itself (not the performance of the generated by compilers/interpreters code).
* According to my [benchmark](https://github.com/tensorflow/tensorflow/issues/60944#issuecomment-1637143591) on applying PGO to `tfcompile` project - PGO helps with optimizing the performance of the deep-learning compiler as well.

> PlaidML is unlikely to benefit from PGO (as it uses runtime code generation aka JIT compilation).

You are probably mixing two different things: "performance of the generated code" and "performance of the compiler itself". With the former PGO does not help (at least in the proposed by me way). I am suggesting optimizing the performance of the PlaidML compiler/interpreter itself. [Here](https://github.com/ZaMaZaN4iK/awesome-pgo#compilers-and-interpreters) you can check how PGO helps with optimizing JIT-like compilers performance (CPython, PHP, Perl, Ruby).

**Comment by hfp** [comment]
> You are probably mixing two different things: "performance of the generated code" and "performance of the compiler itself".

Make sense. We do not care about "performance of the compiler itself" and use something else if this is a constraint (not using LLVM or taking care in the first place). For "tfcompile", I can only see improved prototyping turnaround time; otherwise only two cases: (1) deep learning amortizes JIT-overhead, (2) inference should always work on optimized/frozen/precompiled/etc topologies and never run into JIT overhead.
