### ISSUE TITLE
Support Keras 2.2.4

### ISSUE THREAD

**Issue by corymayer** [plaidml/plaidml#201]
Are there plans to release a version with a Keras 2.2.4 (or greater) dependency requirement? [This bug](https://github.com/keras-team/keras/issues/11617) in Keras < 2.2.4 is quite frustrating for anyone needing to save and load models.

**Comment by miskolc** [comment]
Keras 2.2.4 comes with the `restore_best_weights` for the EarlyStopping callback which is a very useful feature to have therefore I also believe PlaidML and with it will make training high accuracy models much faster.

**Comment by brianretford** [comment]
0.5.0 supports 2.2.4
