### ISSUE TITLE
PlaidML doesn't work on Boot Camp on iMac 2017

### ISSUE THREAD

**Issue by abc1236762** [plaidml/plaidml#217]
I use Windows 10 installed with Boot Camp on my iMac 2017 with Radeon Pro 580.
I used unofficial driver 18.8.2 downloaded at [BootCampDrivers.com](https://www.bootcampdrivers.com/) and PlaidML worked fine.
Today I found official driver reversion number 18.10 [here](https://www.amd.com/en/support/kb/release-notes/apple-boot-camp) and I used DDU to remove the unofficial driver and install this official one.
But after I installed and also reinstalled AMD APP SDK Installer, PlaidML is not working.

The output of clinfo: [clinfo.txt](https://github.com/plaidml/plaidml/files/2708631/clinfo.txt)
GPU-Z also can see that OpenCL is checked: 
![default](https://user-images.githubusercontent.com/11353779/50420651-ebfc8680-0872-11e9-8468-6324b2ede01e.png)

**Comment by brianretford** [comment]
Have you rerun plaidml-setup? It’s possible the device name changed with the driver update.

On Dec 25, 2018, at 1:33 PM, Yù-Jǐn Lín <notifications@github.com<mailto:notifications@github.com>> wrote:


I use Windows 10 installed with Boot Camp on my iMac 2017 with Radeon Pro 580.
I used unofficial driver reversion number 18.8.2 downloaded at BootCampDrivers.com<https://www.bootcampdrivers.com/> and PlaidML worked fine.
Today I found official driver updated to reversion number 18.10 here<https://www.amd.com/en/support/kb/release-notes/apple-boot-camp> and I used DDU to remove the old driver and install this new one.
But after I installed and also reinstalled AMD APP SDK Installer, PlaidML is not working.

The output of clinfo: clinfo.txt<https://github.com/plaidml/plaidml/files/2708631/clinfo.txt>
GPU-Z also can see that OpenCL is checked:
[default]<https://user-images.githubusercontent.com/11353779/50420651-ebfc8680-0872-11e9-8468-6324b2ede01e.png>

―

**Comment by abc1236762** [comment]
Yes I did.
![2018-12-28 114542](https://user-images.githubusercontent.com/11353779/50501881-7244e280-0a96-11e9-8334-b1de8b9acb8a.png)

**Comment by brianretford** [comment]
Apologies for the delay. This issue should be resolved.
