### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000030

### ISSUE THREAD

**Issue by Payback80** [plaidml/plaidml#225]
Hello, to dive deeper into keras i'm reading the book from it's creator 
But with perfect legitimate code Plaidml fails at model.fit 
returning error: 
OSError: exception: access violation reading 0x0000000000000030 
with the tensorflow backend it works flawless 
the notebook code is here: 
https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/3.5-classifying-movie-reviews.ipynb

I'd like to know a workaround, also because i've tried more complex layers like LSTM and they work
What's missing?

**Comment by pkuzhl** [comment]
Hi, I have the similar issue. Did you figure out how to solve it ? I'm using AMD FirePro W2100.
OSError: exception: access violation reading 0x0000000000000018

**Comment by brianretford** [comment]
@pkuzhl are you experiencing the error with the same code? @Payback80 and @pkuzhl what platforms are you on and which GPUs are you using.

**Comment by pkuzhl** [comment]
@brianretford   I was using a different code, but I solved this problem by using a smaller batch size, it seems in my previous code, a larger batch size exceeded the memory of my GPU.

**Comment by brianretford** [comment]
Great we'll add this to our troubleshooting guide and close when the guide is available

**Comment by dgkutnic** [comment]
This has been added to our troubleshooting guide: https://github.com/plaidml/plaidml/blob/master/docs/troubleshooting.md#memory-errors
