### ISSUE TITLE
Drivers for Radeon HD 7950 Tahiti Ubuntu 18.04

### ISSUE THREAD

**Issue by JacoGasp** [plaidml/plaidml#226]
Hello there,

sorry if my question is not particularly relevant for this repo, but I didn't find any solution anywhere else so far.

I own a Radeon HD7950 which is still a powerful GPU. 
On Windows, with standard official AMD's drivers (a no additional installations), PlaidML works like a charm, with perfect results.

On the other hand, on Ubuntu, using `amdgpu-pro` drivers, it _appears_ to work (the GPU is fully loaded during training) but results are garbage.

I read that `amdgpu-pro` are not very stable and one should rely on the better ROCm drivers. But the official notes sentence that my GPU is __NOT__ going to work.

Do anyone has a solution to make old (but still powerful) GCN 1.0 GPUs to work?

EDIT: In addition `plaidbench keras mobilenet` passes on Windows while fails on Ubuntu

**Comment by znmeb** [comment]
@JacoGasp Are you getting the drivers from the AMD website or from Ubuntu's software application? I have an "old" AMD GPU (GCN 1.1, IIRC - it's a Bonaire "Sea Islands" card). I have it running with PlaidML in Arch Linux and the driver is 18.50.708488-1 but it's ***just*** the OpenCL libraries, *not* the whole AMDGPU-Pro package! And it requires these kernel parameters:

```
modprobe.blacklist=radeon radeon.cik_support=0 amdgpu.cik_support=1 amdgpu.dc=0
```
If your card is a "Southern Islands" card change `cik` to `sik`.

**Comment by JacoGasp** [comment]
Hey @znmeb, thank you very much for your reply.
I'm using the driver provided by AMD, v. 18.40. Now I'm going to try v. 18.50 from [here](https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-18-50-unified).

Following your advice, I'm going to try the installation flag `opencl=legacy` to have the OpenCL stack only.

Sorry for my ignorance, but in Ubuntu, do I have to set those kernel flags into grub configuration?

**Comment by V-Kh** [comment]
@JacoGasp 
Please, do not install drivers manually, this is a way to break everything. 
First, Ubuntu should have something like driver/hardware manager. Try to find/install it and after that check all the drivers that are available.  
Unfortunately, current ppa:graphics-drivers offers various versions of drivers only for nvidia cards. So, you can only try one version of free/proprietary amd driver.

**Comment by brianretford** [comment]
Thanks for looking into this - we may need to instrument the device selection stuff

Sent from my iPhone

On Feb 4, 2019, at 6:20 AM, V-Kh <notifications@github.com<mailto:notifications@github.com>> wrote:


@JacoGasp<https://github.com/JacoGasp>
Please, do not install drivers manually, this is a way to break everything.
First, Ubuntu should have something like driver/hardware manager. Try to find/install it and after that check all the drivers that are available.
Unfortunately, current ppa:graphics-drivers offers various versions of drivers only for nvidia cards. So, you can only try one version of free/proprietary amd driver.

**Comment by JacoGasp** [comment]
Sorry @V-Kh but I did not get your answer.. You said to not install drivers manually but the driver manager works only with Nvidia, so to go with manual installation.

Anyway, I think that the problem is on the OpenCl side. I tried with mesa-opencl-icd but plaid-setup is not able to perform the matrix multiplication test

**Comment by V-Kh** [comment]
@JacoGasp 
> Sorry @V-Kh but I did not get your answer.. You said to not install drivers manually but the driver manager works only with Nvidia, so to go with manual installation.
Well, I've checked their page, it seems that you're correct, unfortunately. Nevertheless, downloading video drivers from a manufacturer's site and installing them is (and was) always a bad idea. That is what I meant by manual installation. If driver manager can't help you, you can always use apt.

**Comment by JacoGasp** [comment]
> @JacoGasp
> 
> > Sorry @V-Kh but I did not get your answer.. You said to not install drivers manually but the driver manager works only with Nvidia, so to go with manual installation.
> > Well, I've checked their page, it seems that you're correct, unfortunately. Nevertheless, downloading video drivers from a manufacturer's site and installing them is (and was) always a bad idea. That is what I meant by manual installation. If driver manager can't help you, you can always use apt.

Yes, but as far as I understand, Ubuntu already comes with full supported AMD drivers. But the problem is that they don't provide support for OpenCL. Property AMD's drivers do, and as I wrote in my first post, the appear to work. Simply they give (numerical?) bad results with plaidml

**Comment by V-Kh** [comment]
@JacoGasp 
It's been some time since I use an AMD card but I've never seen anything like this before. 
Indeed, you _have_ to download the driver from their web-page. Odd.

OK, I have two possible options. First, have you tried any other card or CPU just to check if it works? Second, have you tried any other distro?

**Comment by brianretford** [comment]
Closing as it's related to AMD driver support, which we'd love to help with but can't really :-)
