### ISSUE TITLE
Plaidml not detecting Mali-T628 on ARM

### ISSUE THREAD

**Issue by nitescuc** [plaidml/plaidml#227]
Hi,

I've build plaidml 0.3.5 to use on Odroid XU4 with Mali-T628 GPU with debian stretch. I manage to install the wheel, when I run plaidml-setup, I get:

"No supported devices found. Run 'clinfo' and file an issue containing the full output."

However, with plaidml 0.3.0rc1 latest available with pip install plaidml, my devices can be configured and I have 2 mali-t628 reported. "experimental.json" appears quite similar in both cases.

Any clue with what I may have done wrong building plaidml ? (used basel 0.18.1 with --config linux_arm_32v7) or what change might explain 0.3.5 not recognizing my devices where 0.3.0rc1 did ?

Thanks

Here's my clinfo report:

Number of platforms                               1
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 1.2 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_gl_sharing cl_khr_icd cl_khr_egl_event cl_khr_egl_image cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory
  Platform Extensions function suffix             ARM

  Platform Name                                   ARM Platform
Number of devices                                 2
  Device Name                                     Mali-T628
  Device Vendor                                   ARM
  Device Vendor ID                                0x6200010
  Device Version                                  OpenCL 1.2 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82
  Driver Version                                  1.2
  Device OpenCL C Version                         OpenCL C 1.2 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               4
  Max clock frequency                             600MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              4
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              2090405888 (1.947GiB)
  Error Correction support                        No
  Max memory allocation                           522601472 (498.4MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        <printDeviceInfo:89: get CL_DEVICE_GLOBAL_MEM_CACHE_SIZE : error -30>
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             65536x65536 pixels
    Max 3D image size                             65536x65536x65536 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_gl_sharing cl_khr_icd cl_khr_egl_event cl_khr_egl_image cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory

  Device Name                                     Mali-T628
  Device Vendor                                   ARM
  Device Vendor ID                                0x6200010
  Device Version                                  OpenCL 1.2 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82
  Driver Version                                  1.2
  Device OpenCL C Version                         OpenCL C 1.2 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               2
  Max clock frequency                             600MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              4
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              2090405888 (1.947GiB)
  Error Correction support                        No
  Max memory allocation                           522601472 (498.4MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        <printDeviceInfo:89: get CL_DEVICE_GLOBAL_MEM_CACHE_SIZE : error -30>
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             65536x65536 pixels
    Max 3D image size                             65536x65536x65536 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_gl_sharing cl_khr_icd cl_khr_egl_event cl_khr_egl_image cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  ARM Platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [ARM]
  clCreateContext(NULL, ...) [default]            Success [ARM]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (2)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-T628
    Device Name                                   Mali-T628
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (2)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-T628
    Device Name                                   Mali-T628

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

**Comment by tzerrell** [comment]
Odd. You can try upgrading to 0.5.0; I don't think any of those changes should affect this but it's not impossible. You can also try adjusting the last ARM config in `experimental.json` from `ARM` and `Mali-T628` to `.*ARM.*` and `.*Mali-T628.*` -- looking at your clinfo it doesn't seem like that should be necessary but I'm feeling a bit paranoid about it anyway. Let us know if either of these help.

**Comment by nitescuc** [comment]
Thanks for your answer. I take 0.5.0 is master branch. Can you suggest a bazel version to use, I have quite hard time building this branch.

**Comment by earhart** [comment]
It doesn't look like the 0.5.0 code's been released yet.
Once it's there, there'll be an Anaconda `environment.yml` file that should provide a working build environment.

**Comment by nitescuc** [comment]
Hi all,

Adjusting experimental.json with the regex actually did the job in 0.3.5 so I've been able to run my algorithm on Mali. It's not faster than CPU though but, hey, it worth trying. Thanks for support, I'll let you decide about including the adjusted regex in experimental.json.

Regards

**Comment by brianretford** [comment]
Which network are you running? We admittedly haven’t spent much time tweaking the mali config, primarily because it really requires microkernels to get full throughput. Is the t628 the one that shows up as two devices, one with 4 cores and one with 2? There are also a bunch of tricks around using texture memory.

Stripe will allow use to really get the best perf out of them. Have you tried fp16?

Sent from my iPhone

On Feb 2, 2019, at 8:56 AM, Cristian Nitescu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all,

Adjusting experimental.json with the regex actually did the job in 0.3.5 so I've been able to run my algorithm on Mali. It's not faster than CPU though but, hey, it worth trying. Thanks for support, I'll let you decide about including the adjusted regex in experimental.json.

Regards

**Comment by nitescuc** [comment]
I'm using an "NVidia" network for self driving cars as part of DIY Robocars challenge. Here's what my network look like:
```python
def NVidia():
    img_in = Input(shape=(120, 160, 1), name='img_in')                      # First layer, input layer, Shape comes from camera.py resolution, RGB
    x = img_in
    x = Convolution2D(24, (5,5), strides=(2,2), activation='relu')(x)       # 24 features, 5 pixel x 5 pixel kernel (convolution, feauture) window, 2wx2h stride, relu activation
    x = Convolution2D(32, (5,5), strides=(2,2), activation='relu')(x)       # 32 features, 5px5p kernel window, 2wx2h stride, relu activatiion
    x = Convolution2D(64, (5,5), strides=(2,2), activation='relu')(x)       # 64 features, 5px5p kernal window, 2wx2h stride, relu
    x = Convolution2D(64, (3,3), strides=(2,2), activation='relu')(x)       # 64 features, 3px3p kernal window, 2wx2h stride, relu
    x = Convolution2D(64, (3,3), strides=(1,1), activation='relu')(x)       # 64 features, 3px3p kernal window, 1wx1h stride, relu

    x = Flatten(name='flattened')(x)                                        # Flatten to 1D (Fully connected)
    x = Dense(100, activation='relu')(x)                                    # Classify the data into 100 features, make all negatives 0
    x = Dropout(.1)(x)
    x = Dense(50, activation='relu')(x)
    x = Dropout(.1)(x)                                                      # Randomly drop out 10% of the neurons (Prevent overfitting)
    angle_out = Dense(15, activation='softmax', name='angle_out')(x)        # Connect every input with every output and output 15 hidden units. Use Softmax to give percentage. 15 categories and find best one based off percentage 0.0-1.0
    throttle_out = Dense(7, activation='softmax', name='throttle_out')(x)        # Connect every input with every output and output 15 hidden units. Use Softmax to give percentage. 15 categories and find best one based off percentage 0.0-1.0

    return Model(inputs=[img_in], outputs=[angle_out, throttle_out])
```
I'm happy to assist and try any suggestions. Right now my code run in a docker container from the base image arm/python:3.5-stretch, with installation of relevant drivers and then plaidml*.whl (0.3.5) which I've cross-compiled on x86 using python:3.5-stretch image and bazel 0.18.1

**Comment by nitescuc** [comment]
Latest test doesn't show any difference using FP16 or FP32, unless my method of setting it wasn't correct: I use keras.backend.set_floatx('float16') to switch to FP16. The weights of the model were though computed in FP32 mode, I don't actually know if there's any relevance. It might worth trying with weights computed with FP16 instead ? 
For information, a prediction takes approx. 35ms using plaidml on Mali and approx. 23ms on CPU.

**Comment by brianretford** [comment]
So there are a few really stupid things we haven’t fixed in plaid yet (primarily because we’re fixing them in Stripe). One of these is that vec_size in the hardware config is in number of elements. Try setting it to 16 https://github.com/plaidml/plaidml/blob/master/plaidml/configs/experimental.json

**Comment by nitescuc** [comment]
Well, bad news, vec_size to 16 result in prediction time of 220ms instead of 35ms.
Would you think channnels_last (current model) vs channels_first can have significant impact ?

**Comment by brianretford** [comment]
It might - the vectorizer in plaidml isn't as smart as it could be and if things aren't multiples of 8, 4, or 2 in the stride 1 dimension it won't vectorize. 

Which device are you using, from plaidml-setup? Are you sure you're using the one with 4 cores? It's been a while since I played with a device with a T628, but we generally saw a reasonable speedup.

**Comment by nitescuc** [comment]
You're right, I was using the wrong gpu (just took the first one, I've been imagining they're identical). Now I'm on 23ms on GPU. The best vec_size value still seems to be 8. I'm still on 0.3.5, I'll try to build 0.5.0 to see if there's any improvment ...

**Comment by brianretford** [comment]
Hrmmm, we updated our toolchain recently and we don't currently have continuous builds enabled for arm. Frank, any thoughts?

I doubt you'll get better performance in 0.5.0. I think this is an ideal target for multi-gpu support post stripe. The other thing to look at is clock speed - I found different boards seemed to have different settings for clock speeds -- variable clock speeds can really impact NN perf

**Comment by flaub** [comment]
Unfortunately, we upgraded the toolchain on `linux_x86_64` to be based on g++ 6.3.0, which provides support for c++14. However, we haven't yet updated the `linux_arm_32v7` compiler.

If you'd like to try to create a new toolchain for `linux_arm_32v7`, you can follow these instructions:
https://github.com/plaidml/toolchain/blob/master/README.md

You can configure crosstool-ng to create a toolchain that targets arm_32v7, and also have it use a newer compiler. You'll want to try and use the oldest libc that's supported so that it works on older OSes. PRs are welcome on the https://github.com/plaidml/toolchain repo.

**Comment by nitescuc** [comment]
Thanks guys, this seems a bit over my actual skills, I might get into it some time but I hardly can do it right now.

Thanks for the help anyway it was quite useful. I guess I'll close this issue now.
