### ISSUE TITLE
No OpenCL devices found. Check driver installation.

### ISSUE THREAD

**Issue by leon3428** [plaidml/plaidml#229]
I am trying to install plaidml on windows 10 but plaidml-setup just says "No OpenCL devices found". I have also tried installing plaidml on ubuntu and arch but nvidia drivers prevented both distros form booting. 

Tnx for help!

Laptop specs:
intel ccore i5 8300h
nvidia gtx 1050(mobile) - drivers 417.71

**Comment by tzerrell** [comment]
Can you post the information clinfo gives you?

Also, it's possible this is fixed in 0.5.0
