### ISSUE TITLE
LogicError when using BatchNormalization

### ISSUE THREAD

**Issue by marc1701** [plaidml/plaidml#236]
I'm getting the following error:

`LogicError: Broadcast mismatch: 64 and 60 are incompatible; inputs were: (SymbolicDim UINT64(), 64, 1400, 60), (64)`

when trying to build a keras model using a script originally written using a tensorflow backend with plaidml, but only when using batch normalisation. Commenting out the following line: 

`x = BatchNormalization(axis=1)(x)` 

stops the error but the network then trains very poorly.

Very new at this... any ideas?

**Comment by SaeedMontazeri** [comment]
Dear Marc, did you find any solution? Would you please share it with me if you have found a solution, I have the same problem.
Thanks

**Comment by marc1701** [comment]
Sorry Saeed, I don't think I ever got to the bottom of this. I've switch to Pytorch for my work these days.
