### ISSUE TITLE
OpenCL HAL example link is dead.

### ISSUE THREAD

**Issue by trivialfis** [plaidml/plaidml#237]
In contributing guide:

>     HALs for Backend Targets (OpenCL, Vulkan, SPIR-V, HVX, etc)
>     There is no documentation for the HAL currently. The interface is fairly straightforward and the OpenCL HAL provides a good example of a complete HAL.

the link embedded in `OpenCL HAL`: https://github.com/plaidml/plaidml/blob/master/docs/tile/hal/opencl is dead.

**Comment by tzerrell** [comment]
Thanks, we'll get this updated for the next release. The link is intended to point to https://github.com/plaidml/plaidml/tree/master/tile/hal/opencl
