### ISSUE TITLE
AMD R9 390

### ISSUE THREAD

**Issue by logip** [plaidml/plaidml#239]
Hi, 

I'm trying to use AMD 390 on Ubuntu 18.04. I've set up ROCm 1.9 (version 2.1 does not support the card) and I've set up plaidml (0.5). I've also got plaidbench which for some reason only sometimes works and sometimes not. 
Why are AMD cards marked as experimental in plaidml? How can I see what goes wrong, is there a log the could tell me something? 

This is what I get now testing Plaidbench:

**Selected device:
    opencl_amd_gfx701.0

Almost done. Multiplying some matrices...
Tile code:
  function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
Whew. That worked.

Save settings to /home/logip/.plaidml? (y,n)[y]:
Success!

(plaidml3.6) logip@logip-ubuntu:~$ plaidbench keras mobilenet
Running 1024 examples with mobilenet, batch size 1, on backend plaid
INFO:plaidml:Opening device "opencl_amd_gfx701.0"
Model loaded.
Compiling network... Warming up...**

And then nothing. But sometimes it works and the computation is really fast (15 times faster than on the CPU (Intel® Core™ i7-4790K). What might be causing this?

Any help appreciated.

**Comment by brianretford** [comment]
This is quite odd. Do you have anything else running on your machine? Sorry for the delayed reponse

**Comment by logip** [comment]
Hi again, 
Most of the examples work fine:
densenet121
densenet169
densenet201
inception_resnet_v2
etc

But for some reason some just do not. Maybe this has to do with the batch size?
For example this works: plaidbench --batch-size 16 keras --train mobilenet
But this does not: plaidbench --batch-size 32 keras --train mobilenet

If I switched over to the CPU more of them work but not all. I'm now using version 0.6

With regards, Logi

**Comment by brianretford** [comment]
Increasing the batch size past a certain limit will in fact run out of memory. This is pervasive across deep learning libraries, e.g., cuDNN
