### ISSUE TITLE
[RNN] Doesn't work with the following examples from the Keras repository

### ISSUE THREAD

**Issue by LukeB42** [plaidml/plaidml#24]
`lstm_text_generation.py`
`babi_memnn.py`

This is the error I get for the LSTM language model:
```
plaidml.keras.backend.PlaidMLKerasException: Applying function, tensor with mismatching dimensionality: X, expected=2, got=3
Traceback:
_Op(dot)
outputs: R
inputs:
  X: _Op(rnn_lo)
  outputs: B
  inputs:
    A: _Op(concatenate)
    outputs: O
    inputs:
      I1: _Op(reshape)
      outputs: O
      inputs:
        I: _Op(+)
        outputs: A
        inputs:
          ...truncated...
      I0: _Op(reshape)
      outputs: O
      inputs:
        I: _Op(+)
        outputs: A
        inputs:
          ...truncated...
      I3: _Op(reshape)
      outputs: O
      inputs:
        I: _Op(+)
        outputs: A
        inputs:
          ...truncated...
      I2: _Op(reshape)
      outputs: O
      inputs:
        I: _Op(+)
        outputs: A
        inputs:
          ...truncated...
  Y: dense_1/kernel[128, 59]
  dense_1/kernel[128, 59]
```

The output is similar for the memory network example.

Overall thanks for the effort though.

**Comment by jbruestle** [comment]
In the 'current limitations' in our README, we mention that RNNs (which include LSTMs) are not supported yet.  This is the cause of the error, although clearly the error message isn't particularly helpful.  We are hoping to have full support for all Keras operations soon, but I don't have a specific time frame right now.

**Comment by LukeB42** [comment]
@jbruestle Thanks for pointing this out.

**Comment by brianretford** [comment]
We'll leave this open to track completion

**Comment by cathalgarvey** [comment]
Hey folks, any timeline in mind for RNN support? Also, from the above, I think the way commit comments are being made is leading to reference-spam on this issue. :)

**Comment by choongng** [comment]
Hi Cathal, we're making progress but no date yet. Would you be interested in helping us test our internal builds on your application?

**Comment by cathalgarvey** [comment]
Having no application to test, sadly no! I'm interested in learning tile but haven't been able to commit time for it, yet. Really looking forward to working with Plaid some more though, particularly for text projects, so LSTMs and GRUs are especially exciting to me. :)

Thanks!

On 1 February 2018 18:48:19 GMT+00:00, Choong Ng <notifications@github.com> wrote:
>Hi Cathal, we're making progress but no date yet. Would you be
>interested in helping us test our internal builds on your application?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/plaidml/plaidml/issues/24#issuecomment-362363866

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by harish2704** [comment]
Hi, Do we have a public chat room for PlaidML project ?
If not , will it be possible to create a Gitter/Matrix/IRC chat room for PlaidML development discussions.

I was anxiously waiting for RNN to get completed .
If there is a public chat room and core developers of PlaidML can provide some guidance through that, may be we can speed up the development of PlaidML.

-Sorry for putting off-topic in this thread.

**Comment by brianretford** [comment]
You can try out `pip install plaidml-keras==0.3.0rc1 plaidml==0.3.0rc1`. The official release is coming soon. Supports uni-directional LSTMs and many GANs

**Comment by josemjmmg** [comment]
I tried plaidml-keras==0.3.0rc1 plaidml==0.3.0rc1
with the mnist_irnn.py example at
https://github.com/keras-team/keras/blob/master/examples/mnist_irnn.py
including 
import plaidml.keras
plaidml.keras.install_backend()
before  import keras

on macbook pro mid 2012  with Intel HD Graphics 4000 1536 MB 
osx 10.11.4
plaidml-setup gpu inten hd graphics

and failed:
x_train shape: (60000, 784, 1)
60000 train samples
10000 test samples
Evaluate IRNN...
INFO:plaidml:Opening device "hd_graphics_4000.0"
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
INFO:plaidml:Analyzing Ops: 727 of 8744 operations complete
INFO:plaidml:Analyzing Ops: 3268 of 8744 operations complete
INFO:plaidml:Analyzing Ops: 5324 of 8744 operations complete
INFO:plaidml:Analyzing Ops: 6794 of 8744 operations complete
INFO:plaidml:Analyzing Ops: 8309 of 8744 operations complete
WARNING:plaidml:Failed to build program
WARNING:plaidml:Failed build log: Compile Server Error.
WARNING:plaidml:Code was:
    1: // Names: { i1, i2 }
    2: // Ranges: { 1, 100 }
    3: // Out stride: { 100, 1 }
    4: // Elementwise input X_I_0 shape: float32()
    5: // Elementwise input X_I_1 shape: float32(1:100, 100:1)
    6: // Elementwise op: X_T0 = mul(X_I_0, X_I_1)
    7: // Tile size: { 1, 100 }
.......
......
WARNING:plaidml:Failed to build program: CL_BUILD_PROGRAM_FAILURE
Traceback (most recent call last):
  File "mnist_irnn.py", line 75, in <module>
    validation_data=(x_test, y_test))
  File "~/projects/Deep_Learning/pyEnvs/plaidMLrnn/lib/python2.7/site-packages/keras/models.py", line 867, in fit
    initial_epoch=initial_epoch)
.......
.........
plaidml.exceptions.Unknown: Unable to compile Tile program

**Comment by josemjmmg** [comment]
in the same evironment plaidvision.py works fine.

I would like to congratule you on plaidML and plaidVision. Amazing work

**Comment by harish2704** [comment]
@brianretford 
Thanks for the update.

I tried to compile the specified branch for my in my "Opensuse Tumbleweed" OS. 
Unfortunatly, build was failing. 

I tried to find the failing point by running the following command 
* `bazel build plaidml:wheel plaidml/keras:wheel --verbose_failures`

I found that,  following command was the cause of failure.
```bash
cd /home/hari/.cache/bazel/_bazel_hari/3b993baf5bf2ba2258e997244a85fb23/execroot/vertexai_plaidml && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tile/hal/opencl/_objs/opencl/tile/hal/opencl/driver.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tile/hal/opencl/_objs/opencl/tile/hal/opencl/driver.pic.o' -fPIC -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_BUILD_LIB '-DBOOST_THREAD_VERSION=4' -DBOOST_THREAD_PROVIDES_EXECUTORS -DBOOST_ALL_NO_LIB -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/genfiles/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/boost_archive -iquote bazel-out/k8-opt/genfiles/external/boost_archive -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-opt/genfiles/external/com_github_gflags_gflags -iquote external/easylogging_repo -iquote bazel-out/k8-opt/genfiles/external/easylogging_repo -iquote external/jsoncpp_git -iquote bazel-out/k8-opt/genfiles/external/jsoncpp_git -iquote external/minizip_repo -iquote bazel-out/k8-opt/genfiles/external/minizip_repo -iquote external/gmock_archive -iquote bazel-out/k8-opt/genfiles/external/gmock_archive -iquote external/opencl_icd_loader_repo -iquote bazel-out/k8-opt/genfiles/external/opencl_icd_loader_repo -iquote external/opencl_headers_repo -iquote bazel-out/k8-opt/genfiles/external/opencl_headers_repo -iquote external/opengl_repo -iquote bazel-out/k8-opt/genfiles/external/opengl_repo -Ibazel-out/k8-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/genfiles/external/com_google_protobuf/src -isystem external/zlib_archive/zlib-1.2.8 -isystem bazel-out/k8-opt/genfiles/external/zlib_archive/zlib-1.2.8 -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/boost_archive -isystem bazel-out/k8-opt/genfiles/external/boost_archive -isystem external/easylogging_repo/src -isystem bazel-out/k8-opt/genfiles/external/easylogging_repo/src -isystem external/jsoncpp_git/include -isystem bazel-out/k8-opt/genfiles/external/jsoncpp_git/include -isystem external/minizip_repo -isystem bazel-out/k8-opt/genfiles/external/minizip_repo -isystem external/gmock_archive/googlemock -isystem bazel-out/k8-opt/genfiles/external/gmock_archive/googlemock -isystem external/gmock_archive/googlemock/include -isystem bazel-out/k8-opt/genfiles/external/gmock_archive/googlemock/include -isystem external/gmock_archive/googletest -isystem bazel-out/k8-opt/genfiles/external/gmock_archive/googletest -isystem external/gmock_archive/googletest/include -isystem bazel-out/k8-opt/genfiles/external/gmock_archive/googletest/include -isystem external/opencl_headers_repo/opencl22 -isystem bazel-out/k8-opt/genfiles/external/opencl_headers_repo/opencl22 -isystem external/opengl_repo/inc -isystem bazel-out/k8-opt/genfiles/external/opengl_repo/inc '-std=c++14' -Werror -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tile/hal/opencl/driver.cc -o bazel-out/k8-opt/bin/tile/hal/opencl/_objs/opencl/tile/hal/opencl/driver.pic.o
```
the mail error was this 
```
./tile/hal/opencl/info.h:128:83: error: ignoring attributes on template argument 'cl_uint {aka unsigned int}' [-Werror=ignored-attributes]
 struct CLInfoType<CL_DEVICE_VENDOR_ID> : CLDeviceInfo<CL_DEVICE_VENDOR_ID, cl_uint> {};
```

I have attached complete error log.
It will be helpful if you can provide some solution to resolve this

I appreciate team behind PlaidML project for this great project.
-Thanks

[error.log](https://github.com/plaidml/plaidml/files/1850802/error.log)

**Comment by brianretford** [comment]
We have updated our build process in the latest code push and need to update BUILDING.md, can you try `bazel build --config linux_x86_64 plaidml:wheel plaidml/keras:wheel --verbose_failures`

**Comment by tzerrell** [comment]
RNNs are working in general; if you have a specific RNN that is not working, please open a ticket for it.
