### ISSUE TITLE
Pyinstaller

### ISSUE THREAD

**Issue by MichaelFomenko** [plaidml/plaidml#240]
can someone delete this Post, I allredy have this problem solved in the Pyinstaller Github page.

**Comment by MichaelFomenko** [comment]
here is the Solution i found for my Problem: 
**pyinstaller App.py  --add-data 'compile-env\Include;Include' --add-data 'compile-env\library;library'  --add-data 'compile-env\share;share' --clean**

**Comment by mijosch** [comment]
same problem here
trying to use pyinstaller leads to the enum34 problem
is enum34 needed in python 3.6.7 to run plaidml?
