### ISSUE TITLE
plaidML works very slow on frequently calls with various input shapes

### ISSUE THREAD

**Issue by iperov** [plaidml/plaidml#242]
it seems like plaidML does not cache GPU kernels???

plaidML:
![123](https://user-images.githubusercontent.com/8076202/52917107-ebc3b900-3300-11e9-8003-d922c818c3b1.gif)

tensorflow-CPU:
![1234](https://user-images.githubusercontent.com/8076202/52917131-3e9d7080-3301-11e9-89e6-dfb410731765.gif)

**Comment by brianretford** [comment]
From run to run it currently does not, it does inside the same execution. We’ve talked about adding caching of compilations (it’s straightforward). Certainly we’ll add this to the 1.0 backlog

Sent from my iPhone

On Feb 17, 2019, at 1:13 PM, iperov <notifications@github.com<mailto:notifications@github.com>> wrote:


it seems like plaidML does not cache GPU kernels???

plaidML:
[123]<https://user-images.githubusercontent.com/8076202/52917107-ebc3b900-3300-11e9-8003-d922c818c3b1.gif>

tensorflow-CPU:
[1234]<https://user-images.githubusercontent.com/8076202/52917131-3e9d7080-3301-11e9-89e6-dfb410731765.gif>

**Comment by mijosch** [comment]
That is a realy important feature!
In my apllication reloading the kernel ist the most time consuming part!
Im analysing pictures that are added continously and at the moment the kernel is loaded for each picture witch makes it realy slow

**Comment by brianretford** [comment]
Hmmm, can you share some of your code?

**Comment by mijosch** [comment]
I use model.predict for a set of tiles, then I tile the next picture and call model.predict again. It shows analyse each time and if I watch gpu-z I can see that the GPU is computing just a short amount of time and also the memory controller. Seems like each time I call predict the network is loaded

**Comment by brianretford** [comment]
Hmmm, that should definitely not be the case - plaidbench calls predict repeatedly and does not incur that overhead. If you're not streaming the inputs in (i.e., if you aren't preprocessing inputs while you are running the network) you would expect to see spikes in GPU load while it stalls waiting for more input. If you can share your exact code we can help diagnose

**Comment by iperov** [comment]
I think user should manually operate how many various kernels should be cached . Looks like plaidML has limit of 10 or so ...
For small model used in MTCNN (face recognition) I need to cache 200 kernels.

**Comment by mijosch** [comment]
Ah, if I use opencv to process my input data it clears the kernels used by plaidml?
Is there an option to avoid this?

**Comment by brianretford** [comment]
@iperov - we cache everything pretty aggressively and I don't think we have a limit - otherwise plaidbench would also fail. If you all can share links to code we're happy to take a look

@mijosch - no, the cache shouldn't ever be cleared, that's why I want to look at your code :-)

**Comment by mijosch** [comment]
Ok, as soon as I can reach my code

**Comment by iperov** [comment]
@brianretford ok I will try to create minimal reproduce code.

**Comment by iperov** [comment]
@brianretford done
minimal reproducing code

```

import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
os.environ["PLAIDML_DEVICE_IDS"] = "opencl_nvidia_geforce_gtx_1060_6gb.0"
import keras
import numpy as np
import cv2
import time
K = keras.backend



PNet_Input = keras.layers.Input ( (None, None,3) )
x = PNet_Input
x = keras.layers.Conv2D (10, kernel_size=(3,3), strides=(1,1), padding='valid', name="conv1")(x)
x = keras.layers.PReLU (shared_axes=[1,2], name="PReLU1" )(x)
x = keras.layers.MaxPooling2D( pool_size=(2,2), strides=(2,2), padding='same' ) (x)
x = keras.layers.Conv2D (16, kernel_size=(3,3), strides=(1,1), padding='valid', name="conv2")(x)
x = keras.layers.PReLU (shared_axes=[1,2], name="PReLU2" )(x)
x = keras.layers.Conv2D (32, kernel_size=(3,3), strides=(1,1), padding='valid', name="conv3")(x)
x = keras.layers.PReLU (shared_axes=[1,2], name="PReLU3" )(x)
prob = keras.layers.Conv2D (2, kernel_size=(1,1), strides=(1,1), padding='valid', name="conv41")(x)
x = keras.layers.Conv2D (4, kernel_size=(1,1), strides=(1,1), padding='valid', name="conv42")(x)

pnet = K.function ([PNet_Input], [x,prob] )

img = np.random.uniform ( size=(1920,1920,3) )
minsize=80
factor=0.95
factor_count=0
h=img.shape[0]
w=img.shape[1]

minl=np.amin([h, w])
m=12.0/minsize
minl=minl*m
# create scale pyramid
scales=[]
while minl>=12:
    scales += [m*np.power(factor, factor_count)]
    minl = minl*factor
    factor_count += 1
    # first stage
    for scale in scales:
        hs=int(np.ceil(h*scale))
        ws=int(np.ceil(w*scale))
        im_data = cv2.resize(img, (ws, hs), interpolation=cv2.INTER_LINEAR)
        im_data = (im_data-127.5)*0.0078125
        img_x = np.expand_dims(im_data, 0)
        img_x = np.transpose(img_x, (0,2,1,3))
        t = time.time()
        out = pnet([img_x])
        t = time.time() - t
        print (img_x.shape, t)
```
![1](https://user-images.githubusercontent.com/8076202/53192722-9b15ce00-3628-11e9-84a5-fd7eae63ec85.gif)

**Comment by mijosch** [comment]
here is my code, nothing special, just a sliding window and a selftrained model for classification


`import os
import plaidml.keras
import tensorflow
plaidml.keras.install_backend()
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
import datetime

import imutils
from keras import Model
import keras
import numpy
from keras.models import load_model
import time
from PIL import Image
import cv2


image = cv2.resize(cv2.imread("Bild006.bmp"),None,fx=0.5,fy=0.5)


def pyramid(image, scale=1.5, minSize=(30, 30)):
	# yield the original image
	yield image
 
	# keep looping over the pyramid
	while True:
		# compute the new dimensions of the image and resize it
		w = int(image.shape[1] / scale)
		image = imutils.resize(image, width=w)
 
		# if the resized image does not meet the supplied minimum
		# size, then stop constructing the pyramid
		if image.shape[0] < minSize[1] or image.shape[1] < minSize[0]:
			break
 
		# yield the next image in the pyramid
		yield image

def sliding_window(image, stepSize, windowSize):
	# slide a window across the image
	for y in range(0, image.shape[0], stepSize):
		for x in range(0, image.shape[1], stepSize):
			# yield the current window
			yield (x, y, image[y:y + windowSize[1], x:x + windowSize[0]])

winW = winH = 64
count = 0
window1 = 0
tiles = []
tilepositions =[]
#session = tensorflow.Session()
#keras.backend.set_session(session)
model = load_model("Model_Federn.mdl")
for resized in pyramid(image, scale=1.5):
	clone1 = resized.copy() 
	clone = resized.copy()
	window1 = window1 +1
	print(str(datetime.datetime.now())+":start")
	# loop over the sliding window for each layer of the pyramid
	for (x, y, window) in sliding_window(resized, stepSize=int(winW/8), windowSize=(winW, winH)):
		# if the window does not meet our desired window size, ignore it
		if window.shape[0] != winH or window.shape[1] != winW:
			continue
 
		# THIS IS WHERE YOU WOULD PROCESS YOUR WINDOW, SUCH AS APPLYING A
		# MACHINE LEARNING CLASSIFIER TO CLASSIFY THE CONTENTS OF THE
		# WINDOW
		
		# since we do not have a classifier, we'll just draw the window
		#clone = resized.copy()
		iclone = cv2.resize(clone1[y:y + winH,x:x + winW],((32,32)))
		tilepositions.append([y,y + winH,x,x + winW])
		#iclone = cv2.resize(iclone,((224,224)))
		#iclone = Image.fromarray(iclone,'RGB')
		#cclone = numpy.array(iclone)
		#print(cclone.shape)
		tiles.append(iclone)
		#pred = model.predict(cclone)
		#print(pred)
		#cv2.imshow("1Window", iclone)
		#cv2.imwrite("generatedPics/img"+str(count)+".jpg",iclone)
		#cv2.imshow("Window"+str(window1), clone)
		#cv2.waitKey(delay=1)
		count = count +1
		#time.sleep(0.025)
	TileArray = numpy.asarray(tiles)
	#print(TileArray.shape)
	print(str(datetime.datetime.now())+":predict")
	pred = model.predict(TileArray)
	print(str(datetime.datetime.now())+":draw")
	for x in range(0,len(TileArray)):
		if pred[x][0] > 0.5:
			color = (255, 0, 0)
			cv2.rectangle(clone, (tilepositions[x][2], tilepositions[x][0]), (tilepositions[x][3], tilepositions[x][1]), color, 2)
		if pred[x][2] > 0.5:
			color = (0, 0, 255)
			cv2.rectangle(clone,  (tilepositions[x][2], tilepositions[x][0]), (tilepositions[x][3], tilepositions[x][1]), color, 2)
	#cv2.imshow("Window"+str(window1), clone)
	cv2.imwrite("Window"+str(window1)+".jpg",clone)
	#cv2.waitKey(delay=1)
	`

**Comment by brianretford** [comment]
I think this should be fixed by increasing the cache size limit as we did in 0.6.0, please reopen if it's not fixed
