### ISSUE TITLE
Converting tensorflow functions into plaidml equivalents

### ISSUE THREAD

**Issue by HarrisonWilde** [plaidml/plaidml#247]
Hi, not sure if I am missing something or being stupid (probably both) and sorry if this is the wrong place to ask, but I am trying to convert some keras / tensorflow code so it will work with plaidml and struggling. The majority of the network is created using keras but some functions such as tf.range, tf.multiply etc. are used and I was wondering if anyone knew of a way I could remove dependency on Tensors from tf and these associated functions but retain the functionality using plaidml?

Thanks!

**Comment by brianretford** [comment]
As noted on plaidml-dev, you can definitely port your code from tf/keras directly to keras. I will note that we support tensorflow directly now through nGraph, but we haven't released that functionality as wheels yet b/c we need more CI coverage. Wheels will be out in the next couple months
