### ISSUE TITLE
Memory allocation failure

### ISSUE THREAD

**Issue by mijosch** [plaidml/plaidml#251]
if i use a batchsize of 16 the first 2 epochs are running well.
If it starts with the 3. epoch i get an memory allocation error.

Does plaidml not free memory from previous epochs?
Is it supposed to act like that?

**Comment by earhart** [comment]
It's supposed to free memory from previous epochs, but I could believe there's a leak.  There could also be a leak in a driver, or something else in the stack; it would have to be a pretty large allocation for it to show up after only two epochs (or a whole lot of small allocations).

Which device are you using?

**Comment by mijosch** [comment]
Running on a quadro m2200 in my company laptop
Batch size is 4 and training images are about 600 224x224 pixel images

**Comment by brianretford** [comment]
Does this reproduce in the latest versions?

**Comment by dgkutnic** [comment]
Please let us know if you're able to reproduce this issue. Closing for now.
