### ISSUE TITLE
Error building plaidml on Ubuntu 16.04

### ISSUE THREAD

**Issue by Ananyaaa** [plaidml/plaidml#253]
I have followed the instructions below to build plaidml.
https://vertexai-plaidml.readthedocs-hosted.com/en/latest/building.html

Installed bazel and other requirements.

Following is the output when i try to build it.
~/plaidml-master/plaidml-master$ bazel build --config linux_x86_64 plaidml:wheel
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'toolchain' modified arguments {"shallow_since": "1545947467 -0800"}
ERROR: ~/.cache/bazel/_bazel_username/9b0652b59100ccdf0a226ae7e5dbe5c5/external/toolchain/BUILD:31:1: in cc_toolchain_suite rule @toolchain//:toolchain: Error while selecting cc_toolchain: No toolchain found for cpu 'linux_x86_64'. Valid toolchains are: [
  gcc-linux_arm_32v7: --cpu='linux_arm_32v7' --compiler='gcc',
  gcc-linux_arm_64v8: --cpu='linux_arm_64v8' --compiler='gcc',
  gcc-linux_x86_64: --cpu='linux_x86_64' --compiler='gcc',
]
ERROR: Analysis of target '//plaidml:wheel' failed; build aborted: Analysis of target '@toolchain//:toolchain' failed; build aborted
INFO: Elapsed time: 61.103s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (46 packages loaded, 23375 targets configured)

Has anyone tried building plaidml locally on linux (ubuntu)? Any help would be appreciated.

Details:
~/plaidml-master/plaidml-master$ bazel version
Build label: 0.23.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 26 17:42:16 2019 (1551202936)
Build timestamp: 1551202936
Build timestamp as int: 1551202936

~/plaidml-master/plaidml-master$ python --version
Python 2.7.12

Checked out the latest plaidml code from github (as of writing).

**Comment by flaub** [comment]
I haven't tried with bazel 0.23 yet, we're still on bazel 0.20, we might need to make some adjustments for it to work with latest bazel.

**Comment by flaub** [comment]
We've updated our building docs (but we haven't pushed the latest to readthedocs), could you try this?

https://github.com/plaidml/plaidml/blob/master/docs/building.md

**Comment by Ananyaaa** [comment]
flaub, i have not followed the building.md from github. I did follow from https://vertexai-plaidml.readthedocs-hosted.com/en/latest/building.html.

1) Install bazel.
2) Navigate to plaidml directory, where requirements.txt is present.
3) bazel build --config linux_x86_64 plaidml:wheel --- The above error is in this step.

I have not installed anaconda env and not created conda virtual env.
Anyways i will try bazel 0.19.2 and let you know. Thanks for the quick response.

**Comment by flaub** [comment]
We've spent a fair amount of time getting the conda environment to provide a reliable, portable, development environment across the 3 major platforms we support builds on (linux, macos, windows). I'd encourage you to use the conda environment since we will probably remove support for working outside the environment in the future.

Good luck!

**Comment by Ananyaaa** [comment]
Okay, i will follow instructions in 
https://github.com/plaidml/plaidml/blob/master/docs/building.md.

Will download anaconda python2.7 and bazel 0.19.2, will get back if any.
Thanks.

**Comment by Ananyaaa** [comment]
Followed https://github.com/plaidml/plaidml/blob/master/docs/building.md
Downloaded anaconda 2.7 for linux
downloaded bazel (0.19.2)
installed both of them.

Create conda env using, 
conda env create -n plaidml
conda activate plaidml

It updated bazel to 0.22
(plaidml) :~/plaidml-master/plaidml-master$ bazel version
INFO: Invocation ID: 4697a1f6-3047-409d-8888-85bc5c779178
Build label: 0.22.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Feb 16 12:11:29 2019 (1550319089)
Build timestamp: 1550319089
Build timestamp as int: 1550319089

After that ran 
bazel build --config linux_x86_64 //plaidml:wheel

Again, stuck at the same error, i am very much interested in trying out plaidml for my project but disappointed with this (windows also i am getting a different problem, will raise a separate request for that).

Is anyone facing the issue? Is anyone tried to build plaidml on windows or linux?
falub, can you help here?

**Comment by Ananyaaa** [comment]
As mentioned in the thread the error is,
/.cache/bazel/_bazel_ngubba/9b0652b59100ccdf0a226ae7e5dbe5c5/external/toolchain/BUILD:31:1: in cc_toolchain_suite rule @toolchain//:toolchain: Error while selecting cc_toolchain: No toolchain found for cpu 'linux_x86_64'. Valid toolchains are: [
  gcc-linux_arm_32v7: --cpu='linux_arm_32v7' --compiler='gcc',
  gcc-linux_arm_64v8: --cpu='linux_arm_64v8' --compiler='gcc',
  gcc-linux_x86_64: --cpu='linux_x86_64' --compiler='gcc',
]


I did look at the contents of /.cache/bazel/_bazel_ngubba/9b0652b59100ccdf0a226ae7e5dbe5c5/external/toolchain/BUILD. It has entry for cpu linux_x86_64. Pasting the file contents here, hoping some one can point out what is going wrong.

Note: I have not changes any thing in plaidml code, just downloaded from github.

config_setting(
    name = "linux_x86_64",
    values = {"cpu": "linux_x86_64"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux_arm_32v7",
    values = {"cpu": "linux_arm_32v7"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux_arm_64v8",
    values = {"cpu": "linux_arm_64v8"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "macos_x86_64",
    values = {"cpu": "darwin_x86_64"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "windows_x86_64",
    values = {"cpu": "x64_windows"},
    visibility = ["//visibility:public"],
)

cc_toolchain_suite(
    name = "toolchain",
    # target_cpu | compiler
    toolchains = {
        "linux_arm_32v7|gcc": ":cc-linux_arm_32v7",
        "linux_arm_64v8|gcc": ":cc-linux_arm_64v8",
        "linux_x86_64|gcc": ":cc-linux_x86_64",
        "linux_x86_64": ":cc-linux_x86_64",
    },
)

filegroup(
    name = "empty",
    srcs = [],
)

cc_toolchain(
    name = "cc-linux_arm_32v7",
    all_files = "//crosstool_ng/linux_arm_32v7:all_files",
    compiler_files = "//crosstool_ng/linux_arm_32v7:compiler_files",
    cpu = "linux_arm_32v7",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = "//crosstool_ng/linux_arm_32v7:linker_files",
    objcopy_files = "//crosstool_ng/linux_arm_32v7:objcopy",
    static_runtime_libs = [":empty"],
    strip_files = "//crosstool_ng/linux_arm_32v7:strip",
    supports_param_files = 1,
    visibility = ["//visibility:public"],
)

cc_toolchain(
    name = "cc-linux_arm_64v8",
    all_files = "//crosstool_ng/linux_arm_64v8:all_files",
    compiler_files = "//crosstool_ng/linux_arm_64v8:compiler_files",
    cpu = "linux_arm_64v8",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = "//crosstool_ng/linux_arm_64v8:linker_files",
    objcopy_files = "//crosstool_ng/linux_arm_64v8:objcopy",
    static_runtime_libs = [":empty"],
    strip_files = "//crosstool_ng/linux_arm_64v8:strip",
    supports_param_files = 1,
    visibility = ["//visibility:public"],
)

cc_toolchain(
    name = "cc-linux_x86_64",
    all_files = "//crosstool_ng/linux_x86_64:all_files",
    compiler_files = "//crosstool_ng/linux_x86_64:compiler_files",
    cpu = "linux_x86_64",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = "//crosstool_ng/linux_x86_64:linker_files",
    objcopy_files = "//crosstool_ng/linux_x86_64:objcopy",
    static_runtime_libs = [":empty"],
    strip_files = "//crosstool_ng/linux_x86_64:strip",
    supports_param_files = 1,
    visibility = ["//visibility:public"],
)

**Comment by Ananyaaa** [comment]
I did install bazel 0.19.2 explicitly and ran bazel build --config linux_x86_64 plaidml:wheel after doing cd to directory where plaidml code resides. Able to build successfully now. I have not used conda env as it is updating bazel .22, where also i am getting the same problem.

**Comment by zhanwenchen** [comment]
Bazel version 0.19.2 did not work for me but [0.18.0](https://github.com/bazelbuild/bazel/releases/tag/0.18.0) did.
