### ISSUE TITLE
Error building plaidml on Windows 10.

### ISSUE THREAD

**Issue by Ananyaaa** [plaidml/plaidml#255]
Following https://github.com/plaidml/plaidml/blob/master/docs/building.md
to build plaidml on windows 10.

Installed Anaconda C:\ProgramData\Anaconda3
installed bazel using choclatey

Make sure Anaconda, Anaconda/scripts, Python37, Python37/scripts, bazel eveything is on path.
Also did set BAZEL_SH c:\tools\msys64\usr\bin\bash.exe and BAZEL_PYTHON C:\Python37\python.exe

Rebooted the system as well.

Running the command to create conda env from plaidml source directory (C:\Users\uname\Downloads\plaidml-master\plaidml-master\)
giving me the following error, 
conda env create -n plaidml -f environment-windows.yml

PS C:\Users\uname\Downloads\plaidml-master\plaidml-master> conda env create -n plaidml -f environment-windows.yml
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Able to ping, 
PS C:\Users\uname\Downloads\plaidml-master\plaidml-master> ping www.anaconda.com

Pinging www.anaconda.com [104.16.131.3] with 32 bytes of data:
Reply from 104.16.131.3: bytes=32 time=60ms TTL=55
Reply from 104.16.131.3: bytes=32 time=58ms TTL=55
Reply from 104.16.131.3: bytes=32 time=52ms TTL=55
Reply from 104.16.131.3: bytes=32 time=52ms TTL=55

Ping statistics for 104.16.131.3:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 52ms, Maximum = 60ms, Average = 55ms

**Comment by Ananyaaa** [comment]
I tried building it by skipping the conda env creation, even in that case i am getting errors.

PS C:\Users\uname\Downloads\plaidml-master\plaidml-master> bazel build --config windows_x86_64 //plaidml:wheel
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Encountered error while reading extension file 'workspace.bzl': no such package '@toolchain//': Traceback (most recent call last):
        File "C:/users/uname/_bazel_uname/y4fsvkyb/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164
                _clone_or_update(ctx)
        File "C:/users/uname/_bazel_uname/y4fsvkyb/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning toolchain:
+ cd C:/users/uname/_bazel_uname/y4fsvkyb/external
+ rm -rf C:/users/uname/_bazel_uname/y4fsvkyb/external/toolchain C:/users/uname/_bazel_uname/y4fsvkyb/external/toolchain
/usr/bin/bash: line 5: rm: command not found
ERROR: error loading package '': Encountered error while reading extension file 'workspace.bzl': no such package '@toolchain//': Traceback (most recent call last):
        File "C:/users/uname/_bazel_uname/y4fsvkyb/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164
                _clone_or_update(ctx)
        File "C:/users/uname/_bazel_uname/y4fsvkyb/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning toolchain:
+ cd C:/users/uname/_bazel_uname/y4fsvkyb/external
+ rm -rf C:/users/uname/_bazel_uname/y4fsvkyb/external/toolchain C:/users/uname/_bazel_uname/y4fsvkyb/external/toolchain
/usr/bin/bash: line 5: rm: command not found
INFO: Elapsed time: 11.446s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @toolchain; Cloning a487bf9f2cc4edc47d376606abaaf29d85fffcd8 of https://github.com/plaidml/toolchain 8s


After googling for these errors, i am finally wondered has anyone build plaidml on windows successfully.
Thanks in advance.

**Comment by brianretford** [comment]
We build it every night - did you clone with --recursive?

**Comment by brianretford** [comment]
feel free to reopen is a recursive clone did not fix the issue
