### ISSUE TITLE
Radeon VII (Vega 20) support

### ISSUE THREAD

**Issue by sergeykern** [plaidml/plaidml#257]
Hi,
I just wanted to continue my studies with keras, but I cannot use plaidml as backend for keras since I swapped my RX Vega 56 for the Radeon VII. 
Output of plaidml-setup: 

> PlaidML Setup (0.5.0)
>
>Thanks for using PlaidML!

>Some Notes:
>  * Bugs and other issues: https://github.com/plaidml/plaidml
>  * Questions: https://stackoverflow.com/questions/tagged/plaidml
>  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
>  * PlaidML is licensed under the GNU AGPLv3

>No OpenCL devices found. Check driver installation.
>Read the helpful, easy driver installation instructions from our README:
>http://github.com/plaidml/plaidml

Output of clinfo:

> Number of platforms:                             1
>   Platform Profile:                              FULL_PROFILE
>   Platform Version:                              OpenCL 2.1 AMD-APP (2766.5)
>   Platform Name:                                 AMD Accelerated Parallel Processing
>   Platform Vendor:                               Advanced Micro Devices, Inc.
>   Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
> 
> 
>   Platform Name:                                 AMD Accelerated Parallel Processing
> Number of devices:                               1
>   Device Type:                                   CL_DEVICE_TYPE_GPU
>   Vendor ID:                                     1002h
>   Board name:                                    AMD Radeon VII
>   Device Topology:                               PCI[ B#30, D#0, F#0 ]
>   Max compute units:                             60
>   Max work items dimensions:                     3
>     Max work items[0]:                           1024
>     Max work items[1]:                           1024
>     Max work items[2]:                           1024
>   Max work group size:                           256
>   Preferred vector width char:                   4
>   Preferred vector width short:                  2
>   Preferred vector width int:                    1
>   Preferred vector width long:                   1
>   Preferred vector width float:                  1
>   Preferred vector width double:                 1
>   Native vector width char:                      4
>   Native vector width short:                     2
>   Native vector width int:                       1
>   Native vector width long:                      1
>   Native vector width float:                     1
>   Native vector width double:                    1
>   Max clock frequency:                           1802Mhz
>   Address bits:                                  64
>   Max memory allocation:                         4244635648
>   Image support:                                 Yes
>   Max number of images read arguments:           128
>   Max number of images write arguments:          64
>   Max image 2D width:                            16384
>   Max image 2D height:                           16384
>   Max image 3D width:                            2048
>   Max image 3D height:                           2048
>   Max image 3D depth:                            2048
>   Max samplers within kernel:                    16
>   Max size of kernel argument:                   1024
>   Alignment (bits) of base address:              2048
>   Minimum alignment (bytes) for any datatype:    128
>   Single precision floating point capability
>     Denorms:                                     No
>     Quiet NaNs:                                  Yes
>     Round to nearest even:                       Yes
>     Round to zero:                               Yes
>     Round to +ve and infinity:                   Yes
>     IEEE754-2008 fused multiply-add:             Yes
>   Cache type:                                    Read/Write
>   Cache line size:                               64
>   Cache size:                                    16384
>   Global memory size:                            16978542592
>   Constant buffer size:                          4244635648
>   Max number of constant args:                   8
>   Local memory type:                             Scratchpad
>   Local memory size:                             32768
>   Max pipe arguments:                            16
>   Max pipe active reservations:                  16
>   Max pipe packet size:                          4244635648
>   Max global variable size:                      3820172032
>   Max global variable preferred total size:      16978542592
>   Max read/write image args:                     64
>   Max on device events:                          1024
>   Queue on device max size:                      8388608
>   Max on device queues:                          1
>   Queue on device preferred size:                262144
>   SVM capabilities:
>     Coarse grain buffer:                         Yes
>     Fine grain buffer:                           Yes
>     Fine grain system:                           No
>     Atomics:                                     No
>   Preferred platform atomic alignment:           0
>   Preferred global atomic alignment:             0
>   Preferred local atomic alignment:              0
>   Kernel Preferred work group size multiple:     64
>   Error correction support:                      0
>   Unified memory for Host and Device:            0
>   Profiling timer resolution:                    1
>   Device endianess:                              Little
>   Available:                                     Yes
>   Compiler available:                            Yes
>   Execution capabilities:
>     Execute OpenCL kernels:                      Yes
>     Execute native function:                     No
>   Queue on Host properties:
>     Out-of-Order:                                No
>     Profiling :                                  Yes
>   Queue on Device properties:
>     Out-of-Order:                                Yes
>     Profiling :                                  Yes
>   Platform ID:                                   00007FFDF9386FD0
>   Name:                                          gfx906
>   Vendor:                                        Advanced Micro Devices, Inc.
>   Device OpenCL C version:                       OpenCL C 2.0
>   Driver version:                                2766.5 (PAL,HSAIL)
>   Profile:                                       FULL_PROFILE
>   Version:                                       OpenCL 2.0 AMD-APP (2766.5)
>   Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash cl_amd_planar_yuv

I would be very appreciated if plaidml would support my GPU.
Thanks in advance.

Edit:
Even after editing the config.json and the experimental.json plaidml-setup did not recognize my gpu. I tried AMD.* / .* for vendor and .\*gfx906.\* for device device name (from OpenCL output). I even stepped through the code of plaidml-setup but the recognition of devices is happening in plaidml.dll and I'm not experienced in decompiling dlls...
I would suspect that 
`tile::proto::ListDevicesRequest req;`
` tile::proto::ListDevicesResponse resp;`
` enumerator->platform->ListDevices(activity.ctx(), req, &resp);` in line 248 of plaidml.cc doesn't return my device.

Edit2:
On Ubuntu I'm now getting this error:

> PlaidML Setup (0.5.0)
> 
> Thanks for using PlaidML!
> 
> Some Notes:
>   * Bugs and other issues: https://github.com/plaidml/plaidml
>   * Questions: https://stackoverflow.com/questions/tagged/plaidml
>   * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
>   * PlaidML is licensed under the GNU AGPLv3
>  
> Traceback (most recent call last):
>   File "/usr/local/bin/plaidml-setup", line 10, in <module>
>     sys.exit(main())
>   File "/home/sk/.local/lib/python3.5/site-packages/plaidml/plaidml_setup.py", line 44, in main
>     devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
>   File "/home/sk/.local/lib/python3.5/site-packages/plaidml/__init__.py", line 1042, in devices
>     enumerator = _Enumerator(ctx)
>   File "/home/sk/.local/lib/python3.5/site-packages/plaidml/__init__.py", line 1000, in __init__
>     ctx, ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
>   File "/home/sk/.local/lib/python3.5/site-packages/plaidml/__init__.py", line 746, in _check_err
>     self.raise_last_status()
>   File "/home/sk/.local/lib/python3.5/site-packages/plaidml/library.py", line 131, in raise_last_status
>     raise self.last_status()
> plaidml.exceptions.Unknown: unable to resolve type: 

Phoronix got their Radeon VII to work:
[https://www.phoronix.com/scan.php?page=article&item=radeon-vii-linux&num=9]( )

**Comment by kirmorozov** [comment]
Will join debugging in 2 weeks after Vega 20 arrival.

**Comment by brianretford** [comment]
Which platform are you using?

**Comment by kirmorozov** [comment]
Ok, Vega 20 arrived, I have following results:
```bash
$ plaidbench keras vgg19
Running 1024 examples with vgg19, batch size 1, on backend plaid
INFO:plaidml:Opening device "metal_amd_radeon_pro_vega_20.0"
Model loaded.
Compiling network...INFO:plaidml:Analyzing Ops: 103 of 193 operations complete
 Warming up... Running...
Example finished, elapsed: 5.614s (compile), 44.733s (execution)

keras metal_amd_radeon_pro_vega_20.0
-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS          
-----------------------------------------------------------------------------------------
vgg19                43.68 ms                  43.68 ms / 22.89 fps
Correctness: PASS, max_error: 4.833400453208014e-06, max_abs_error: 2.980232238769531e-07, fail_ratio: 0.0
```

**Comment by brianretford** [comment]
Those are kind of disappointing results. We are working on a major refactor of the GPU backend and it should be out in the next week or two. It should let us really bump the AMD perf

**Comment by brianretford** [comment]
Er actually I think that's reasonable - the card is this one: https://www.techpowerup.com/gpu-specs/radeon-pro-vega-20.c3263?

**Comment by kirmorozov** [comment]
I'm using this benchmark as reference:
https://browser.geekbench.com/opencl-benchmarks
Anyway this one is much better for local prototyping, yes not as superior as 2080 Ti.
