### ISSUE TITLE
plaidml-setup on windows aborting

### ISSUE THREAD

**Issue by daniel-zing** [plaidml/plaidml#259]
Hi

I am trying to configure plaidml on windows 10 with python 3.6.8 using plaidml-setup.

But when i run plaidml-setup it starts but then aborts before the configuration part of the setup withput errors.

(py368) D:\>plaidml-setup

PlaidML Setup (0.5.0)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the GNU AGPLv3

(py368) D:\>

any ideas why this is happening or how i can debug this?

**Comment by brianretford** [comment]
Can you try installing 0.6.0rc1 and see if this problem is resolved?

**Comment by Danila2221** [comment]
> Can you try installing 0.6.0rc1 and see if this problem is resolved?

I have the same problem. Installing a new version does not help. My GPU is RX470

**Comment by brianretford** [comment]
Sorry you're having problems @Danila2221 can you send me a clinfo dump and let me know what platform you're using?

**Comment by Danila2221** [comment]
> Sorry you're having problems @Danila2221 can you send me a clinfo dump and let me know what platform you're using?

Windows 10 64 bit. I use the miniconda, but on the usual python the same problem.
clinfo: https://pastebin.com/RucGPK7z

**Comment by brianretford** [comment]
Interesting, can you also copy the entire output of running plaidml-setup?

**Comment by Danila2221** [comment]
> Interesting, can you also copy the entire output of running plaidml-setup?

Please tell me how to do it.

**Comment by brianretford** [comment]
Sorry for the delay, can you try again w/ 0.6.0 and let us know if it reproduces
