### ISSUE TITLE
Cannot init device within Celery worker thread

### ISSUE THREAD

**Issue by kirmorozov** [plaidml/plaidml#263]
It works fine within standalone script.
It does not seem to be fork-friendly. 

Cannot make it run within Celery worker thread:
> [2019-03-10 01:11:49,991: WARNING/ForkPoolWorker-8] Using plaidml.keras.backend backend.
> objc[69206]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
> objc[69206]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
> [2019-03-10 01:11:50,154: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:69206 exited with 'signal 6 (SIGABRT)'
> [2019-03-10 01:11:50,169: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT).',)
> Traceback (most recent call last):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
>     human_status(exitcode)),

System (Macbook Pro Early 2013) info:
> Default Config Devices:
>    metal_intel_hd_graphics_4000.0 : Intel HD Graphics 4000 (Metal)
> 
> Experimental Config Devices:
>    llvm_cpu.0 : CPU (LLVM)
>    opencl_nvidia_geforce_gt_650m.0 : NVIDIA GeForce GT 650M (OpenCL)
>    metal_intel_hd_graphics_4000.0 : Intel HD Graphics 4000 (Metal)
>    opencl_intel_hd_graphics_4000.0 : Intel HD Graphics 4000 (OpenCL)
>    opencl_cpu.0 : Intel CPU (OpenCL)
>    metal_nvidia_geforce_gt_650m.0 : NVIDIA GeForce GT 650M (Metal)
>

**Comment by brianretford** [comment]
Indeed making it fork friendly would be quite challenging. If you need it to be fork friendly you need to ensure that each fork loads it independently, i.e., post-fork

**Comment by kirmorozov** [comment]
I moved all the initialization all the way to the end, it does not help.
Same code with external initialization in standalone script works perfectly.

This just prevents production use in my case, TF works well with post-fork.

**Comment by kirmorozov** [comment]
My journey ended up here:
https://github.com/plaidml/plaidml/blob/ec748d1cb488e5863b8134ec843cf85442df644d/plaidml/__init__.py#L991
Then worker dies, few steps deeper.

**Comment by kirmorozov** [comment]
Please help to debug deeper,
https://github.com/plaidml/plaidml/blob/ec748d1cb488e5863b8134ec843cf85442df644d/plaidml/plaidml.cc#L212 

Is there way to compile with all the debugging capabilities for C? Using JetBrains Idea.

**Comment by brianretford** [comment]
Can you share your code?

**Comment by kirmorozov** [comment]
Sure, let me forge test case with minimal dependencies.

**Comment by kirmorozov** [comment]
Hm, I forged sample, sample worked fine with late initialization, looks like I have some dependencies to debug in my fat app.

Early keras application import kills ( put `import keras.applications as kapp` at first line) worker same way as described above.

Following code works:
Here is `flask_celery.py` test server.
```python
from celery import Celery

def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery

from flask import Flask

flask_app = Flask(__name__)
flask_app.config.update(
    CELERY_BROKER_URL='redis://localhost:6379/2',
    CELERY_RESULT_BACKEND='redis://localhost:6379/2'
)
celery = make_celery(flask_app)

@celery.task()
def add_together(a, b):
    import keras.applications as kapp
    model = kapp.VGG19(weights=None)
    return a + b

@flask_app.route('/')
def hello_world():
    result = add_together.delay(23, 42)
    r = result.wait()
    return f'Hello, World!{r}'
```
To run worker:
```bash
celery worker -A flask_celery.celery -l INFO
```
To run server/flask:
```bash
FLASK_APP=flask_celery.py flask run
```

**Comment by brianretford** [comment]
Cool! I'm glad it works. I'd love to make plaid fork friendly, but lots of the user land OCL drivers we encountered aren't, so there doesn't seem to be a safe way to do it
