### ISSUE TITLE
Explanations of experimental.json

### ISSUE THREAD

**Issue by iamlion12** [plaidml/plaidml#265]
Hello! It will be really helpful, if there will be some guide for options provided in config file or maybe you have some reference for it explanation.

**Comment by brianretford** [comment]
Hey! The config files are basically terrible. They made sense at the time to us but we're certain they are bad. Stay tuned for a complete reworked system (with explanations :-)

**Comment by brianretford** [comment]
We'll be replacing experimental.json before 1.0

**Comment by preFiredman** [comment]
till now, your new doc still list usage of custom config json file:
https://plaidml.github.io/plaidml/docs/building.html
so, why can't u just tell us what's the exact meanings in the json file?

**Comment by hemangjoshi37a** [comment]
but at which location experimental.json is at? in windows 10
