### ISSUE TITLE
Swift for TensorFlow Support

### ISSUE THREAD

**Issue by Gerzer** [plaidml/plaidml#267]
Will PlaidML ever support [Swift for TensorFlow](https://www.tensorflow.org/swift)?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brianretford** [comment]
Possibly yes, if so it will be through Chris Latner and co's new MLIR project which you can read about (along with some material about our polyhedral IR, Stripe) here: www.c4ml.org
