### ISSUE TITLE
arange not implemented

### ISSUE THREAD

**Issue by hatarist** [plaidml/plaidml#268]
Sorry, I'm new to ML and I'm not sure I could contribute.

I ran into this issue while trying to run https://github.com/ksanjeevan/dourflow/ with PlaidML.

The traceback:
```
Traceback (most recent call last):
  File "dourflow.py", line 7, in <module>
    from net.netarch import generate_model
  File "/Users/igor/Projects/dourflow/net/netarch.py", line 16, in <module>
    from .netparams import YoloParams
  File "/Users/igor/Projects/dourflow/net/netparams.py", line 75, in <module>
    class YoloParams(object):
  File "/Users/igor/Projects/dourflow/net/netparams.py", line 156, in YoloParams
    c_grid = generate_yolo_grid(BATCH_SIZE, GRID_SIZE, NUM_BOUNDING_BOXES)
  File "/Users/igor/Projects/dourflow/net/netparams.py", line 63, in generate_yolo_grid
    c_x = K.cast(K.reshape(K.tile(K.arange(g), [g]), (1, g, g, 1, 1)), K.floatx())
  File "/Users/igor/.virtualenvs/tensorflow/lib/python3.6/site-packages/plaidml/keras/backend.py", line 210, in arange
    _report_unimplemented('arange')
  File "/Users/igor/.virtualenvs/tensorflow/lib/python3.6/site-packages/plaidml/keras/backend.py", line 103, in _report_unimplemented
    raise NotImplementedError(report)
NotImplementedError: The Keras backend function 'arange' is not yet implemented in Plaid. You can help us prioritize by letting us know if this function is important to you, and as always, contributions are welcome!
```

**Comment by iperov** [comment]
I investigated this repo where K.arange used.
```
c_grid = generate_yolo_grid(BATCH_SIZE, GRID_SIZE, NUM_BOUNDING_BOXES)

def generate_yolo_grid(batch, g, num_bb):
    c_x = K.cast(K.reshape(K.tile(K.arange(g), [g]), (1, g, g, 1, 1)), K.floatx())
    c_y = K.permute_dimensions(c_x, (0,2,1,3,4))
    return K.tile(K.concatenate([c_x, c_y], -1), [batch, 1, 1, num_bb, 1])
```
try to replace `K.arange(g)`
with
`K.constant ( np.arange(0, g, dtype=K.floatx()) )`

**Comment by SleepProgger** [comment]
Is there a case i missed where iperovs solution won't  work ?
If not i suggest adding it to the backend.
If start, stop and step can't be tensors that should be all that is required and would bring plaidml a step further to completely implementing the keras backend functions.

```
def arange(start, stop=None, step=1, dtype='int32'):
    return constant( np.arange(start, stop, step, dtype) )
 ```

**Comment by brianretford** [comment]
@iperov we’d love a PR. @tzerrell is our resident front end and Tile expert, I’ll have him review this and the patch match stuff. We’ll definitely want to incorporate your patch match stuff in the overall solution

**Comment by tzerrell** [comment]
Thanks for the PR for this in https://github.com/plaidml/plaidml/pull/291, we'll get that into 0.6.1

**Comment by iperov** [comment]
@SleepProgger 
actually implement arange via np.arange  is a huge mistake. 
Better remove it.
Because plaidml engine must provide arange for variable values during runtime for example batch_size that can be obtained in runtime only.
