### ISSUE TITLE
Write a more programmer-centric tile dialect / add documentation

### ISSUE THREAD

**Issue by iperov** [plaidml/plaidml#269]
I am programmer, not math professor. Is there any approach how to understand Tile language?

I read tutorial provided here https://vertexai-plaidml.readthedocs-hosted.com/en/latest/index.html but didnt understand.

I am trying to implement reflected padding,
but all "examples" in op.py uses a lot of string formatters which are impossible to understand.

**Comment by Degerz** [comment]
Ironic considering you brushed off concerns of the programming language not too long ago. There are no tutorials for programmers and this is not a design flaw of the programming language but it's a feature ... ;)

You need to frame your algorithms like a mathematician would so good luck trying to get a feel for what a tensor is along with all these other notations ...

**Comment by brianretford** [comment]
We are definitely planning a major doc push as soon as I have resources for it. Know anybody good? We are also planning on both redesigning it as well as potentially incorporating Stripe compilation into julia, etc (in addition tile). Tile is really just a fancy concise way to write map reduces. Did you find tvm's or tensor comprehensions more understandable?

**Comment by brianretford** [comment]
Did you manage to find this page in the docs? https://vertexai-plaidml.readthedocs-hosted.com/en/latest/adding_ops.html

**Comment by iperov** [comment]
yes I read all these docs.

I start understanding principles while playing in console 
`t[:,0:64,128::2,0].source.op.code`
that prints the tile code, so I can deduce relations

**Comment by brianretford** [comment]
Cool. Now that you have a bit of an idea what they language is like, any thoughts on what you'd like to be programming in? Things like these are pretty translatable and much more programmer friendly:

https://github.com/JuliaGPU/GPUArrays.jl
https://stsievert.com/blog/2016/07/01/numpy-gpu/

**Comment by SleepProgger** [comment]
just my 2 cents. A numpy like interface for tile code would be freaking awesome.

**Comment by brianretford** [comment]
We've been working on a C++ EDSL that we'll be releasing docs and code for soon

**Comment by flaub** [comment]
We now have a Python EDSL to replace the string-based on of today. It isn't integrated yet but will be coming soon.

**Comment by iperov** [comment]
what is ESDL ? how to use it? any documentatino?
