### ISSUE TITLE
K.stack is unimplemented

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#271]
```
NotImplementedError: The Keras backend function 'stack' is not yet implemented in Plaid. You can help us prioritize by letting us know if this function is important to you, and as always, contributions are welcome!
```

Since stack is a function commonly used in K-functions it would be nice to have it.
Seems like it would be easy to implement via Tile, but that language is a bit too strange for me currently.

**Comment by brianretford** [comment]
Will make it into 0.6.1

**Comment by tzerrell** [comment]
Thanks for adding this in #292!
