### ISSUE TITLE
IRC or discord channel for plaidml ?

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#280]
Would it be possible to set up a plaidml IRC or discord channel for plaidml ?
Doesn't need to be official supported, but it would be nice to have a way to communicate with other plaidml enthusiast (and maybe even devs) and not just in issues/PRs.

I know there is already the google.group but its not the same as a chat system.

**Comment by quocdat32461997** [comment]
That would be great. I don’t use Discord but still I can download it. 
Can you send me the link to the discord?
Thanks

**Comment by SleepProgger** [comment]
That was more a question if there is interest in that and if maybe the devs could set one up.
But, i went ahead and created a `plaidml` server on discord.
As i have no clue about managing server on discord i'd gladly give that server to whoever has ;)

So for now: completely unofficial and probably empty, except me;)
https://discord.gg/n36dta

**Comment by brianretford** [comment]
Just FYI this would be great - we're looking into setting up something official right now

**Comment by SleepProgger** [comment]
Awesome. If you want the discord server i'd gladly transfer it to you (if that works, that is. I have absolutely no clue about discord ;) )

**Comment by dgkutnic** [comment]
We have a #plaidml channel within the nGraph Slack workspace that's open to both internal and external PlaidML enthusiasts. [Feel free to join us!](https://join.slack.com/t/ngraph/shared_invite/enQtNjI1NDA2NjgwODk4LTc3NjU3ZGZhNTIxMWRhYmE1NjQyZWM4N2ZkYzc4MzY0MzM0MjFiZWYyMjg0MjU5YzA4MDNmOTZkMGQyZTQxNWE)

**Comment by IIIBlueberry** [comment]
> 
> 
> We have a #plaidml channel within the nGraph Slack workspace that's open to both internal and external PlaidML enthusiasts. [Feel free to join us!](https://join.slack.com/t/ngraph/shared_invite/enQtNjI1NDA2NjgwODk4LTc3NjU3ZGZhNTIxMWRhYmE1NjQyZWM4N2ZkYzc4MzY0MzM0MjFiZWYyMjg0MjU5YzA4MDNmOTZkMGQyZTQxNWE)
> (Note: this invite link is temporary and will only be active for three weeks; we're working on a more permanent solution that everyone can use to join our slack channel!)

How about a matrix server? For those who dont know what is it, "Matrix is an open source project that publishes the
Matrix open standard for secure, decentralised, real-time communication," think it as IRC successor.

a cool idea of Matrix is interoperability, allowing sending message between other communication systems and vise versa via bridging.

We could have someone from plaidml member host a matrix server, bridge plaidml slack channel and optionally discord server to plaidml matrix server

useful info:
https://matrix.org/
https://matrix.org/docs/guides/introduction

https://wiki.mozilla.org/Matrix#.22What_is_the_Matrix.3F.22
https://matrix.org/blog/2020/03/03/moznet-irc-is-dead-long-live-mozilla-matrix

slack bridge : https://matrix.org/bridges/#slack https://github.com/matrix-org/matrix-appservice-slack
