### ISSUE TITLE
Multiple easy backend function implementations

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#282]
I implemented some of the missing keras.backend functions (the easy ones) and love to have some feedback.
No PR yet, because i am not sure about some of them (and didn't feel like writing test cases tbh ;))

Some open questions:
- Is there anything i missed for the `any` and `all` implementations ? They feel a bit hackish, but should work well.
- Do i see that right that all the random function without `_variable` at the end should be executed on the device and thus create new outputs for every call ? Whereas the ones with `_variable` at the end of the name should only be created once ?
- When should the result be a constant and when a variable ? Is there even a difference with plaidml backends ? The `arange` impl fe: returns a constant. Is this the correct approach ?
- Is my handling of dtypes for functions which create wrapped numpy values correct ? The idea is that both tile.Dtype and np.dtype + strings are accepted.
- Is there a reason that `variable` doesn't use the dtype of the np.array (if that is the input) even when the variable dtype parameter is set to None ?
- Probably more question i missed, but see `TODO`s

```
def any(x, axis=None, keepdims=False):
    # Should probably check if int* or bool ?
    truths = plaidml.op.summation(x, axis, keepdims, floatx=plaidml.DType.INT32)
    return not truths > 0


def all(x, axis=None, keepdims=False):
    # Should probably check if int* or bool ?
    truths = plaidml.op.summation(x, axis, keepdims, floatx=plaidml.DType.INT32)
    if axis is None:
        # == and != (magic functions) doesn't seem to be implemented for plaidml tensor/variables
        # why not ? The magic functions for lt and gt seem to be implemented. + equal and not_equal works 
        items = np.prod(x.shape.dims)
        return K.equal(truths, items)
    return K.equal(truths, x.shape.dims[axis])


def arange(start, stop=None, step=1, dtype='int32'):
    # basically iperovs impl
    try:
        dtype = ptile.convert_pml_dtype_to_np(dtype)
    except ValueError: pass
    return K.constant( np.arange(start, stop, step, dtype), dtype=dtype)


class CumulativeProd(ptile.Operation):
    """Cumulative product of a tensor"""

    def __init__(self, x, axis=0):
        ranges = ', '.join(['N{}'.format(n) for n in range(x.shape.ndims)])
        dest_idxs = ', '.join(['i{}'.format(n) for n in range(x.shape.ndims)])
        src_idxs = ['i{}'.format(n) for n in range(x.shape.ndims)]
        src_idxs[axis] += ' - k'
        src_idxs = ', '.join(src_idxs)
        f = """
            function (I[{src_ranges}]) -> (O) {{
                O[{dest_idxs}: {dest_ranges}] = *(I[{src_idxs}]), k < N{ax};
            }}""".format(
            src_ranges=ranges, dest_idxs=dest_idxs, dest_ranges=ranges, src_idxs=src_idxs, ax=axis)
        super(CumulativeProd, self).__init__(f, [('I', x)], [('O', x.shape)])

cumprod = CumulativeProd.function


def eye(size, dtype=None, name=None):
    # TODO: I am not sure if that is a good idea to use np here instead of generating this on the device .?
    if dtype is None:
        dtype = K.floatx()
    else:
        try:
            dtype = ptile.convert_pml_dtype_to_np(dtype)
        except ValueError: pass
    return K.constant(np.eye(size, dtype=dtype), name=name, dtype=dtype)


def random_normal_variable(shape, mean, scale, dtype=None, name=None, seed=None):
    if seed is not None:
        np.random.seed(seed)
    if dtype is None:
        dtype = K.floatx()
    else:
        try:
            dtype = ptile.convert_pml_dtype_to_np(dtype)
        except ValueError: pass
    data = np.random.normal(mean, scale, shape).astype(dtype)
    return K.variable(data)


def sign(data):
    return ptile.unary_op(data, "I == 0 ? 0 : (I > 0 ? 1 : -1)", name="Sign")

def stack(x, axis=0):
    tshape = x[0].shape
    for item in x:
        if tshape != item.shape:
            raise ValueError("All inputs must have the same shape and type")
    nshape = list(tshape.dims)
    nshape.insert(axis if axis >= 0 else len(nshape), 1)
    return K.concatenate([K.reshape(item, nshape) for item in x], axis=axis)
```

Possible fixes for:
#271

**Comment by SleepProgger** [comment]
If i start to send PRs for this functions, should i send one for each function or can i merge (at least some) into a single PR ?

**Comment by brianretford** [comment]
Fewer PRs are better for us. I'm going to start merging them in today

**Comment by brianretford** [comment]
Also, please email me at brian.retford [at] intel.com, we have some cool swag we'd like to send you if you're interested!

**Comment by SleepProgger** [comment]
Ok, i am going to split in two or three PRs.
Will add unit tests too. ETA probably today

**Comment by SleepProgger** [comment]
- arange, eye and random_normal_variable added in #291 

Having some troubles with the any and all implementation. Is testing it with `compareForward` good enough for those ?
TF doesn't seem to be able to create gradients for them (or i messed something up)

**Comment by brianretford** [comment]
We'll get your PRs into 0.6.1.
