### ISSUE TITLE
plaidml + Intel 520  is about 20x slower than Intel I7 6600@2,6GHz or Ryzen5

### ISSUE THREAD

**Issue by MPenzlin** [plaidml/plaidml#286]
Hello,

as written above, with plaidml the Performance is very slow.
Is this due to the small Network? ( 30 Input, only 1 hidden layer with 6 Neurons, only one Output layer with 1 Neuron) or did I use the plaidml in a way that is not appropiate?
Below the code:

```
import numpy as np 
import plaidml.keras 
plaidml.keras.install_backend() 
from keras.layers import Dense 
from keras.models import Sequential 
from keras.optimizers import SGD 
from keras.initializers import VarianceScaling 
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler() 
np.set_printoptions(edgeitems =50) 
  
np.random.seed(42) 
fFloat  = open("C:/10000_examples.csv","r") 
XundY = np.loadtxt(fFloat, delimiter=","); 
fFloat.close() 

X=XundY[:,0:30] 
X=sc.fit_transform(X) 

Y=XundY[:,30:31] 

yMin = Y.min(axis=0); 
yMax = Y.max(axis=0) 

TrainSet     = np.random.choice(X.shape[0],int(X.shape[0]*0.8), replace=False) 
XTrain       = X[TrainSet,:] 
YTrain       = Y[TrainSet] 
TestSet      = np.delete(np.arange(0, len(Y) ), TrainSet) 
XTest        = X[TestSet,:] 
YTest        = Y[TestSet] 

myANN = Sequential() 
myANN.add(Dense(6,input_dim=30,kernel_initializer=VarianceScaling(),activation='sigmoid',use_bias=True)) 
myANN.add(Dense(1,kernel_initializer=VarianceScaling(),activation='sigmoid',use_bias=True)) 
myANN.compile(loss='mean_squared_error', optimizer = 'RMSprop', metrics=['accuracy']) 
history = myANN.fit(XTrain,YTrain, batch_size = 1, epochs=10, verbose=True) 
```

  
Kind regards
Matthias

**Comment by brianretford** [comment]
For very small networks CPUs are often faster than GPUs, so it’s hard to say. CPUs are much more competitive for inference than most people realize. Were you training or predicting? GPUs are best with reasonable minibatch sizes.

All that said our performance is not great on Intel hardware and is very dependent on the driver stack (beignet currently performs the best). As you might imagine we are very actively engaged in improving performance on Intel GPUs. More on that soon…
