### ISSUE TITLE
"Analyzing Ops", followed by either "Abort trap: 6" or "Unable to Compile Tile Program" 

### ISSUE THREAD

**Issue by vrl2** [plaidml/plaidml#287]
When using `opencl_amd_amd_radeon_rx_580_compute_engine.0` I am getting a similar error as [Issue 207](https://github.com/plaidml/plaidml/issues/207) -- `Analyzing Ops...` followed by `Unable to Compile Tile Program.`  Similar to #207 , I successfully get to `INFO:plaidml:Analyzing Ops: 227736 of 235878 operations complete`. There's then a long hang, followed by a long hang, and thousands of lines of C/C++ code, and then the `Unable to Compile...` message.

However, when using `metal_amd_radeon_rx_580.0` I experience a different set of errors: I reach `Analyzing Ops: xxx of 235878 operations complete,` but then the computer either resets (version 0.5.0) or halts with with `Abort trap: 6` (with 0.6.0 rc2).

I'm running [this example code](https://github.com/javaidnabi31/Word-Embeddding-Sentiment-Classification), [description here](https://github.com/javaidnabi31/Word-Embeddding-Sentiment-Classification) on a Mac Pro 5,1, 10.14.4, Python 3.68 with Anaconda.

I'd appreciate any insights or suggestions. @brianretford , is this a distinct issue from the one you addressed in post #207 ? Thanks in advance for your time!

[plaidML_crash.txt](https://github.com/plaidml/plaidml/files/3040743/plaidML_crash.txt)

**Comment by cnamrata15** [comment]
We have made some changes, can you pull down the latest master and let us know if the issue still persists? 
If it does, can you add a minimal reproduce?

**Comment by brianretford** [comment]
Friendly ping. Can you try to reproduce on 0.6.0 and reopen if it does? Fundamentally this looks like a degenerate RNN case. We are planning on supporting recursion in the next major version in an efficient manner.
