### ISSUE TITLE
TILE: plaidml.exceptions.Unknown: Variable _T2 used in a context which requires it to be a constant integer

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#290]
*Sorry for the amount of opened issues.*

When using a float casted to an int as dimensions for an array in tile i run into this exception:
`plaidml.exceptions.Unknown: Variable _T2 used in a context which requires it to be a constant integer`

Example:
```
    import keras
    from plaidml.keras import backend as K
    import plaidml    
    import numpy as np
    
    op = plaidml.tile.Operation(
        """
            function (I[J]) -> (O){
                NJ = as_int(2.0, 32);
                O[nj : NJ] = =(I[nj]);
            }
        """,
        [('I', K.constant(np.arange(5), dtype="float32"))],
        [('O', plaidml.tile.Shape(plaidml.DType.FLOAT32, (2,)))])
    
    print(op.sole_output().eval())
```

Is this the expected behavior, and if it is is there any workaround ?

**Comment by brianretford** [comment]
Don't apologize! This is a fundamental issue in the current design. We will be supporting dynamic shapes in 1.x
