### ISSUE TITLE
Viewing OpenCL C code cache

### ISSUE THREAD

**Issue by leohentschker** [plaidml/plaidml#293]
I'm looking to export the OpenCL kernels generated by setting the `PLAIDML_OPENCL_CACHE` environment variable. However no matter how I set `PLAIDML_OPENCL_CACHE` or which device I choose in `plaidml-setup`, no OpenCL code is generated.

If anyone has figured out how to generate OpenCL code I would really appreciate the help!

**Comment by flaub** [comment]
Are you using an absolute path?

**Comment by leohentschker** [comment]
Nevermind it was a mistake in how I set the environment variable! Thanks for the support.
