### ISSUE TITLE
Plaidml and OpenAI

### ISSUE THREAD

**Issue by xxshazxx** [plaidml/plaidml#295]
Hi, is it possible to run OpenAI baseline or stable-baseline with Plaidml ?
They are both leveraging Tensorflow.
If so, how?

Thanks a lot

**Comment by brianretford** [comment]
We do actually support tensorflow via nGraph but it's very somewhat to very complicated to setup right now, depending on your comfort with building things from source. We can provide instructions though

**Comment by xxshazxx** [comment]
Great. If you could share the instructions I would love to try.
Thanks a lot

**Comment by brianretford** [comment]
There are instructions actually in `docs/building.md`, that said there will be a pip release in june of ngraph that will support plaid with no building by hand.

**Comment by IIIBlueberry** [comment]
Is there any guide to build ngraph on windows? or do i need to use anaconda?

**Comment by earhart** [comment]
I don't think anyone's tried nGraph with PlaidML on Windows.

I talked to one of the nGraph build people.  The commands they're using for Windows are:
```
cmake ../ngraph -DNGRAPH_CPU_ENABLE=FALSE  -G "Visual Studio 15 2017 Win64"
cmake --build . --config Release
.\src\ngraph\Release\unit-test
```

They recommend replacing `-DNGRAPH_CPU_ENABLE=FALSE` with `-DNGRAPH_DEX_ONLY=TRUE`.

I'm not sure whether the nGraph/PlaidML integration builds cleanly these days, especially on Windows -- it hasn't been part of anyone's CI (so there's been a bit of bitrot that I'm currently cleaning out), and back when I wrote it, nGraph didn't really support Windows well at all.

**Comment by IIIBlueberry** [comment]
> 
> 
> I don't think anyone's tried nGraph with PlaidML on Windows.
> 
> I talked to one of the nGraph build people. The commands they're using for Windows are:
> 
> ```
> cmake ../ngraph -DNGRAPH_CPU_ENABLE=FALSE  -G "Visual Studio 15 2017 Win64"
> cmake --build . --config Release
> .\src\ngraph\Release\unit-test
> ```
> 
> They recommend replacing `-DNGRAPH_CPU_ENABLE=FALSE` with `-DNGRAPH_DEX_ONLY=TRUE`.
> 
> I'm not sure whether the nGraph/PlaidML integration builds cleanly these days, especially on Windows -- it hasn't been part of anyone's CI (so there's been a bit of bitrot that I'm currently cleaning out), and back when I wrote it, nGraph didn't really support Windows well at all.

so after i build the ngraph i have to add the '.\src\ngraph\Release\unit-test'(which only have .dll and .lib file) to my windows PATH? and i installed ngraph> 
https://i.imgur.com/x5ZoYjK.png
.\src\ngraph\Release\unit-test

**Comment by IIIBlueberry** [comment]
> u



> 
> 
> I don't think anyone's tried nGraph with PlaidML on Windows.
> 
> I talked to one of the nGraph build people. The commands they're using for Windows are:
> 
> ```
> cmake ../ngraph -DNGRAPH_CPU_ENABLE=FALSE  -G "Visual Studio 15 2017 Win64"
> cmake --build . --config Release
> .\src\ngraph\Release\unit-test
> ```
> 
> They recommend replacing `-DNGRAPH_CPU_ENABLE=FALSE` with `-DNGRAPH_DEX_ONLY=TRUE`.
> 
> I'm not sure whether the nGraph/PlaidML integration builds cleanly these days, especially on Windows -- it hasn't been part of anyone's CI (so there's been a bit of bitrot that I'm currently cleaning out), and back when I wrote it, nGraph didn't really support Windows well at all.

tried build ngraph for windows with this commands 
```
cmake ../ngraph -DCMAKE_INSTALL_PREFIX=ngraph_plaidml_dist -DNGRAPH_CPU_ENABLE=FALSE -G "Visual Studio 16 2019" -A X64
cmake --build . --config Release
```
but i got a error https://pastebin.com/1mC3P5Ng

**Comment by earhart** [comment]
You'll need to add `-DNGRAPH_PLAIDML_ENABLE=ON` to get the PlaidML backend built.
The errors you ran into are with the nGraph build; they could possibly be caused by using VS 2019 instead of 2017, but I'm not sure.  I'm sure the nGraph team would love any patches you might have to get things working with VS 2019 -- or you could try using VS 2017.

**Comment by IIIBlueberry** [comment]
> 
> 
> You'll need to add `-DNGRAPH_PLAIDML_ENABLE=ON` to get the PlaidML backend built.
> The errors you ran into are with the nGraph build; they could possibly be caused by using VS 2019 instead of 2017, but I'm not sure. I'm sure the nGraph team would love any patches you might have to get things working with VS 2019 -- or you could try using VS 2017.

kinda a late post but 1/2 month ago i tried to build ngraph with plaidml with VS2017, but cmake failed to generate vs2017 solution. however standard ngraph does
