### ISSUE TITLE
RuntimeError: CuDNN RNNs are only available with the TensorFlow backend

### ISSUE THREAD

**Issue by xxshazxx** [plaidml/plaidml#298]
Hello,

I have two GPU in my system , AMD and nVIDIA. I'm using CUDA with tensorflow-gpu and I would like to use plaid-ml for the AMD card.
I've changed the code to run plaidml but I get the message:
RuntimeError: CuDNN RNNs are only available with the TensorFlow backend

Any hint on how to solve it?
Thanks

**Comment by aviallon** [comment]
Well you can't use NVIDIA CuDNN for AMD GPU... It makes sense I guess :sweat_smile:

**Comment by xxshazxx** [comment]
Aviallon, I'm asking support to understand how to let run Plaidml without having the CuDNN error message.
I'm not trying to run CuDNN on AMD. :)

**Comment by brianretford** [comment]
Hey @xxshazxx can you provide the exact details of what you're trying to do? Are you running through keras? We don't officially support tensorflow yet

**Comment by xxshazxx** [comment]
Hi. I would like just to run PlaidML on AMD GPU in a system where NVIDIA is present and running with CUDA.
I would like to be able to run PlaidML on AMD and Tensorflow-gpu on NVIDIA. 
Yes, I'm looking to understand how to obviate the need of cuDNN in an environemnt where there is also CUDA installed.
I'm using anaconda if that could help in separating the two env.

thank you so much for the help, really appreciated.

**Comment by brianretford** [comment]
Well, not knowing where that error is coming from, can you provide the exact system / env config and the code you are trying to run? It's hard to diagnose things w/o a minimal reproduction

**Comment by brianretford** [comment]
Closing as invalid pending a clearer reproduction
