### ISSUE TITLE
Latest master has dependency on python3 in __init__.py

### ISSUE THREAD

**Issue by chrisbarrera** [plaidml/plaidml#302]
I compiled the latest master and running tests on various keras scripts fails under python2 with this error:
$ python trivial_model_test.py 
Traceback (most recent call last):
  File "trivial_model_test.py", line 4, in <module>
    import plaidml.keras
  File "/anaconda2/lib/python2.7/site-packages/plaidml/__init__.py", line 1320
    def __init__(self, ctx, dtype, *args, layout=None):

The error is pointing to "layout=None" which follows *args and I believe this semantic (keyword argument following *args which is a keyword-only argument) is only supported under python 3.x.

The code works if I install anaconda3 and use that instead of anaconda2. Which I am fine to continue doing.

**Comment by aviallon** [comment]
I guess this is normal since Python 2.7 is officially deprecated and all support will end really soon now.

**Comment by brianretford** [comment]
This is definitely unintentional and is due to a bit of a CI gap. We'll address this in 0.6.0

**Comment by brianretford** [comment]
Fixed in 0.6.0

**Comment by alguru** [comment]
@brianretford It doesn't seem fixed in 0.6.0

I ran 
> pip install -U plaidml plaidml-keras

This ends with 

> Successfully installed plaidml-0.6.0 plaidml-keras-0.6.0


When I run 

> plaidml-setup


I get 

> Traceback (most recent call last):
>   File "/anaconda2/bin/plaidml-setup", line 7, in <module>
>     from plaidml.plaidml_setup import main
>   File "/anaconda2/lib/python2.7/site-packages/plaidml/__init__.py", line 1320
>     def __init__(self, ctx, dtype, *args, layout=None):


I'm running macOS Mojave 10.14.4, using python 2.7 under anaconda. Any suggestions?
