### ISSUE TITLE
how to set gpu.json.j2 for Nvidia GPU for USE_STRIPE=1 ?

### ISSUE THREAD

**Issue by chrisfan100** [plaidml/plaidml#304]

**Comment by chrisfan100** [comment]
Hi ,
I try to test USE_STRIPE=1 on my NV RTX2070 using a convolution script. But it's much slower than USE_STRIPE=0.
According the dumped ocl kernel, I found it does not use share memory when USE_STRIPE=1.
It seems I should set tile\targets\gpu\gpu.json.j2 according my GPU. But I don't know how to set it to turn on share memory.
Could you give me an example gpu.json.j2 for NV GPU which have good performance?

Thanks,
Chris

**Comment by brianretford** [comment]
Hey Chris,

Thanks for trying out stripe. Right now that file should really be named 'intel_gen9_gpu.json.j2'. We don't have an nvidia optimized one done yet. Creating them is a bit complicated but it's something we're actively documenting.

@jbruestle might have more to offer

**Comment by brianretford** [comment]
Yao is working on NVidia support for stripe

**Comment by brianretford** [comment]
There are now Nvidia stripe configs checked in. For inference workloads we find it is up to 50% faster than the old plaidml. Feel free to try and it provide feedback
