### ISSUE TITLE
implementation of kervolution layer

### ISSUE THREAD

**Issue by iperov** [plaidml/plaidml#307]
@SleepProgger 
can you please implement subj
links:
https://www.reddit.com/r/MachineLearning/comments/bkil6g/r_kervolutional_neural_networks_cvpr19_oral/?sort=new

tf impl:
https://github.com/CyberZHG/tf-keras-kervolution-2d/blob/master/tf_keras_kervolution_2d/layers.py

problem is tf impl via tf.extract_image_patches is extremelly slow.
it would be good to implement it in low level of plaidml

**Comment by brianretford** [comment]
the extract image patches issues is separate right?

**Comment by iperov** [comment]
no, extract image patches works fine :)

nevermind, this is not important
