### ISSUE TITLE
Implement Data Parallelism

### ISSUE THREAD

**Issue by brianretford** [plaidml/plaidml#31]
PlaidML currently aborts when multiple devices are selected. Initial support for multiple devices will be implemented through a data parallel approach, using something similar to MXNet's strategy.

Possible Implementation Strategy:
  * Add a setting for parallelism strategy, with two options [None, Data]. None matches current behavior
  * Modify the program.cc in local_platform to take a list of devices and the parallelism strategy.
  * If data parallelism is enabled, do the work necessary to build multiple kernels and split work amongst them
  * Need to figure out how to shoehorn this into keras - splitting batches into parts and rejoining seems like the most reasonable approach

**Comment by jbruestle** [comment]
This probably belongs on the development roadmap, not as a ticket.
