### ISSUE TITLE
Fit generator

### ISSUE THREAD

**Issue by thienquang199x** [plaidml/plaidml#314]
I have error "plaidml.exceptions.Unknown: Datatype for index input to gather must be INT32" when I training model with fit_generator . Can you help me fix it ?

**Comment by srmykola** [comment]
> I have error "plaidml.exceptions.Unknown: Datatype for index input to gather must be INT32" when I training model with fit_generator . Can you help me fix it ?

Hi. Got into the same issue. Any luck with solving?
