### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by jverce** [plaidml/plaidml#317]
CI process has been broken for this project for several months (see [this example](https://travis-ci.org/plaidml/plaidml/builds/536153067?utm_source=github_status&utm_medium=notification)), limiting the ability to quickly check whether a PR is correct and doesn't break existing functionality.

**Comment by jverce** [comment]
I would like to work on this unless there's any objection or there's someone addressing it already.

**Comment by brianretford** [comment]
We'd love to have some help! We use buildkite internally and will be working on better procedures to ensure it doesn't break in the future.

**Comment by jverce** [comment]
Awesome! BTW, is there any means of communication for contributors to interact besides Github?

**Comment by brianretford** [comment]
Yes! We are launching a public slack channel for ngraph & plaid - see the link at the bottom of #280 - we're still sorting some things out so it's a soft launch for now, but we're all there.

**Comment by jverce** [comment]
Submitted https://github.com/plaidml/plaidml/pull/324, which gets the Travis build going.
We're still getting an error from Travis because of a build timeout, so I'll work on some caching mechanism (like a pre-built image or package caching) to improve the build time.

**Comment by brianretford** [comment]
Public repo now uses buildkite.
