### ISSUE TITLE
Support Multiple Devices

### ISSUE THREAD

**Issue by brianretford** [plaidml/plaidml#32]
PlaidML currently requires exactly one selected device.

We've considered multiple approaches to multi-device support:
  * [Data Parallelism] (Multiple copies of the function graph on each device, coordinate weight updates)
  * Model Parallelism (Split up the graph across devices)
  * Kernel Parallelism (Effectively splitting up the Tile Op index space)

Alternatively, we could implement backends for frameworks that have solid multi-device support, such as:
  * MXNet
  * TensorFlow

This is a parent issue tracking implementation of all 3. We'll start with data parallelism and move on to others as warranted, with separate issues for each.

**Comment by jverce** [comment]
Hi, any updates regarding MXNet integration?

**Comment by brianretford** [comment]
We will support MXNet through our upcoming ngraph integreation. It's a bit of a convoluted loop, but it's what we're doing. Honestly supporting ngraph wouldn't be too hard (ngraph support took us 1 engineer month), though there's some refactoring we would need to do. Why's it important? MultiGPU support?

**Comment by jverce** [comment]
Hi @brianretford 
There's an [ongoing issue](https://github.com/apache/incubator-mxnet/issues/621) with MXNet support of GPU brands other than NVIDIA.
Didn't actually research much about PlaidML (though I plan to) but it sounds like it could be a good fit to finally achieve that support.

**Comment by leedrake5** [comment]
Hi, 

I'm curious if there are any updates? I suspect data parallelism is the most useful, particularly as it addresses RAM availability for more complicated models. 

As always, thanks for your work on this project.
