### ISSUE TITLE
CLA for contributors

### ISSUE THREAD

**Issue by boxerab** [plaidml/plaidml#33]
You guys might want to consider setting up a contributor license agreement for third party contributions.

For example:

[CLAHub](https://www.clahub.com/)

**Comment by choongng** [comment]
Hi Aaron, we are! We're getting a CLA bot set up using the Apache documents.

**Comment by brianretford** [comment]
Done.

**Comment by boxerab** [comment]
Thanks, guys.  Really interested to see how this project evolves.
