### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) 

### ISSUE THREAD

**Issue by leedrake5** [plaidml/plaidml#334]
I've found myself unable to use plaidml - and I don't know where the problem is. Using Anaconda Python 3.6.4 and accessing it through R 3.6.0

`library("keras"); library("sessioninfo")
use_python("/Users/<user.name>/anaconda3/bin/python")
use_backend(backend = "plaidml")`

When I do this I get the following error:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'

Detailed traceback: 
  File "/Users/lee/anaconda3/lib/python3.6/site-packages/plaidml/keras/__init__.py", line 74, in install_backend
    from keras.utils import conv_utils
  File "/Users/lee/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 5, in <module>
    from . import applications
  File "/Users/lee/anaconda3/lib/python3.6/site-packages/keras/applications/__init__.py", line 13, in <module>
    keras_applications.set_keras_submodules(`

Not sure where to start - this has worked for months now, and then this.

**Comment by leedrake5** [comment]
The solution was to remove Keras completely

`pip uninstall keras`
And reinstall from conda forge

`sudo conda install -c conda-forge keras tensorflow`

Then plaidml loaded normally.

**Comment by dgkutnic** [comment]
It seems like you've solved your own issue, so I'm closing this for now. Please re-open this if you are still experiencing issues with loading PlaidML.

Thanks for using PlaidML!
