### ISSUE TITLE
could tile code be debuged?

### ISSUE THREAD

**Issue by preFiredman** [plaidml/plaidml#335]
I have wrote some tile code in C++ project. when it was successfully compiled, there is no kernels dumped. When I debug the project line to line , it goes into the compile() function, making it hard to find if i have made any mistakes in the tile code. 
so, how could I check the mistakes in my tile code?

**Comment by brianretford** [comment]
Tile code is unfortunately quite hard to debug. We're going to be porting the entire project to use MLIR at which point we hope debugging things will be easier, as Denise noted we are also working on more idiomatic ways to program from c++ and other languages.

If you can post your code here or on the slack channel we'll happily help you debug it.
