### ISSUE TITLE
could you guys provide more tile code examples or samples for us to understand the special program?

### ISSUE THREAD

**Issue by preFiredman** [plaidml/plaidml#337]
since you guys made the "tile code" style, why don't you guys offer more tile code samples or more delicate specifications on how to write tile codes? your "write tile code" documentation is not that easy to understand.
also, I find it hard to understand when reading your "tile code templates" in your op.py file.

**Comment by dgkutnic** [comment]
Hi @preFiredman,

We're actively working on the programmability of PlaidML to improve our developer experience and make it easier for new members of our community to get started with PlaidML.

If you have any suggestions, or you want to learn more about our strategic direction, [join us on Slack!](https://join.slack.com/t/ngraph/shared_invite/enQtNjY1Njk4OTczMzEyLWYxOWM2OGJhYjgwYzQ4MTZkODkwYjM3MjRkOTQ3MzMwNmQ2NjRkZjkxOWRlOGFjMjY1ZTdmOWQ5Mzc3NjA0OTQ)
