### ISSUE TITLE
Add debug output for selecting backends

### ISSUE THREAD

**Issue by KOLANICH** [plaidml/plaidml#342]
For example GPU is not selected on my machine IDK why. I have done some experiments with `experimental.json` and haven't managed to get the GPU selected. I even suspect that regex matching may have been broken. So we need a debug output showing against which strings regexs are matched, results of matching and the moments when the device is discarded.

**Comment by dgkutnic** [comment]
We're actively working to improve the debug messages within `plaidml-setup`.

**Comment by brianretford** [comment]
Can you provide a `clinfo` dump? We can make sure your card gets enabled if it's not working. We're targeting a new config system in 0.7.0 which will resolve these kinds of problems

**Comment by KOLANICH** [comment]
>Can you provide a clinfo dump?

In the head of https://github.com/plaidml/plaidml/issues/344

**Comment by dgkutnic** [comment]
We've added debug info to `plaidml-setup` in plaidml 0.6.4+
You can set the environment variable `PLAIDML_VERBOSE` to 1 to enable the debug messages within `plaidml-setup`.
Closing this issue for now -- please ask us to re-open this if you are still experiencing issues.

**Comment by KOLANICH** [comment]
It still doesn't explain why doesn't it see my device. I have set the regexes to `.+` and I don't see it and I neither see any log messages about it.
