### ISSUE TITLE
Add verbose logging through an environment variable

### ISSUE THREAD

**Issue by dgkutnic** [plaidml/plaidml#346]
We've had several cases of issues that required verbose logging to debug. Currently, PlaidML has support for verbose logging, but it must be set using a function that is called _after_ the PlaidML binaries are loaded. This makes it difficult to debug exceptions that occur in the following cases:

- Developers who want to set verbose logging without having to modify their source code or PlaidML binaries
- Developers who are debugging `plaidml-setup` issues that occur _during_ the binary loading process
- Developers who are debugging issues between nGraph <-> PlaidML

In all of these cases, verbose logging could be easily enabled through an environment variable that the user sets in their shell before setting up PlaidML. We should add support and documentation for this.

**Comment by earhart** [comment]
IMHO -- the entire configuration story needs to be cleaned up and simplified; the current implementation is a bit ad-hoc.

What I'd like to see is something like a platform-native configuration, coupled with environment variable overrides, done in a way that integrates well with the various frameworks and apps that use PlaidML.

**Comment by dgkutnic** [comment]
@earhart 
@mwyi is working on a restructure of our configuration process. I will be working with him to ensure that both of our changes work together harmoniously for our community members as well as internal developers, among other audiences.

**Comment by earhart** [comment]
SGTM :-)

**Comment by flaub** [comment]
FYI I plan to eventually make all the configs be built into binaries with an environment variable to allow users to specify their own. We currently do this with the stripe config, but I think our next release ought to use the same strategy for legacy configs. Is this what @mwyi is working on?

**Comment by dgkutnic** [comment]
Yes, that is what @mwyi is working on for legacy configs and what I had been planning to do for verbose logging. I don't mean to step on any toes here - shall Mike and I keep working on this or did you want to own it?

**Comment by flaub** [comment]
Nope sounds good, I wasn't aware of that work going on. I haven't gotten around to it yet so carry on :)

**Comment by brianretford** [comment]
@dgkutnic you marked this needs docs / verify - so there is now an env variable for debug logging?

**Comment by dgkutnic** [comment]
Yes and no - the environment variable `PLAIDML_VERBOSE` is currently being used to print debug messages during `plaidml-setup`, but that variable is not setting `plaidml._internal_set_vlog` in any way. I'll make that change now and add documentation for `PLAIDML_VERBOSE`.

**Comment by dgkutnic** [comment]
This has been enabled for a while - closing now.
