### ISSUE TITLE
Can't work correctly with TensorFlow

### ISSUE THREAD

**Issue by damamasss** [plaidml/plaidml#349]
When I install and enable PlaidML, my programm cant work correctly with TensorFlow.

Programm good work on CPU
Checked: When installed old NVIDIA card - Tensorflow tell that CUDA very old and slowly compute on CPU

I see:
> AttributeError: 'TensorShape' object has no attribute 'dtype'

HW:
CPU i5-2300
RAM 10G
GPU AMD RX580

SW:
OS: Win 10 x64
CLI: Anaconda (installed on days from official site; work here, created custom enviroments)

Python: 3.7.3
PIP 19.0.3
Conda 4.6.14

> pip list:
```
...
keras 2.2.4
keras-applications 1.0.8
keras-preprocessing 1.1.0
opencv-python 4.1.0.25
tensorflow 1.14.0
plaidml 0.6.0
plaidml-keras 0.6.0
```

> conda list
```
...
keras 2.2.4 pypi_0 pypi
keras-applications 1.0.8 pypi_0 pypi
keras-preprocessing 1.1.0 pypi_0 pypi
opencv-python 4.1.0.25 pypi_0 pypi
tensorflow 1.14.0 pypi_0 pypi
plaidml 0.6.0 pypi_0 pypi
plaidml-keras 0.6.0 pypi_0 pypi
```

_Now Tensorflow not GPU version, because create Anaconda enviroment when was inserted AMD card and tensorflow-gpu requires DLLs from cudatoolkit (installed on this PC earlier, but tensorflow not see this). But when using tensorflow-gpu - same error_

* I tried Tensorfow: 1.13, 1.14, 2.0beta, nighty - all same
* Tried install Tensorflow-GPU - install NVIDIA card, install CUDA, and then install Tensorflow-GPU - similar problem
* Try install Keras, Tensorflow-GPU, OpenCV and via PIP and via CONDA (and aslo tried install and create enviroment for Tensorflow, PlaidML) - all same

> plaidbench keras mobilenet
```
Running 1024 examples with mobilenet, batch size 1, on backend plaid
INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
Compiling network... Warming up... Running...
Example finished, elapsed: 6.994s (compile), 8.510s (execution)

-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS
-----------------------------------------------------------------------------------------
mobilenet            8.31 ms                   1.56 ms / 642.15 fps
Correctness: PASS, max_error: 1.8053706298815086e-05, max_abs_error: 9.760260581970215e-07, fail_ratio: 0.0
```

Traceback
```
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    gen_flow_lr = fnet( inputs_frames, reuse=False)
  File "C:\Users\Optimus\Desktop\sr_GAN_vid\TecoGAN-master\lib\frvsr.py", line 27, in fnet
    net = down_block( fnet_input, 32, scope = 'encoder_1')
  File "C:\Users\Optimus\Desktop\sr_GAN_vid\TecoGAN-master\lib\frvsr.py", line 8, in down_block
    net = lrelu(net, 0.2)
  File "C:\Users\Optimus\Desktop\sr_GAN_vid\TecoGAN-master\lib\ops.py", line 95, in lrelu
    return keras.layers.LeakyReLU(alpha=alpha).call(inputs)
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\keras\layers\advanced_activations.py", line 48, in call
    return K.relu(inputs, alpha=self.alpha)
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\plaidml\tile.py", line 255, in function
    operation = cls(*args, **kwargs)
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\plaidml\op.py", line 2272, in __init__
    super(Relu, self).__init__(code, inputs, [('Y', x.shape)])
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\plaidml\tile.py", line 213, in __init__
    (output_name, Value.for_op(shape, self, output_name)) for output_name, shape in outputs
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\plaidml\tile.py", line 213, in <listcomp>
    (output_name, Value.for_op(shape, self, output_name)) for output_name, shape in outputs
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\plaidml\tile.py", line 715, in for_op
    return Value(shape, None, Source(operation, output), name)
  File "C:\Users\Optimus\Anaconda3\envs\envy\lib\site-packages\plaidml\tile.py", line 683, in __init__
    shape = Shape(shape.dtype, tuple(shape.dims))
AttributeError: 'TensorShape' object has no attribute 'dtype'
```

**Comment by dgkutnic** [comment]
To use PlaidML with TensorFlow, you would want to install [nGraph](https://github.com/tensorflow/ngraph-bridge), which interfaces directly with TensorFlow and produces an output that PlaidML recognizes. We're working together with the nGraph team to improve both the installation process and documentation behind the TensorFlow <-> nGraph <-> PlaidML stack.

**Comment by damamasss** [comment]
Now I cant use PlaidML with TensorFlow?
Or where and when I can find docs for right config TensorFlow <-> nGraph <-> PlaidML

**Comment by brianretford** [comment]
Our BUILDI?NG.md doc should contain sufficient instructions, would love reports on their inadequacy. The next nGraph release will have plaidML wheels so you shouldn't need to build anything
