### ISSUE TITLE
Add contributors file

### ISSUE THREAD

**Issue by ikhlestov** [plaidml/plaidml#35]
It will be really great if you will add some [contributors file](https://github.com/blog/1184-contributing-guidelines) where you will describe something like this:
- What packages required to contribute
- What steps should be executed after new features added:
  - Test running and expected results
  - Building source code. Yes I know that such instructions already exists in installation but maybe there should be added some flags for enabling debug features.
- General requirements to follow during contributing:
  - Test coverage should not decrease
  - Tests should not fail
  - Follow PEP8 or any other guide
  - Use linter or anything else

I think with such file it will be easier to join you community and boost the development.

**Comment by brianretford** [comment]
Great suggestion. We'll get that done today.

**Comment by brianretford** [comment]
Sorry for the delay, fixed in #62
