### ISSUE TITLE
how does plaidml optimize kernels?

### ISSUE THREAD

**Issue by preFiredman** [plaidml/plaidml#353]
the core innovation of plaidML is auto kernel optimization. how does it accomplish it ?
which part of code should I focus on if I wanna to go further to study on the kernel optimization func ?
I have joined your slack talk team, what could I get from it ?
thanks so much ! !

**Comment by dgkutnic** [comment]
For a technical overview of PlaidML's Stripe IR (which performs most of our optimizations), you can take a look at @tzerrell and @jbruestle's [Stripe Paper](https://arxiv.org/pdf/1903.06498.pdf).

Jeremy also wrote [an article](https://www.intel.ai/automatic-kernel-generation-in-plaidml/) ~1 year ago addressing automatic kernel generation, but PlaidML's architecture is rapidly changing and this article contains information that is outdated.

Many of our current optimizations live within the `tile/lang`, `tile/stripe`, and `tile/codegen` directories. Feel free to poke around and  post any specific code questions either here or on Slack. Slack is better when you want a more immediate and interactive answer to short questions, whereas GitHub is a good medium for issues that you'd like to refer back to.

We're working on building a more complete set of documentation about PlaidML, including blog posts, demos, and webinars. We're already planning content about PlaidML's kernel optimizations, too. I'll link you to those resources as they become available.
