### ISSUE TITLE
The git-repository for 'toolchain' in WORKSPACE is out of date. 

### ISSUE THREAD

**Issue by SingularMaster** [plaidml/plaidml#362]
git-repository of 'toolchain' in WORKSPACE is:

```
git_repository(
     name = "toolchain",  
     commit = "a487bf9f2cc4edc47d376606abaaf29d85fffcd8",  
     remote = "https://github.com/plaidml/toolchain",  
 )
```

The commit ID "a487bf9f2cc4edc47d376606abaaf29d85fffcd8" is for toolchain committed on Dec 28, 2018. And many rules can't be found when building Plaidml with this ID. To update it with  the latest 'toolchain' commit ID can resolve this problem.

But I am not sure that if this is a mistake or just because of my misunderstanding. Could anybody help verify this issue?

**Comment by brianretford** [comment]
We have an update for this but we've also integrated MLIR recently and we need to modify the public build config a bit more. Will get this addressed.

**Comment by flaub** [comment]
I think this was fixed awhile back. Please re-open if you still have issues.
