### ISSUE TITLE
broadcast error in elementwise operations

### ISSUE THREAD

**Issue by preFiredman** [plaidml/plaidml#364]
I am trying to emplyment 'tensor adds' function utilizing plaidML. your tile code tutorial said the binary elementwise operation will automatically doing  some broadcast work when A and B has different shapes. Here is my case(supposing A and B are nchw tensors):
A[2, 3, 3, 5] B[1, 3, 1, 1]
`	function (BIAS[N, CH, H, W], C[NC, CC, HC, WC]) -> (O) {
OBIAS[n, c, h, w: N, CH, H, W] = BIAS[n, c, h, w] * 1;
OC[n, c, h, w: NC, CC, HC, WC] = C[n, c, h, w] *  1;
O = OC + OBIAS;
	}`
it returns:

>  what():  syntax error, unexpected ID

**Comment by tzerrell** [comment]
It doesn't look to me like you need `OBIAS` or `OC`, and eliminating them gives you a function that runs:
```
function (BIAS[N, CH, H, W], C[NC, CC, HC, WC]) -> (O) {
    O = C + BIAS;
}
```
If you want too set `OBIAS = BIAS` and `OC = C`, you can do that without specifying indexes:
```
function (BIAS[N, CH, H, W], C[NC, CC, HC, WC]) -> (O) {
    OBIAS = BIAS;
    OC = C;
    O = OC + OBIAS;
}
```
If you want indexes available (e.g. to reorder dimensions) you need to write the operation as a contraction. For something like a simple rearrangement which doesn't need aggregation, you can use the `=` aggregation operation to use the "assignment" aggregation, which indicates that no aggregations should be performed. So e.g.
```
function (BIAS[N, CH, H, W], C[NC, CC, HC, WC]) -> (O) {
    OBIAS[n, h, w, c: N, H, W, CH] = =(BIAS[n, c, h, w]);
    OC[n, h, w, c: NC, HC, WC, CC] = =(C[n, c, h, w]);
    O = OC + OBIAS;
}
```
