### ISSUE TITLE
Explain the meanings of the settings in the json file

### ISSUE THREAD

**Issue by jinz2014** [plaidml/plaidml#367]
Could you please explain the meaning of each name in the settings ?  For example, what does the "max_mem" mean and why is it 7300 ?   Do these values impact the compiler flow (scheduling, code generation, etc) ? 

Thanks
        
"settings": {
          "threads": 64,
          "vec_size": 1,
          "mem_width": 256,
          "max_mem": 7300,
          "max_regs": 4000,
          "goal_groups": 1,
          "goal_flops_per_byte": 50,
          "disable_mad": true,
          "stripe_config": "intel_gen9_opencl"

**Comment by brianretford** [comment]
Hey @jinz2014 sadly the best way to understand these options is by reading the code in read_plan.cc, write_plan.cc and tile_opt.cc .  They are all parameters to various optimization functions in that code.

We would happily document them but we're replacing that system with a new IR and compiler stack that is much more configurable. Our documentation efforts are focused on that (currently in the 'stripe') directory and enabled by setting USE_STRIPE=1
