### ISSUE TITLE
image_dim_ordering

### ISSUE THREAD

**Issue by jinz2014** [plaidml/plaidml#368]
I tried to run an example using the plaidml backend.  

AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'
AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'

Thank you for your answer.

**Comment by dgkutnic** [comment]
Hi @jinz2014,
Could you provide us with the code you were running which resulted in these errors?

**Comment by jinz2014** [comment]
import os
import time
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
from keras import backend as K
K.set_image_dim_ordering("th")

I hope my example is correct. Thanks.

**Comment by cnamrata15** [comment]
image_dim_ordering has been now renamed to image_data_format as per [https://github.com/keras-team/keras/wiki/Keras-2.0-release-notes]
