### ISSUE TITLE
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".

### ISSUE THREAD

**Issue by Duddino** [plaidml/plaidml#370]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts\plaidml-setup.exe\__main__.py", line 5, in <module>
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\plaidml\__init__.py", line 50, in <module>
    import plaidml.settings
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\plaidml\settings.py", line 33, in <module>
    _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\plaidml\settings.py", line 30, in _setup_config
    'Could not find PlaidML configuration file: "{}".'.format(filename))
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".

**Comment by dgkutnic** [comment]
Disclaimer: We're actively working to improve the setup experience and documentation around it. We're sorry you were stuck on this. For now, here's some instructions to get you back on track.

 1. Find out where plaidml-setup was installed. I know you're on Windows, so this is probably a bit different than the install path for Linux. On Linux, this is some variant of `/usr/local/bin` or a path to your virtual environment. The prefix of this path (i.e. `/usr/local`) is important to note for the next step.
 2. Find the plaidml `share` directory. It's within the same prefix as plaidml-setup, i.e. `/usr/local/share/plaidml`.
 3. Within the plaidml `share` directory, there should be a few files: at a minimum, `config.json` and `experimental.json` should be in there. If they're not in there, you can copy [the files here](https://github.com/plaidml/plaidml/tree/master/plaidml/configs) to your plaidml `share` directory.

After copying those json files over, you should be able to run `plaidml-setup` with no issue.

**Comment by Duddino** [comment]
I added those files and nothing changed. After looking at plaidml-setup.py, I noticed the script was trying to add experimental.json and config.json to the environment variables, but somehow it was failing to load those. I added them manually and now the error has changed:
File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\plaidml\__init__.py", line 168, in load_library
    'Could not find PlaidML library file: "{}".'.format(libname))
plaidml.exceptions.PlaidMLError: Could not find PlaidML library file: "plaidml.dll".

**Comment by Duddino** [comment]
I managed to change the exception again. Now it is 
  File "c:\users\andre\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\Scripts\plaidml-setup.exe\__main__.py", line 9, in <module>
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plaidml\plaidml_setup.py", line 50, in main
    devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plaidml\__init__.py", line 1073, in devices
    enumerator = _Enumerator(ctx)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plaidml\__init__.py", line 1031, in __init__
    ctx, ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plaidml\__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plaidml\library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: unable to resolve type:

**Comment by dgkutnic** [comment]
Alright, `plaidml.exceptions.Unknown: unable to resolve type:` is one we've seen before in #245 and #320. It's typically a result of PlaidML being unable to find any usable devices. Do you have OpenCL >= 1.2 installed and can you provide us with the output of `clinfo`?

**Comment by Duddino** [comment]
I figured it out at the end. It was because I installed python from the windows 10 app store and I guess the weird path (C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37) maybe needed permission or something.
As for the second error it was because I had manually set the system variables and then changed the python version (so plaidml thought I was using the old path but there was nothing in there)

**Comment by fogleman** [comment]
I'm hitting this issue on macOS with a clean install following the directions here:

https://github.com/plaidml/plaidml/blob/master/docs/install.md#macos

**Comment by AGenchev** [comment]
Hit this on Debian 10. plaidml-setup is found in ~/.local/bin/plaidml-setup
The files were already in `~/.local/share/plaidml`
no go for now

**Comment by gilemon** [comment]
I also had this problem but that's because I forgot to activate my virtualenv (e.g. source ./plaidml-venv/bin/activate)

**Comment by AGenchev** [comment]
@gilemon I don't use virtualenv, I do per user install, e.t.
`pip3 install  plaidml-keras  --user`
because I do not need to support different versions in virtualenvs. Until now, everyting (I mean other libraries) have worked this way hence I consider this error a plaidml bug.

**Comment by fogleman** [comment]
My virtualenv was activated, bug still occurred.

**Comment by AGenchev** [comment]
@fogleman Well, then I guess we should open a new bug ?

**Comment by asheetal** [comment]
> @fogleman Well, then I guess we should open a new bug ?
> BTW yesterday I managed to make it start by adding the path to it's library and tinkering with the source, but then it failed to compute it's test kernel (the setup does a little test) on my Intel UHD 620 GPU

What path did you change?  I am doing 
>>pip3 install plaidml-keras --user
and not  sure how to give the local install path to the plaidml-setup script

**Comment by houp** [comment]
As a workaround for MacOS 10.15 I found that setting
export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
export RUNFILES_DIR=/usr/local/share/plaidml
solved all the issues with missing experimental.json, settings.json and libplaidml.dylib files.

I have been able to successfully run plaidml-setup, save settings with it and further run one of the benchmarks (tried only this one): plaidbench keras vgg16

I've installed plaidml version 0.6.4 with pip3 today.

**Comment by asheetal** [comment]
I discovered that installing plaidml and other packages systemwide works using pip3.  Installing plaidml and related packages in userspace might need more options as @houp has mentioned.

**Comment by AGenchev** [comment]
@asheetal How did you install systemwide with pip3 ?
In my non-system-wide, 
libplaidml.so is installed in ~/.local/lib/libplaidml.so
 
as **root** I copy libplaidml.so to /usr/lib folder;
as **root** I copy the required json configs to /usr/share/plaidml folder.

**Comment by asheetal** [comment]
@AGenchev Seems like your pip3 is confused where to install site-packages in your case. I would delete .local completely or move it elsewhere temporarily. Check your python3 path if it knows the correct whereabouts of system site-packages. I did not have to manually copy libplaidml.so

**Comment by AGenchev** [comment]
O.K. installed as root it doesn't require me to copy files as root.

**Comment by leedrake5** [comment]
> export RUNFILES_DIR=/usr/local/share/plaidml



> As a workaround for MacOS 10.15 I found that setting
> export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
> export RUNFILES_DIR=/usr/local/share/plaidml
> solved all the issues with missing experimental.json, settings.json and libplaidml.dylib files.
> 
> I have been able to successfully run plaidml-setup, save settings with it and further run one of the benchmarks (tried only this one): plaidbench keras vgg16
> 
> I've installed plaidml version 0.6.4 with pip3 today.

I can confirm this works with the newest Mac operating system + pip3

**Comment by bikcrum** [comment]
Check this https://stackoverflow.com/a/60016869/6117565

**Comment by leedrake5** [comment]
> As a workaround for MacOS 10.15 I found that setting
> export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
> export RUNFILES_DIR=/usr/local/share/plaidml
> solved all the issues with missing experimental.json, settings.json and libplaidml.dylib files.
> 
> I have been able to successfully run plaidml-setup, save settings with it and further run one of the benchmarks (tried only this one): plaidbench keras vgg16
> 
> I've installed plaidml version 0.6.4 with pip3 today.

This worked for me too

**Comment by micchickenburger** [comment]
On macOS 10.15 Catalina, site-packages is not writable so pip installs packages to user directory.  This worked for me:

```
export PLAIDML_NATIVE_PATH=/Users/[username]/Library/Python/3.7/lib/libplaidml.dylib
export RUNFILES_DIR=/Users/[username]/Library/Python/3.7/share/plaidml
```

**Comment by aditya-88** [comment]
> I discovered that installing plaidml and other packages systemwide works using pip3. Installing plaidml and related packages in userspace might need more options as @houp has mentioned.

I confirm this worked on my MacBook Pro 2019 (AMD Radeon 555X).

Use:
`sudo pip3 install plaidml plaidml-keras plaidbench`
(for Python 3 installation)

**Comment by Brightchu** [comment]
> > export RUNFILES_DIR=/usr/local/share/plaidml
> 
> > As a workaround for MacOS 10.15 I found that setting
> > export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
> > export RUNFILES_DIR=/usr/local/share/plaidml
> > solved all the issues with missing experimental.json, settings.json and libplaidml.dylib files.
> > I have been able to successfully run plaidml-setup, save settings with it and further run one of the benchmarks (tried only this one): plaidbench keras vgg16
> > I've installed plaidml version 0.6.4 with pip3 today.
> 
> I can confirm this works with the newest Mac operating system + pip3, for setup at least. But I am still having problems actually using it.
> 
> ```
> import os
> os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
> from keras import backend as K
> ```
> 
> gives:
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/usr/local/lib/python3.7/site-packages/keras/**init**.py", line 3, in 
> > from . import utils
> > File "/usr/local/lib/python3.7/site-packages/keras/utils/**init**.py", line 6, in 
> > from . import conv_utils
> > File "/usr/local/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in 
> > from .. import backend as K
> > File "/usr/local/lib/python3.7/site-packages/keras/backend/**init**.py", line 93, in 
> > backend_module = importlib.import_module(_BACKEND)
> > File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "/usr/local/lib/python3.7/site-packages/plaidml/**init**.py", line 50, in 
> > import plaidml.settings
> > File "/usr/local/lib/python3.7/site-packages/plaidml/settings.py", line 33, in 
> > _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
> > File "/usr/local/lib/python3.7/site-packages/plaidml/settings.py", line 30, in _setup_config
> > 'Could not find PlaidML configuration file: "{}".'.format(filename))
> > plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".
> 
> EDIT
> 
> Reinstalling fixed it. Logging here for those who need to see all the steps
> 
> ```
> sudo pip3 uninstall plaidml-keras plaidbench
> sudo pip3 install plaidml-keras plaidbench
> export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
> export RUNFILES_DIR=/usr/local/share/plaidml
> plaidml-setup
> ```

GREAT JOB! solved my problem. thanks

**Comment by hyzgh** [comment]
As a workaround for ubuntu I found that setting:
export PLAIDML_NATIVE_PATH=~/.local/lib/libplaidml.so
export RUNFILES_DIR=~/.local/share/plaidml
solved all the issues with missing experimental.json, settings.json and libplaidml.so files.

**Comment by hemangjoshi37a** [comment]
> > export RUNFILES_DIR=/usr/local/share/plaidml
> 
> > As a workaround for MacOS 10.15 I found that setting
> > export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
> > export RUNFILES_DIR=/usr/local/share/plaidml
> > solved all the issues with missing experimental.json, settings.json and libplaidml.dylib files.
> > I have been able to successfully run plaidml-setup, save settings with it and further run one of the benchmarks (tried only this one): plaidbench keras vgg16
> > I've installed plaidml version 0.6.4 with pip3 today.
> 
> I can confirm this works with the newest Mac operating system + pip3, for setup at least. But I am still having problems actually using it.
> 
> ```
> import os
> os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
> from keras import backend as K
> ```
> 
> gives:
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/usr/local/lib/python3.7/site-packages/keras/**init**.py", line 3, in 
> > from . import utils
> > File "/usr/local/lib/python3.7/site-packages/keras/utils/**init**.py", line 6, in 
> > from . import conv_utils
> > File "/usr/local/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in 
> > from .. import backend as K
> > File "/usr/local/lib/python3.7/site-packages/keras/backend/**init**.py", line 93, in 
> > backend_module = importlib.import_module(_BACKEND)
> > File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "/usr/local/lib/python3.7/site-packages/plaidml/**init**.py", line 50, in 
> > import plaidml.settings
> > File "/usr/local/lib/python3.7/site-packages/plaidml/settings.py", line 33, in 
> > _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
> > File "/usr/local/lib/python3.7/site-packages/plaidml/settings.py", line 30, in _setup_config
> > 'Could not find PlaidML configuration file: "{}".'.format(filename))
> > plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".
> 
> EDIT
> 
> Reinstalling fixed it. Logging here for those who need to see all the steps
> 
> ```
> sudo pip3 uninstall plaidml-keras plaidbench
> sudo pip3 install plaidml-keras plaidbench
> export PLAIDML_NATIVE_PATH=/usr/local/lib/libplaidml.dylib
> export RUNFILES_DIR=/usr/local/share/plaidml
> plaidml-setup
> ```

What is the export location for windows 10?

**Comment by fritx** [comment]
> On macOS 10.15 Catalina, site-packages is not writable so pip installs packages to user directory. This worked for me:
> 
> ```
> export PLAIDML_NATIVE_PATH=/Users/[username]/Library/Python/3.7/lib/libplaidml.dylib
> export RUNFILES_DIR=/Users/[username]/Library/Python/3.7/share/plaidml
> ```

for me, I'm using things like conda environment, I have to change the path like, and it works for me:

```sh
# plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".
#370
# https://github.com/plaidml/plaidml/issues/370#issuecomment-596232790

export PLAIDML_NATIVE_PATH=/Users/fritx/miniforge3/envs/faceswap/lib/libplaidml.dylib
export RUNFILES_DIR=/Users/fritx/miniforge3/envs/faceswap/share/plaidml
```
