### ISSUE TITLE
Monitor turns off while training with a Radeon RX 590

### ISSUE THREAD

**Issue by Duddino** [plaidml/plaidml#371]
When I train a GAN, for the first ≃100 epochs it works fine, but suddendly the video card's fans start spinning on what I'm assuming it's the maximum speed and the monitor turns off. The model stop training and I have to shut the PC by pressing the power button. I'm not sure if it's an issue of my graphics card or with plaidml

EDIT: It seems to be a overheating problem. I ran a program called CPUID HWmonitor to check the temperature while training. After 100 epochs the gpu temperature was 83 °C (200w, 2463 RPM and 98% gpu usage) 
As soon as it reached 85 °C the screen stopped working

**Comment by brianretford** [comment]
It's hard to say exactly. It's basically a heat issue which I would say is a hardware issue or an OS issues. You could try lowering the batch size and see if that resolves the issue. You may be able to force a lower clock speed. It can't really be a plaidml problem though.
