### ISSUE TITLE
Keras backend function 'any'

### ISSUE THREAD

**Issue by jinz2014** [plaidml/plaidml#376]
The Keras backend function 'any' is not yet implemented in Plaid.  Is there an implementation available ?

Thanks

**Comment by dgkutnic** [comment]
We do not currently have `K.any` implemented in PlaidML _yet_. Someone's working on an implementation over in [PR 369](https://github.com/plaidml/plaidml/pull/369), but we'd like to see unit tests implemented before we merge this implementation into master. Does that sound like something you may be interested in contributing?

**Comment by Antetokounpo** [comment]
The PR got merged, so it's now implemented.
