### ISSUE TITLE
How to simplify the build flow.

### ISSUE THREAD

**Issue by JerryShih** [plaidml/plaidml#452]
I follow the document in https://github.com/plaidml/plaidml/blob/master/docs/building.md:

I need to use bazelisk to build the wheel.
bazelisk build //plaidml:wheel
And then use pip to install that wheel
pip install -U bazel-bin/plaidml/*.whl

In my experience(build tensorflow and pytorch), I could just use "python setup.py develop" to install the developing build. Then, I could just update the python code or compile the c++ code without call the pip again and again.

Is it a simple flow for developing plaidml?

**Comment by JerryShih** [comment]
@dgkutnic 
I try to add some debug info in plaidml tile module, and I use plaidbench to run with some nn models. I should do the following task:
```
1) update python or c++ code
2) call bazelisk build //plaidml:wheel //plaidml/keras:wheel
3) and then call pip to install these packages.
```

How could I skip the step 3?
When I use pytorch, I could build the develop version of pytorch using:
`python setup.py develop`
Then I don't need to install/uninstall the pytorch pip package again and again. I just need to update python code and c++ code, and compile them if necessary.

**Comment by flaub** [comment]
You can try: 

```
bazelisk run //plaidbench:bin -- <arguments to plaidbench go here>
```

That way you don't have to re-install wheels.

**Comment by dgkutnic** [comment]
Closing this because we've addressed how to use `bazelisk` for your use case instead of reinstalling wheels each time you change code. Please let us know if you have any more questions.
