### ISSUE TITLE
Float64 supported on Mac?

### ISSUE THREAD

**Issue by jw3267** [plaidml/plaidml#462]
System:
Mac Pro 2018, OSX Mojave 10.14.06, Radeon VII eGPU
python 3.7.4
Installed via pip,
plaidml-0.6.4-py2.py3-none-macosx_10_10_x86_64.whl
plaidml_keras-0.6.4-py2.py3-none-any.whl

Problem:
I set keras.backend.set_floatx("float64")
When I run model.fit(...), I get an error, listed below.
Does plaidml require something special or is it just not supported?

Error MSGs:

Metal:
Unknown: Unusable hardware type: fp64

OpenCL:
WARNING:plaidml:Failed to build program kernel_c10_sdk_20
W0829 12:27:51.678007 123145400958976 library.py:135] Failed to build program kernel_c10_sdk_20
WARNING:plaidml:Failed build log: Undeclared function '' called by function 'kernel_c10_sdk_20'

W0829 12:27:51.680746 123145400958976 library.py:135] Failed build log: Undeclared function '' called by function 'kernel_c10_sdk_20'

WARNING:plaidml:Code was: 
    1: #pragma OPENCL EXTENSION cl_khr_fp64 : enable
    2: // gid: 131072 1 1
    3: // lid: 256 1 1
    4: // Names: { i1, i2 }
    5: // Ranges: { 4096, 50 }
    6: // Out stride: { 50, 1 }
    7: // Elementwise input X_T74 shape: fp64(4096, 50):(50, 1):1600 KiB
    8: // Elementwise input X_T475 shape: fp64(4096, 1):(1, 1):32 KiB
    9: // Elementwise op: X_T476 = sub(X_T74, X_T475)
   10: // Elementwise op: X_T477 = exp(X_T476)
   11: // Tile size: { 8, 50 }
   12: // Contraction output var shape: fp64(4096, 50):(50, 1):1600 KiB
   13: // Computed true ops: 409600
   14: // Computed work groups: 512
   15: // Computed inner loops: 1
   16: // Computed shared mem: 0
   17: // Computed out regs: 4096
   18: // Computed mem read: 512
   19: // Computed mem write: 4096
   20: // Computed operations: 256
   21: // Computed rollups: 0
   22: // Computed threads used: 256
   23: // lwork = 256, 1, 1
   24: // gwork = 131072, 1, 1
   25: __kernel void kernel_c10_sdk_20(__global double* restrict  X_T477, __global const double* restrict  X_T74, __global const double* restrict  X_T475)
   26: {
   27:   int tid = get_local_id(0);
   28:   int i1_gid = (get_group_id(0) * 8);
   29:   int i2_tid = (tid % 32);
   30:   int i1_tid = ((tid / 32) % 8);
   31:   for (int i2_lid = 0; i2_lid < 2; i2_lid += 1)
   32:   {
   33:     int i2_cond = ((i2_lid < 1) || (i2_tid < 18));
   34:     if (i2_cond)
   35:     {
   36:       int i2 = ((32 * i2_lid) + i2_tid);
   37:       int gout_idx = ((50 * (i1_gid + i1_tid)) + i2);
   38:       double LX_T74 = X_T74[gout_idx];
   39:       double LX_T475 = X_T475[(i1_gid + i1_tid)];
   40:       double LX_T476 = (LX_T74 - LX_T475);
   41:       double LX_T477 = native_exp(LX_T476);
   42:       X_T477[gout_idx] = LX_T477;
   43:     }
   44:   }
   45: }

W0829 12:27:51.684996 123145400958976 library.py:135] Code was: 
    1: #pragma OPENCL EXTENSION cl_khr_fp64 : enable
    2: // gid: 131072 1 1
    3: // lid: 256 1 1
    4: // Names: { i1, i2 }
    5: // Ranges: { 4096, 50 }
    6: // Out stride: { 50, 1 }
    7: // Elementwise input X_T74 shape: fp64(4096, 50):(50, 1):1600 KiB
    8: // Elementwise input X_T475 shape: fp64(4096, 1):(1, 1):32 KiB
    9: // Elementwise op: X_T476 = sub(X_T74, X_T475)
   10: // Elementwise op: X_T477 = exp(X_T476)
   11: // Tile size: { 8, 50 }
   12: // Contraction output var shape: fp64(4096, 50):(50, 1):1600 KiB
   13: // Computed true ops: 409600
   14: // Computed work groups: 512
   15: // Computed inner loops: 1
   16: // Computed shared mem: 0
   17: // Computed out regs: 4096
   18: // Computed mem read: 512
   19: // Computed mem write: 4096
   20: // Computed operations: 256
   21: // Computed rollups: 0
   22: // Computed threads used: 256
   23: // lwork = 256, 1, 1
   24: // gwork = 131072, 1, 1
   25: __kernel void kernel_c10_sdk_20(__global double* restrict  X_T477, __global const double* restrict  X_T74, __global const double* restrict  X_T475)
   26: {
   27:   int tid = get_local_id(0);
   28:   int i1_gid = (get_group_id(0) * 8);
   29:   int i2_tid = (tid % 32);
   30:   int i1_tid = ((tid / 32) % 8);
   31:   for (int i2_lid = 0; i2_lid < 2; i2_lid += 1)
   32:   {
   33:     int i2_cond = ((i2_lid < 1) || (i2_tid < 18));
   34:     if (i2_cond)
   35:     {
   36:       int i2 = ((32 * i2_lid) + i2_tid);
   37:       int gout_idx = ((50 * (i1_gid + i1_tid)) + i2);
   38:       double LX_T74 = X_T74[gout_idx];
   39:       double LX_T475 = X_T475[(i1_gid + i1_tid)];
   40:       double LX_T476 = (LX_T74 - LX_T475);
   41:       double LX_T477 = native_exp(LX_T476);
   42:       X_T477[gout_idx] = LX_T477;
   43:     }
   44:   }
   45: }

WARNING:plaidml:Failed to build program kernel_c10_sdk_20: CL_BUILD_PROGRAM_FAILURE
W0829 12:27:51.688277 123145400958976 library.py:135] Failed to build program kernel_c10_sdk_20: CL_BUILD_PROGRAM_FAILURE
WARNING:plaidml:Failed to build program kernel_c10_sdk_20
W0829 12:27:51.689977 123145400958976 library.py:135] Failed to build program kernel_c10_sdk_20
WARNING:plaidml:Failed build log: Undeclared function '' called by function 'kernel_c10_sdk_20'

W0829 12:27:51.691578 123145400958976 library.py:135] Failed build log: Undeclared function '' called by function 'kernel_c10_sdk_20'

WARNING:plaidml:Code was: 
    1: #pragma OPENCL EXTENSION cl_khr_fp64 : enable
    2: // gid: 131072 1 1
    3: // lid: 256 1 1
    4: // Names: { i1, i2 }
    5: // Ranges: { 4096, 50 }
    6: // Out stride: { 50, 1 }
    7: // Elementwise input X_T74 shape: fp64(4096, 50):(50, 1):1600 KiB
    8: // Elementwise input X_T475 shape: fp64(4096, 1):(1, 1):32 KiB
    9: // Elementwise op: X_T476 = sub(X_T74, X_T475)
   10: // Elementwise op: X_T477 = exp(X_T476)
   11: // Tile size: { 8, 50 }
   12: // Contraction output var shape: fp64(4096, 50):(50, 1):1600 KiB
   13: // Computed true ops: 409600
   14: // Computed work groups: 512
   15: // Computed inner loops: 1
   16: // Computed shared mem: 0
   17: // Computed out regs: 4096
   18: // Computed mem read: 512
   19: // Computed mem write: 4096
   20: // Computed operations: 256
   21: // Computed rollups: 0
   22: // Computed threads used: 256
   23: // lwork = 256, 1, 1
   24: // gwork = 131072, 1, 1
   25: __kernel void kernel_c10_sdk_20(__global double* restrict  X_T477, __global const double* restrict  X_T74, __global const double* restrict  X_T475)
   26: {
   27:   int tid = get_local_id(0);
   28:   int i1_gid = (get_group_id(0) * 8);
   29:   int i2_tid = (tid % 32);
   30:   int i1_tid = ((tid / 32) % 8);
   31:   for (int i2_lid = 0; i2_lid < 2; i2_lid += 1)
   32:   {
   33:     int i2_cond = ((i2_lid < 1) || (i2_tid < 18));
   34:     if (i2_cond)
   35:     {
   36:       int i2 = ((32 * i2_lid) + i2_tid);
   37:       int gout_idx = ((50 * (i1_gid + i1_tid)) + i2);
   38:       double LX_T74 = X_T74[gout_idx];
   39:       double LX_T475 = X_T475[(i1_gid + i1_tid)];
   40:       double LX_T476 = (LX_T74 - LX_T475);
   41:       double LX_T477 = native_exp(LX_T476);
   42:       X_T477[gout_idx] = LX_T477;
   43:     }
   44:   }
   45: }

W0829 12:27:51.693425 123145400958976 library.py:135] Code was: 
    1: #pragma OPENCL EXTENSION cl_khr_fp64 : enable
    2: // gid: 131072 1 1
    3: // lid: 256 1 1
    4: // Names: { i1, i2 }
    5: // Ranges: { 4096, 50 }
    6: // Out stride: { 50, 1 }
    7: // Elementwise input X_T74 shape: fp64(4096, 50):(50, 1):1600 KiB
    8: // Elementwise input X_T475 shape: fp64(4096, 1):(1, 1):32 KiB
    9: // Elementwise op: X_T476 = sub(X_T74, X_T475)
   10: // Elementwise op: X_T477 = exp(X_T476)
   11: // Tile size: { 8, 50 }
   12: // Contraction output var shape: fp64(4096, 50):(50, 1):1600 KiB
   13: // Computed true ops: 409600
   14: // Computed work groups: 512
   15: // Computed inner loops: 1
   16: // Computed shared mem: 0
   17: // Computed out regs: 4096
   18: // Computed mem read: 512
   19: // Computed mem write: 4096
   20: // Computed operations: 256
   21: // Computed rollups: 0
   22: // Computed threads used: 256
   23: // lwork = 256, 1, 1
   24: // gwork = 131072, 1, 1
   25: __kernel void kernel_c10_sdk_20(__global double* restrict  X_T477, __global const double* restrict  X_T74, __global const double* restrict  X_T475)
   26: {
   27:   int tid = get_local_id(0);
   28:   int i1_gid = (get_group_id(0) * 8);
   29:   int i2_tid = (tid % 32);
   30:   int i1_tid = ((tid / 32) % 8);
   31:   for (int i2_lid = 0; i2_lid < 2; i2_lid += 1)
   32:   {
   33:     int i2_cond = ((i2_lid < 1) || (i2_tid < 18));
   34:     if (i2_cond)
   35:     {
   36:       int i2 = ((32 * i2_lid) + i2_tid);
   37:       int gout_idx = ((50 * (i1_gid + i1_tid)) + i2);
   38:       double LX_T74 = X_T74[gout_idx];
   39:       double LX_T475 = X_T475[(i1_gid + i1_tid)];
   40:       double LX_T476 = (LX_T74 - LX_T475);
   41:       double LX_T477 = native_exp(LX_T476);
   42:       X_T477[gout_idx] = LX_T477;
   43:     }
   44:   }
   45: }

**Comment by dgkutnic** [comment]
We don't officially support `float64` in plaidml. Any support that you may see at this time is extremely experimental. Many GPUs don't even have inbuilt double precision support, so we haven't really prioritized supporting it on our end.

If it's something you're interested in seeing, please let us know. We value the perspectives that our open source community brings us and may revisit supporting this with enough interest from members of the community.
