### ISSUE TITLE
macbook pro 2018 15' runs slower when using plaidml than CPU tensorflow

### ISSUE THREAD

**Issue by williamtong0228** [plaidml/plaidml#467]
I guess that it didn't really activate the GPU, but I don't know what was wrong. I tested on my Mac mini and Intel M3 Compute Stick and I found that the CPU tensorflow backend was faster.
And the code was copied from a book I am reading.

I created a new virtual environment with conda and then install plaidml

pip install -U plaidml-keras
plaidml-setup

(**plaidml**) bash-3.2$ cd /Users/user/Desktop/OneDrive ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /anaconda3/envs/plaidml/bin/python /Users/william/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 60761 /Users/william/Desktop/OneDrive/deepmnist.py 
x_train.shape: (60000, 28, 28)
x_train.shape: (10000, 28, 28)
y_train.shape: (60000,)
y_test.shape: (10000,)
INFO:plaidml:Opening device "metal_amd_radeon_pro_555x.0"
Train on 48000 samples, validate on 12000 samples
Epoch 1/20
48000/48000 [==============================] - 11s 231us/step - loss: 0.3299 - acc: 0.9051 - val_loss: 0.1821 - val_acc: 0.9488

(**tensorflow**) bash-3.2$ cd /Users/user/Desktop/OneDrive ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /anaconda3/envs/deeplearning/bin/python /Users/william/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 60825 /Users/william/Desktop/OneDrive/deepmnist.py 
x_train.shape: (60000, 28, 28)
x_train.shape: (10000, 28, 28)
y_train.shape: (60000,)
y_test.shape: (10000,)
WARNING: Logging before flag parsing goes to stderr.
W0901 17:06:58.058610 4557985216 deprecation.py:506] From /anaconda3/envs/deeplearning/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Train on 48000 samples, validate on 12000 samples
2019-09-01 17:06:58.277411: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2019-09-01 17:06:58.277678: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 12. Tune using inter_op_parallelism_threads for best performance.
Epoch 1/20
48000/48000 [==============================] - 3s 68us/sample - loss: 0.3311 - acc: 0.9076 - val_loss: 0.1771 - val_acc: 0.9498
Epoch 2/20
48000/48000 [==============================] - 3s 61us/sample - loss: 0.1533 - acc: 0.9563 - val_loss: 0.1323 - val_acc: 0.9620

```python
import os
import numpy as np
import plaidml.keras
plaidml.keras.install_backend()

import keras
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Input,Dense
from keras.models import Model


# from tensorflow.python.keras.datasets import mnist
# from tensorflow.python.keras.utils import to_categorical
# from tensorflow.python.keras.models import Sequential
# from tensorflow.python.keras.layers import Input,Dense
# from tensorflow.python.keras.callbacks import TensorBoard
# from tensorflow.python.keras.models import Model

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_train = x_train/255.
x_test = x_test.reshape(10000, 784)
x_test = x_test/255.

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)


model = Sequential()
model.add(
    Dense(
        units=64,
        input_shape=(784,),
        activation='relu'
    )
)
model.add(
    Dense(
        units=10,
        activation='softmax'
    )
)

#tsb = TensorBoard(log_dir='./logs')

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(
    x_train,
    y_train,
    batch_size=32,
    epochs=20,
    validation_split=0.2,
    #callbacks=[tsb]

)

model.save('mnist.h5')
```

**Comment by dgkutnic** [comment]
Hi @williamtong0228,
You'll see the most performance gain when using PlaidML with GPU on medium to large sized networks. This is because the GPU performs mathematical computations much more quickly than the CPU can.
Conversely, on smaller networks, you may see that PlaidML with GPU performs more slowly than the TensorFlow CPU backend because there is a bottleneck associated with transferring training/validation data over to the GPU.
Using the example you provided, if you change this code snippet
```
model.add(
    Dense(
        units=64,
        input_shape=(784,),
        activation='relu'
    )
)
```
to this:
```
model.add(
    Dense(
        units=2048,
        input_shape=(784,),
        activation='relu'
    )
)
```
you'll see that PlaidML + GPU is about twice as fast as TensorFlow + CPU on a Macbook Pro 2018.

**Comment by williamtong0228** [comment]
Hi dgkutnic,
Thank you for the reply. I tried to set it to units = 2048, but the result didn't change. And I found that there's another similar thread but it turned out that it was another problem. https://github.com/plaidml/plaidml/issues/312 . I am fine with it because I use my PC for intensive training.

Another observation I got was that the High Performance GPU was never activated when I check the power consumption monitor.
 
I also tested that I got almost the same result as the Intel intergrated GPU. So I suspect that the Discreted GPU was not activated.

I am using Anaconda's virtual environment. But I am positive that I was running plaidml backend because I saw the following error message when I imported keras too early. 
ModuleNotFoundError: No module named 'tensorflow'


bash-3.2$ source /anaconda3/bin/activate
/anaconda3/envs/plaidml/bin/python /Users/william/.vscode/extensions/ms-python.python-2019.9.34474/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 50625 /Users/william/Desktop/OneDrive/deepmnist.py 
(base) bash-3.2$ /anaconda3/envs/plaidml/bin/python /Users/william/.vscode/extensions/ms-python.python-2019.9.34474/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 50625 /Users/william/Desktop/OneDrive/deepmnist.py 
conda activate plaidml
x_train.shape: (60000, 28, 28)
x_train.shape: (10000, 28, 28)
y_train.shape: (60000,)
y_test.shape: (10000,)
INFO:plaidml:Opening device "metal_amd_radeon_pro_555x.0"
Train on 48000 samples, validate on 12000 samples

**Comment by dgkutnic** [comment]
Thanks for sharing. Our entire team develops our code on 15" MacBook Pro 2018 machines, so they're a pretty heavily tested piece of hardware. 

I'm curious as to why you aren't seeing your discrete GPU being utilized even when you select it from within PlaidML. Here's what I see on my Mac Pro 2018. The discrete GPU is being utilized both before and after I run the training example, and utilization hits 100% when I am running training. Since you mentioned that you don't believe the discrete GPU was utilized at all, I wonder if your laptop's settings are configured to enable the discrete GPU. Do you see it being utilized when you run other GPU-intensive applications?

<img width="698" alt="Screen Shot 2019-09-05 at 8 27 57 AM" src="https://user-images.githubusercontent.com/50588693/64356272-6ad7c080-cfb7-11e9-912c-ac01b6827b4a.png">

**Comment by williamtong0228** [comment]
Oh, I was wrong. It did utilize the GPU. Thank you.
It just happens that 555x's performance is just too close to UHD 630 for smaller networks. 

<img width="1438" alt="Screenshot 2019-09-06 at 12 24 26 AM" src="https://user-images.githubusercontent.com/38699976/64361046-525eb900-d03e-11e9-98e5-cdb8713ae33a.png">
CPU

<img width="1428" alt="Screenshot 2019-09-06 at 12 27 37 AM" src="https://user-images.githubusercontent.com/38699976/64361429-20018b80-d03f-11e9-85c3-dcc0f80207de.png">
UHD 630

<img width="1280" alt="Screenshot 2019-09-06 at 12 29 25 AM" src="https://user-images.githubusercontent.com/38699976/64361658-956d5c00-d03f-11e9-9042-b6c76a93f548.png">
555x OpenCL


<img width="1319" alt="Screenshot 2019-09-06 at 12 31 27 AM" src="https://user-images.githubusercontent.com/38699976/64361721-b46bee00-d03f-11e9-8d94-f665d6cd0871.png">
555x Metal
