### ISSUE TITLE
Issue in building plaidml through bazelisk

### ISSUE THREAD

**Issue by ShashanKV98** [plaidml/plaidml#536]
Hi y'all, 

So i'm trying to build plaidml from the source on Linux following the documentation.
After 
./configure
the build tests were successful, but later on entering the command,

bazelisk build //plaidml:wheel

I enountererd this error.

(Pip subprocess error:
/uufs/chpc.utah.edu/common/home/u1265559/.cache/bazel/_bazel_u1265559/468c5cbd5df58a1ca8f24bb5248544ff/external/com_intel_plaidml_conda_unix/env/.tmpvhgr6ei6: line 3: 20098 Killed                  /uufs/chpc.utah.edu/common/home/u1265559/.cache/bazel/_bazel_u1265559/468c5cbd5df58a1ca8f24bb5248544ff/external/com_intel_plaidml_conda_unix/env/bin/python -m pip install -U -r /uufs/chpc.utah.edu/common/home/u1265559/plaidml2/plaidml/conda/condaenv.v3s1mb74.requirements.txt

CondaEnvException: Pip failed
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u1265559/plaidml2/plaidml/bzl/conda_wrapper.py", line 225, in <module>
    main()
  File "/uufs/chpc.utah.edu/common/home/u1265559/plaidml2/plaidml/bzl/conda_wrapper.py", line 218, in main
    subprocess.check_call(['conda'] + sys.argv[1:])
  File "/uufs/chpc.utah.edu/common/home/u1265559/software/pkg/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call

I've used a virtual env for these operations. I've tried deleting the bazel directory in .cache and plaidml dir, freshly cloned the plaidml repo and downloaded bazel, but in vain. Also updated the conda to newest version.
Anyone has any suggestions about this error. Thanks a lot!

**Comment by vmiheer** [comment]
Just to add:
```
ERROR: Analysis of target '//plaidml:wheel' failed; build aborted: no such package '@com_intel_plaidml_conda_unix//': conda_repo failed: Collecting package metadata (repodata.json): ...working... done
```

**Comment by dgkutnic** [comment]
To clarify: are both of you running `conda activate ./.cenv` between running `configure` and building the wheel? If not, what are the results when you activate this conda environment?

**Comment by flaub** [comment]
It appears that somehow `conda` was not found on the PATH. You shouldn't need to activate the conda environment, but you do need to ensure that you can run `conda` from whichever shell you are running `bazelisk`.

**Comment by flaub** [comment]
You can try running `bazelisk clean --expunge` and then doing a new build. Sometimes conda has unrecoverable errors it seems.

**Comment by ShashanKV98** [comment]
I've tried all the above ones suggested, but still, the same error pops up. 
com_intel_plaidml_conda_unix:  is the package which it tried to fetch for a pretty long time, and then the build failed along with the series of errors.

**Comment by flaub** [comment]
We actually build and run on a variety of linux (and windows) machines in house, and I admit I've never seen an error message like you're getting. I wonder if you were to use conda manually to install the environment whether it would complete successfully, leading to the idea that something is different about your machine somehow. You could try: 

```
conda env create -f conda/unix.yml -n experiment
```

**Comment by ShashanKV98** [comment]
I used this one too. Just a small hunch, should I create the env inside the plaidml directory (changing the path). And is this command supposed to "update the conda environment from" the unix.yml, because it's still using the environment.yml file inside the plaidml dir, during the ./configure command execution.

**Comment by ShashanKV98** [comment]
The only reason why I am building plaidml from source is that it isn't recognizing CUDA on the devices (OpenCL only) when I have installed it through pip. Is there any way I could cut short this problem enable CUDA.

**Comment by dgkutnic** [comment]
Hi @ShashanKV98 - FWIW, we once had experimental support for CUDA but found that there weren't substantial performance gains over using OpenCL for the same device, so we chose to officially support OpenCL and have not worked on furthering our CUDA support since then. Hope this helps.

**Comment by vmiheer** [comment]
Hi @dgkutnic, what tools did you use to profile OpenCl? Our motivation behind building CUDA version is to use nvprof/nnvm to measure performance of the kernels.

**Comment by dgkutnic** [comment]
@brianretford can you comment on this one?

**Comment by vmiheer** [comment]
Also even if the performance you observed with both apis was equivalent, given that CUDA exposes bit of additional features like warp shuffles, way to limit thread-register usage at compile time etc, we would like to do exploration over these features using CUDA version.
In gist, it would be still great to have the ability to build the CUDA version. 🙂

**Comment by vmiheer** [comment]
> Hi @ShashanKV98 - FWIW, we once had experimental support for CUDA but found that there weren't substantial performance gains over using OpenCL for the same device, so we chose to officially support OpenCL and have not worked on furthering our CUDA support since then. Hope this helps.

Apologies, I missed the last line of reply, so @dgkutnic, you are not planning on CUDA support in near future?

**Comment by flaub** [comment]
There is experimental support for CUDA already. We don't build this by default, but you can enable it. You'll need the CUDA SDK and then you'll have to configure your build to find it. To enable it use

```
CUDA_TOOLKIT_PATH=/path/to/cuda/sdk VAI_NEED_CUDA=1 bazelisk run //plaidml:setup
```

It's possible that this code is broken since we haven't updated it in a long time. We'd welcome any patches however :)
