### ISSUE TITLE
PlaidML can't see GPU on OpenCL 1.2 (HD6950).

### ISSUE THREAD

**Issue by JMcsLk** [plaidml/plaidml#560]
Hello Everyone, I just prepared all drivers compatibile to Radeon HD6950 card and tried to set my GPU as a accelerator. Clinfo sees normally my card but PlaidML does not. Could you explain me this discrepancy?

**### Clinfo:**

Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (1800.11)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon HD 6900 Series 
  Device Topology:				 PCI[ B#2, D#0, F#0 ]
  Max compute units:				 22
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 4
  Preferred vector width double:		 2
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 4
  Native vector width double:			 2
  Max clock frequency:				 870Mhz
  Address bits:					 32
  Max memory allocation:			 534773760
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 None
  Cache line size:				 0
  Cache size:					 0
  Global memory size:				 909115392
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 0
  Max pipe active reservations:			 0
  Max pipe packet size:				 0
  Max global variable size:			 0
  Max global variable preferred total size:	 0
  Max read/write image args:			 0
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f9947d31430
  Name:						 Cayman
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1800.11 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (1800.11)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_amd_image2d_from_buffer_read_only cl_khr_spir cl_khr_gl_event 

  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 4
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 4
  Preferred vector width double:		 2
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 4
  Native vector width double:			 2
  Max clock frequency:				 800Mhz
  Address bits:					 64
  Max memory allocation:			 2621737984
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 65536
  Global memory size:				 10486951936
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2621737984
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f9947d31430
  Name:						 AMD Phenom(tm) II X4 B25 Processor
  Vendor:					 AuthenticAMD
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1800.11 (sse2)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (1800.11)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 

**### PlaidML-setup:**

PlaidML Setup (0.6.4)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0
 

Default Config Devices:
   No devices.

Experimental Config Devices:
   llvm_cpu.0 : CPU (LLVM)

Using experimental devices can cause poor performance, crashes, and other nastiness.

**Comment by dgkutnic** [comment]
Hi @JMcsLk,
 
Could you enable verbose logging and provide us with the full output of plaidml-setup?

```
export PLAIDML_VERBOSE=4
plaidml-setup
```

Thanks!

**Comment by JMcsLk** [comment]
Surely I do, thanks for very quick response!

**### Plaidml-setup log:**

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0
 
INFO:Verbose logging has been enabled - verbose level 4 

DEBUG:plaidml:Creating HAL: opencl
DEBUG:plaidml:Failed to initialize HAL: clGetPlatformIDs libOpenCL.so: cannot open shared object file: No such file or directory
DEBUG:plaidml:Creating HAL: llvm
DEBUG:plaidml:Creating HAL: opencl
DEBUG:plaidml:Failed to initialize HAL: clGetPlatformIDs libOpenCL.so: cannot open shared object file: No such file or directory
DEBUG:plaidml:Creating HAL: llvm
DEBUG:plaidml:threads: 1
vec_size: 32
use_global: true
mem_width: 4096
max_mem: 8192
max_regs: 8192
goal_groups: 1
goal_flops_per_byte: 20
dim_sizes: 0
stripe_config: "cpu"

DEBUG:plaidml:Using shared memory for data transfer
DEBUG:plaidml:Using fifo scheduler; size_goal=1.36e+10

Default Config Devices:
   No devices.

Experimental Config File Location:
   /home/mpietrzycki/virtualenvs/d2-amd/share/plaidml/

Experimental Config Devices:
   llvm_cpu.0 : CPU (LLVM)

Using experimental devices can cause poor performance, crashes, and other nastiness.

**Comment by dgkutnic** [comment]
Thanks for this info!

Notice the following line? This is an indicator that PlaidML can't find your OpenCL install:
> DEBUG:plaidml:Failed to initialize HAL: clGetPlatformIDs libOpenCL.so: cannot open shared object file: No such file or directory

Typically, the OpenCL installation should be located in something like `/usr/lib/x86_64-linux-gnu/libOpenCL.so`. I've had a couple of people in the past who have had OpenCL install to the same directory, but with a different suffix (i.e. `/usr/lib/x86_64-linux-gnu/libOpenCL.so.<some different suffix here>`). Could you check if that is the case?

In any case, your solution would be to do the following:
1. Locate where your `libopencl.so` file is located (clinfo works, so you have this file _somewhere_)
2. Create a symbolic link from the real path to `libopencl.so` to `/usr/lib/x86_64-linux-gnu/libOpenCL.so`
3. Rerun `plaidml-setup` with the verbosity on, verifying that a) the "Failed to initialize HAL" error message goes away and b) the setup completes successfully

**Comment by JMcsLk** [comment]
I could not locate this file so I tried to reinstall it by:

`sudo apt install ocl-icd-opencl-dev`

Now i get on plaidml-setup this:
Traceback (most recent call last):
  File "/home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/__init__.py", line 154, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/libplaidml.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mpietrzycki/virtualenvs/d2-amd/bin/plaidml-setup", line 10, in <module>
    sys.exit(main())
  File "/home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/plaidml_setup.py", line 16, in main
    ctx = plaidml.Context()
  File "/home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/__init__.py", line 889, in Context
    return plaidml.context.Context(_lib())
  File "/home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/__init__.py", line 789, in _lib
    _impl_lib = _Library()
  File "/home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/__init__.py", line 181, in __init__
    lib = load_library('libplaidml.so', ['lib'], prefixes)
  File "/home/mpietrzycki/virtualenvs/d2-amd/lib/python3.6/site-packages/plaidml/__init__.py", line 166, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mpietrzycki/virtualenvs/d2-amd/lib/libplaidml.so: symbol _ZTINSt8ios_base7failureB5cxx11E, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by JMcsLk** [comment]
Ok i think I just fixed it by:
`wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb`

`sudo dpkg --force-all -i libstdc++6`

`wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_extended_0.46_Linux_64bit.de`

`sudo dpkg -i hugo.deb`

And now I can find it:

**Experimental Config Devices:
   llvm_cpu.0 : CPU (LLVM)
   opencl_amd_cayman.0 : Advanced Micro Devices, Inc. Cayman (OpenCL)**

Thanks!

**Comment by dgkutnic** [comment]
Nice! Glad you figured it out. I'll keep this in mind for anyone who experiences similar issues in the future.

Thanks for using PlaidML!
