### ISSUE TITLE
Jupyter Notebook PlaidML-Setup Issue.

### ISSUE THREAD

**Issue by JMcsLk** [plaidml/plaidml#562]
It's me again...
I solved my previous problem with AMD HD6950 OpenCL drivers. Now I tried to use plaidml as a keras backend on Jupyter Notebook. When i try to import backend i get:

`os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
os.environ["PLAIDML_DEVICE_IDS"] = " opencl_amd_cayman.0

import plaidml.keras
plaidml.keras.install_backend()
`
opencl_amd_cayman line was optional I tried without it and result was the same...

**PlaidMLError: No devices found. Please run plaidml-setup. The following devices are available:
  b'llvm_cpu.0'
  b'opencl_cpu.0'**

When I start tests in terminal as a:
`plaidbench keras mobilenet`

Everything works fine!

**Comment by dgkutnic** [comment]
Do you have `PLAIDML_EXPERIMENTAL` set anywhere in your jupyter notebook? You would likely need that along with `PLAIDML_DEVICE_IDS` to both be set.

**Comment by JMcsLk** [comment]
I may not, could you precise how to do it?

**Comment by dgkutnic** [comment]
Set these variables:
```
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
os.environ["PLAIDML_EXPERIMENTAL"] = True
os.environ["PLAIDML_DEVICE_IDS"] = "opencl_amd_cayman.0"
```
Then, when you run this:
```
import keras
```
You'll see the following:
```
Using plaidml.keras.backend backend.
```

**Comment by flaub** [comment]
Actually I think the experimental value wants a `1`

**Comment by flaub** [comment]
And actually env vars can only be strings, so you need to say 

```
os.environ["PLAIDML_EXPERIMENTAL"] = "1"
```

**Comment by JMcsLk** [comment]
It takes this well:
```
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
os.environ["PLAIDML_EXPERIMENTAL"] = "1"
os.environ["PLAIDML_DEVICE_IDS"] = "opencl_amd_cayman.0"

```
But output is the same as in the 1 post.

**Comment by JMcsLk** [comment]
Just want to add that I can run different .py scripts using PlaidML by terminal easily.
Still do not understand this jupyter failure...

**Comment by dgkutnic** [comment]
Hi @JMcsLk,

We haven't been able to reproduce this on our end -- Jupyter notebooks are working fine for us, including the ones in our `demos` directory.

If you're still having issues running PlaidML through Jupyter, could you provide us with the Jupyter notebook that is causing you issues? If not, could you let us know so that we can close the issue?

Thanks!

**Comment by JMcsLk** [comment]
I switched my OS to Windows which works fine in this case. You can close this topic.

**Comment by dgkutnic** [comment]
Thanks for the update! Glad you got it working.
