### ISSUE TITLE
plaidml version  incompatibility with keras?

### ISSUE THREAD

**Issue by asheetal** [plaidml/plaidml#612]
I have installed  minimal packages using pip3  
cffi (1.12.3)
enum34 (1.1.6)
h5py (2.10.0)
Keras (2.2.5)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
numpy (1.17.2)
pip (9.0.3)
plaidml (0.6.4)
plaidml-keras (0.6.4)
pycparser (2.19)
PyYAML (5.1.2)
scipy (1.3.1)
setuptools (39.2.0)
six (1.12.0)

When I run the  training with the code
```
callback_model_checkpoint(
  filepath = model_file,   
  save_best_only = TRUE, 
  period = 1,
  verbose = 0)
```

I get an error with tensorflow version check. Anyone  has any idea  how to fix this error below?

> Error in if (tensorflow::tf_version() < "1.14") { : 
>   argument is of length zero

There is no error if I do not use save model

**Comment by dgkutnic** [comment]
Have you tried installing `tensorflow==1.14.0`? Some parts of Keras are hard-coded to check for the tensorflow version, even if you are using plaidml as the backend.

**Comment by dgkutnic** [comment]
We haven't been able to reproduce this issue on our end because we couldn't find the function `callback_model_checkpoint` within Keras. Could you provide us with more information on what this function is trying to do?

**Comment by asheetal** [comment]
This piece of code

`callback_model_checkpoint(
  filepath = model_file,   
  save_best_only = TRUE, 
  period = 1,
  verbose = 0)
`
This callback code above is just saving the best model, nothing more. Is very basic operation. Nothing complicated. My comment is that there is a inconsistency between versions of libraries/drivers. And to add to that python2.7 is marked EOL in Centos 7. Can someone share the output of the following command?

`pip3 list`

**Comment by asheetal** [comment]
I realized that the problem was with callback_model_checkpoint, the callback I use in keras to save the model periodically. Seems there is some incompatility with that. Finally I am using plaidml==0.6.3, tensorflow-rocm==1.13.2, commented out model_checkpoint, and the code runs fine. Closing it.
