### ISSUE TITLE
plaidml roadmap?

### ISSUE THREAD

**Issue by iperov** [plaidml/plaidml#618]
what are you doing now?
do you port existing tech or invent something new from scratch?
what is EDSL in plaidml? any info about it?

**Comment by dgkutnic** [comment]
> what are you doing now?

We are working on releasing a roadmap to the public soon. @brianretford would have more details.
> do you port existing tech or invent something new from scratch?

If this is about the EDSL op lib, some of the ops follow the existing Tile implementations closely but others are vastly improved. Some operations that were not supported in Tile are now supported in the EDSL. Several members of our team have been working hard on this.
> what is EDSL in plaidml? any info about it?

You can read about the EDSL at [docs/edsl.md](https://github.com/plaidml/plaidml/blob/master/docs/edsl.md).

**Comment by iperov** [comment]
I checked plaidml2.op.convolution, it has hidden C++ implementation.
But can convolution be implemented via pure python and has same speed?
I am asking this, because there are some new conv's researches released last time
for example
Kervolutional Neural Networks https://arxiv.org/pdf/1904.03955.pdf
PacConv2d https://github.com/NVlabs/pacnet
and other

**Comment by AGenchev** [comment]
@iperov python typically is way slower than C++ In fact  most performant python packages are ported from C/C++
there's a new language targeting the science community which is more performant. It's called Julia.

**Comment by iperov** [comment]
> python typically is way slower than C++

'implemented via python' of course I mean using new edsl python api, where most of ML is implemented.

ROFL 
Did you think of doing real convolution on CPU in python?

bury your julia back please

**Comment by bhack** [comment]
Check this for some updates:
https://drive.google.com/file/d/1FLdhNgTii9x5o1rMgN4ibB7Wkuq6Pyye/view?usp=drivesdk

**Comment by Gerzer** [comment]
> Check this for some updates:
> https://drive.google.com/file/d/1FLdhNgTii9x5o1rMgN4ibB7Wkuq6Pyye/view?usp=drivesdk

I hate to bring this up again, but I saw that one of the slides listed Stripe support for GPUs as expected in 2020. Is better "scatter/gather" GPU performance—and therefore better RNN/LSTM/GRU performance—only coming after initial Stripe GPU support is completed?

I apologize if I'm completely misunderstanding the situation, which is very possible. I just want to know if you have an estimated timeframe for when RNN performance will be improved. Thanks!

**Comment by iperov** [comment]
any news?

**Comment by iperov** [comment]
any news?

**Comment by dataopt** [comment]
> @iperov python typically is way slower than C++ In fact most performant python packages are ported from C/C++
> Also there's a new language targeting the science community which is more performant. It's called Julia. It works well in Jupyter notebook as well.
> Now imagine we want to move from Python to Julia and we're using Plaidml. It'd be much easier to link to C/C++ code than to reinvent it by translating backend code from Python to Julia

What needs to happen to make using Plaidml in Julia a reality?

**Comment by iperov** [comment]
any news?

**Comment by brianretford** [comment]
We have made make progress on the gpu front. Intel GEN was our first target and we hope to have AMD and  Nvidia configs soon after. A huge gap we have yet to address is training.

Internal resources have shifted a bit and we do have some more resources available, but I couldn't say when that will became a priority.

Prior to training we are adding various Edsl constructs to enable writing LSTM like contructs.

We are also working on tensorflow and pytorch support but no have on that front.

Not the news I want to have but we were heads down doing future looking intel stuff atm

**Comment by KSTRTK** [comment]
Hi All,

Was wondering if plaidml runs well on Julia. Any information you guys can provide will be greatly appreciated!

Thanks

**Comment by chelini** [comment]
> 

I don't think PlaidML has a Julia frontend, and as far as I know, there are no efforts in this direction.
