### ISSUE TITLE
No matching distribution error from pip

### ISSUE THREAD

**Issue by drewstone** [plaidml/plaidml#65]
Hello, I'm not able to install this using pip and am having even less luck compiling bazel to do it from source.

I've tried python version 2.7 and 3.6.

How can I install this?

**Comment by brianretford** [comment]
Hey Drew,

What platform are you on? Can you provide exact details on that as well as a dump of the command you're running and the output.

Thanks!

**Comment by brianretford** [comment]
Friendly ping. Are you trying to deploy to arm?

**Comment by drewstone** [comment]
Apologies, I've been busy with school. I believe I was on Ubuntu 16.04 when I was trying to configure this (I quickly iterated on multiple Ubuntu versions perhaps 14.04.5 if this can't be replicated)

I was trying to deploy plaidML on my AMD GPUs: XFX7970 or Sapphire cards. I was getting errors that the packages didn't exist in pip. After also failing to compile bazel from source, I gave up compiling anything from source.

**Comment by brianretford** [comment]
Can you copy and paste exactly what you're doing and what the error is and the output of 'uname -a'? The pips are definitely there:
https://pypi.python.org/pypi/plaidml-keras
https://pypi.python.org/pypi/plaidml

**Comment by brianretford** [comment]
Note that we only ship pips for x64. If for some reason you were using a 32-bit version of Linux, I would expect to see something like what you saw.

**Comment by brianretford** [comment]
Could you let us know if PlaidML currently works for you? Or if you were running a 32-bit linux?

**Comment by tzerrell** [comment]
Closing this as stale; feel free to reopen if the issue persists

**Comment by bulgarian-beast** [comment]
Hello,

First of all thank you for any help.
I am on : 

macOS Big Sur 11.0.1
Python 3.7.9 - 64Bit
pip 20.0.2

I can't `pip install plaidml-keras==0.7.0` (or any other version)

Got : 
   
Collecting plaidml-keras==0.7.0
  Using cached plaidml_keras-0.7.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from plaidml-keras==0.7.0) (1.14.0)
ERROR: Could not find a version that satisfies the requirement plaidml (from plaidml-keras==0.7.0) (from versions: none)
