### ISSUE TITLE
Run Fails with CL_MEM_OBJECT_ALLOCATION_FAILURE error

### ISSUE THREAD

**Issue by rahasayantan** [plaidml/plaidml#67]
I tried using Keras VGG implementation. (keras.applications.vgg16). I am getting the following error. This might not be related to Plaidml, can you help me with what I need to change with the GPU config and where to get rid of this issue?

Error: 
=================================
---------------------------------------------------------------------------
Unknown                                   Traceback (most recent call last)
<ipython-input-17-f8075de3d0be> in <module>()
----> 1 preds=myAngleCV(X_train, X_angle, X_test)

<ipython-input-16-1804a5b82d69> in myAngleCV(X_train, X_angle, X_test)
     21         callbacks = get_callbacks(filepath=file_path, patience=5)
     22         gen_flow = gen_flow_for_two_inputs(X_train_cv, X_angle_cv, y_train_cv)
---> 23         galaxyModel= getVggAngleModel()
     24         galaxyModel.fit_generator(
     25                 gen_flow,

<ipython-input-9-0d65cb77269d> in getVggAngleModel()
     34     angle_layer = Dense(1, )(input_2)
     35     base_model = VGG16(weights='imagenet', include_top=False, 
---> 36                  input_shape=X_train.shape[1:], classes=1)
     37     x = base_model.get_layer('block5_pool').output
     38 

/home/sayantan/anaconda2/lib/python2.7/site-packages/keras/applications/vgg16.pyc in VGG16(include_top, weights, input_tensor, input_shape, pooling, classes)
    134     x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv1')(x)
    135     x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv2')(x)
--> 136     x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv3')(x)
    137     x = MaxPooling2D((2, 2), strides=(2, 2), name='block5_pool')(x)
    138 

/home/sayantan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in __call__(self, inputs, **kwargs)
    573                                          '`layer.build(batch_input_shape)`')
    574                 if len(input_shapes) == 1:
--> 575                     self.build(input_shapes[0])
    576                 else:
    577                     self.build(input_shapes)

/home/sayantan/anaconda2/lib/python2.7/site-packages/keras/layers/convolutional.pyc in build(self, input_shape)
    132                                       name='kernel',
    133                                       regularizer=self.kernel_regularizer,
--> 134                                       constraint=self.kernel_constraint)
    135         if self.use_bias:
    136             self.bias = self.add_weight(shape=(self.filters,),

/home/sayantan/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/home/sayantan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint)
    397                             dtype=dtype,
    398                             name=name,
--> 399                             constraint=constraint)
    400         if regularizer is not None:
    401             self.add_loss(regularizer(weight))

/home/sayantan/anaconda2/lib/python2.7/site-packages/plaidml/keras/backend.pyc in variable(value, dtype, name, constraint)
   2536     else:
   2537         if isinstance(value, _Op):
-> 2538             value = value.eval()
   2539         tensor = plaidml.Tensor(_device(), plaidml.Shape(_ctx, _dtypes[dtype], *value.shape))
   2540         with tensor.mmap_discard(_ctx) as view:

/home/sayantan/anaconda2/lib/python2.7/site-packages/plaidml/keras/backend.pyc in eval(self)
    900 
    901         # Copy the data
--> 902         with tensor.mmap_current() as view:
    903             view.copy_to_ndarray(out)
    904 

/home/sayantan/anaconda2/lib/python2.7/contextlib.pyc in __enter__(self)
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")

/home/sayantan/anaconda2/lib/python2.7/site-packages/plaidml/__init__.pyc in mmap_current(self)
   1127     def mmap_current(self):
   1128         mapping = _lib().plaidml_map_buffer_current(self.buffer,
-> 1129                                                     ctypes.cast(None, _MAP_BUFFER_FUNCTYPE), None)
   1130         yield _View(self.buffer._ctx, mapping, self.shape.dtype, self.shape.ctype,
   1131                     _lib().plaidml_get_shape_element_count(self.shape), self.shape, None)

/home/sayantan/anaconda2/lib/python2.7/site-packages/plaidml/__init__.pyc in _check_err(self, result, func, args)
    672         if func == self.plaidml_writeback_mapping and args[2]:
    673             return None
--> 674         self.raise_last_status()
    675 
    676 

/home/sayantan/anaconda2/lib/python2.7/site-packages/plaidml/library.pyc in raise_last_status(self)
    134 
    135     def raise_last_status(self):
--> 136         raise self.last_status()
    137 
    138     def _logger_callback(self, unused_arg, level, msg):

Unknown: unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE

**Comment by rahasayantan** [comment]
Its a resource issue. Required compute power is more than what I have..

**Comment by mirh** [comment]
> CL_MEM_OBJECT_ALLOCATION_FAILURE

Amd driver (well, at least fglrx) doesn't allocate a big slice of available VRAM. 
You can try to override default behavior by exporting any combination of the following environment variables with a value like 95 or 100

GPU_MAX_HEAP_SIZE
GPU_MAX_ALLOC_PERCENT
GPU_SINGLE_ALLOC_PERCENT
