### ISSUE TITLE
Has the current avaliable version of plaidml utilized “stripe”?

### ISSUE THREAD

**Issue by preFiredman** [plaidml/plaidml#702]
I am now studying how plaidml optimize kernels. I saw some meterials shown your v1 will use stripe model, is it currently available?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by dgkutnic** [comment]
Hi @preFiredman,

Stripe is currently available -- if you want to enable it, you can set the environment variable `PLAIDML_USE_STRIPE` to 1.

In our current `master`, Stripe is already enabled by default for Intel GPU devices (this is not true for our 0.6.4 release though). Turning on Stripe by default for all devices is currently our top priority.
