### ISSUE TITLE
When will you correspond to Conv2DTranspose?

### ISSUE THREAD

**Issue by shi3z** [plaidml/plaidml#74]
Hi, This is very impressive project.

I tried plaidml on AMD Radeon RX570.
When I was trying keras/examples/mnist_cond_gan.py with PlaidML, error occurred.

> NotImplementedError: The Keras backend function 'conv2d_transpose' is not yet implemented in Plaid. You can help us prioritize by letting us know if this function is important to you, and as always, contributions are welcome!

conv2d_transpose is quite important for implement Generative Adversarial Networks.

If you have a plan, I want to know that.
I think that when support conv2d_transpose in plaidML, almost users can change from CUDA to OpenCL based system completely.

**Comment by tzerrell** [comment]
Thanks for letting us know that you'd like support for transposed convolutions! I'll look into implementing this.

**Comment by shi3z** [comment]
Thank you.
 I am a computer vender for deep learning. 
Now we are delivering only NVIDIA-GPU model, but you know CUDA driver has EULA problem.
If PlaidML supports conv2d_transposed, when we delivery AMD Radeon version to our customer.
If you offer paid technical support, we are ready to pay.

Best regards

**Comment by choongng** [comment]
Hi @shi3z, we may also be able to solve the NVIDIA driver issue. If you send us a mail at solutions@vertex.ai we can discuss more. Thanks!

**Comment by tzerrell** [comment]
We have added the function `conv2d_transpose` to the Keras backend in our most recent update (in commit d4afce2). This also adds support for 3D transposed convolutions with `conv3d_transpose` and, unique to PlaidML, support for arbitrary-dimension transposed convolutions with `conv_transpose`.

Thanks for letting us know that this function is important to you! Please let us know if you have any further difficulties in running your target network.
