### ISSUE TITLE
Pull 734 make it extreamly difficult for windows users to build

### ISSUE THREAD

**Issue by lllyasviel** [plaidml/plaidml#754]
https://github.com/plaidml/plaidml/pull/734

The pull 734 uses a llinux c++17 feature "std::optional", nevertheless it is not supported in vs2015/2017/2019 c++17 and even the vs2019's c++latest do not support it. The only way to build it is to make great efforts to build extra std libs for vs in windows.

Rolling back pull 734 will directly solve this issue.

**Comment by flaub** [comment]
It works on VS2019 (we are currently building this in our CI environment):

https://buildkite.com/plaidml/plaidml-plaidml/builds/1708#9b39799d-e15d-4b93-b1a9-5c946632a035
