### ISSUE TITLE
Feature Request: ELU activation function Implementation

### ISSUE THREAD

**Issue by KuzMenachem** [plaidml/plaidml#81]
I will implement the ELU function from the Keras backend as introduced here: http://image-net.org/challenges/posters/JKU_EN_RGB_Schwarz_poster.pdf

**Comment by tzerrell** [comment]
Thanks for your submission! I've reviewed it with some minor corrections, but once those are in we'll be happy to accept it!

**Comment by tzerrell** [comment]
Implemented in #82
