### ISSUE TITLE
Question: why has plaidbench been archived ?

### ISSUE THREAD

**Issue by boxerab** [plaidml/plaidml#818]

**Comment by dgkutnic** [comment]
Hi @boxerab,

The functionalities of `plaidbench` were merged into the `plaidml` repository approximately 5 months ago and have been maintained/upgraded exclusively within the `plaidml` repository. Due to this, we archived the `plaidbench` repository.

**Comment by boxerab** [comment]
Thanks. In that case, you may want to update this [blog post](https://www.intel.ai/reintroducing-plaidml/#gs.qtzky0) or remove it, as it suggests installing plaidbench to measure plaid performance.
