### ISSUE TITLE
separable_conv1d implementation not available

### ISSUE THREAD

**Issue by MarwahAhmadHelaly** [plaidml/plaidml#841]
Hello there, 

I am unfortunately unable to find the implementation for **separable_conv1d** in plaidml. The main separable_conv function and separable_conv2d are available, but not separable_conv1d. When trying to use the 1D version with keras, this of course gives an error that the function is not found in the backend (i.e. plaidml).

**Code from `plaidml/plaidml/keras/backend.py`:**
```
def separable_conv(x,
                   depthwise_kernel,
                   pointwise_kernel,
                   strides=None,
                   padding='valid',
                   data_format=None,
                   dilation_rate=None):
      ... implementation

def separable_conv2d(x,
                     depthwise_kernel,
                     pointwise_kernel,
                     strides=(1, 1),
                     padding='valid',
                     data_format=None,
                     dilation_rate=(1, 1)):
    return separable_conv(x, depthwise_kernel, pointwise_kernel, strides, padding, data_format,
                          dilation_rate)
```

I also went back to the initial release of plaidml to try to figure out if it was possibly mistakenly erased, but I found the same above two functions and still no sign of separable_conv1d. Can I kindly find some help?

**Comment by Antetokounpo** [comment]
I think calling `separable_conv` with arguments `strides=(1,)` and `dilatation_rate=(1,)` will do the trick.

**Comment by MarwahAhmadHelaly** [comment]
Thank you, it's working!
