### ISSUE TITLE
NotImplementedError: The Keras backend function 'flatten' is not yet implemented in Plaid. You can help us prioritize by letting us know if this function is important to you, and as always, contributions are welcome!

### ISSUE THREAD

**Issue by rahasayantan** [plaidml/plaidml#85]
I have implemented a simple UNET Segmentation network. I am using Dice Loss as the metric for the same. Implementation is provided below. 
I am getting the error that Plaid-ml has not implemented Flatten.

System OS: Ubuntu 14.04
GPU - AMD Hainan (Experimental)
PLaid-ML - 0.1.2
plaid_ml-keras - 0.1.2

def dice_loss(y_true, y_pred):
    smooth = 1.
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = y_true_f * y_pred_f
    score = (2. * K.sum(intersection) + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)
    return 1. - score

Kindly suggest if there is any alternative available for this issue.

**Comment by tzerrell** [comment]
Hi @rahasayantan, I notice you are using PlaidML version 0.1.2. Please try updating to the most recent version 0.2.0; the flatten function has been implemented in that version. Let us know if you have any further issues after updating!
