### ISSUE TITLE
Keras Embedding Layer is not working

### ISSUE THREAD

**Issue by yylonly** [plaidml/plaidml#92]
I try cGANs of https://github.com/eriklindernoren/Keras-GAN

Without PlaidML is working well, but after add

> import plaidml.keras
> plaidml.keras.install_backend()

I got the errors:

> PlaidMLKerasException: b'Applying function, tensor with mismatching dimensionality: I, expected=3, got=2'
> Traceback:
> _Op(batch_flatten)
> outputs: O
> inputs:
>   I: _Op(gather)
>   outputs: OUT
>   inputs:
>     V: sequential_1/dropout_1/sequential_2/dropout_3/embedding_3/embeddings[10, 784]
>     sequential_1/dropout_1/sequential_2/dropout_3/embedding_3/embeddings[10, 784]
>     I: sequential_1/dropout_1/sequential_2/dropout_3/input_6[None, 1]
>     sequential_1/dropout_1/sequential_2/dropout_3/input_6[None, 1]
>

**Comment by brianretford** [comment]
We have a release candidate out that should fix this: `pip install plaidml-keras==0.3.0rc1 plaidml==0.3.0rc`

Could you test it and confirm? It's working for me

**Comment by yylonly** [comment]
it works, thanks.

**Comment by jbruestle** [comment]
Closing as fixed.  Thanks again for the report.
