### ISSUE TITLE
Bidirectional RNNs not working

### ISSUE THREAD

**Issue by XpRienzo** [plaidml/plaidml#94]
Since it was not mentioned in the readme anymore, I assumed that plaidml had support for bidirectional RNNs. It'd be better if you guys did mention this on the readme. Is there any way to track the progress of bidirectional support?
The error I was greeted with:
NotImplementedError: rnn is not implemented for go_backwards=True

**Comment by jbruestle** [comment]
Thanks for the heads up.  We actually just added support for bidirectional support on our internal branch.  It should be in the next push to the public, which should be soon.  I'll leave this ticket open in the meantime.

**Comment by brianretford** [comment]
release 0.3.0rc2 is up if you want to verify that it fixes your issue - `pip install -U plaidml-keras==0.3.0rc2`

**Comment by XpRienzo** [comment]
It is letting me use Bidirectional now, but then there's the issue I mentioned in #95 comment.
