### ISSUE TITLE
Training networks with large embedding layers is very slow

### ISSUE THREAD

**Issue by brianretford** [plaidml/plaidml#96]
Currently PlaidML doesn't support derivatives involving sparse tensors very well, leading to serious performance issues while training large embedding layers

**Comment by vermorel** [comment]
I believe that the modern way of dealing with those sparse tensors is use table lookup embeddings. I am pointing out the case in #96. In practice, those table lookup embeddings remove entirely the need to cope with sparse tensors, which is indeed highly desirable for large embedding layers.

**Comment by Sioxas** [comment]
Is there any update?
