### ISSUE TITLE
the lib is dead?

### ISSUE THREAD

**Issue by iperov** [plaidml/plaidml#967]
no new updates
many amd gpus are still not supported.

**Comment by hfp** [comment]
I do not think so. Maybe it is confusing that development moved to `plaidml-v1` branch while master receives no updates. Typically, the default branch (here: master) is considered for daily development, but stable versions are kept in branches. PlaidML seems to do this the other way around. Anyhow, this is likely a matter of taste.

**Comment by brianretford** [comment]
We are hoping to switch over in the next couple months. The reason for the hard bifurcation is the switch to MLIR. Many GPUs will probably work if the regexs in the configurations are adjusted, in the short term.

**Comment by blblbl3** [comment]
> no new updates
> many amd gpus are still not supported.

Hello, I'm your fan. Today, your add QQ donation, that person is not trustworthy.

You can ask him to give you his donation account and password, and you can check the transaction records, so that you can trust him.

If I can help you, I will tell you the donation account and password.

I can help you anytime

**Comment by iperov** [comment]
@blblbl3 you wrote in wrong repo :D

**Comment by iperov** [comment]
any news?

**Comment by iperov** [comment]
@brianretford please don't throw the lib

**Comment by brianretford** [comment]
It's not dead but its future is a bit unclear. The future should get a lot better whether its plaidml or IREE or other things.

**Comment by iperov** [comment]
is google iree cool? looks raw

**Comment by ayeganov** [comment]
@brianretford has the future gotten any clearer? I am thinking of using it for one of my projects, but right now it seems too risky a proposition.

**Comment by brianretford** [comment]
A bit yes, I've left Intel and I'm working on something else. The new branch is actively being developed but those devs are currently focused on CPU perf.

We might start working on it again as independent people in which case I would certainly be more focused on GPU acceleration for macs / AMD / etc. Wouldn't hold my breath though.

**Comment by iperov** [comment]
I'm afraid your train has already left. I originally used plaidml for amd cards, but now tensorflow and pytorch have a directml backend, so it works on any video card.
Linux also has rocm solution.
