### ISSUE TITLE
Errors building plaid-ml-v1 from f9718a0542ce9d26e99ce2ea473fd6b41cf44b8d

### ISSUE THREAD

**Issue by powderluv** [plaidml/plaidml#972]
(plaidenv) foo@foo-ThinkPad-P53:~/github/plaidml$ bazelisk build //plaidml:wheel
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=188
INFO: Reading rc options for 'build' from /home/foo/github/plaidml/bzl/bazel.rc:
  'build' options: -c opt --spawn_strategy=standalone --genrule_strategy=standalone --announce_rc --nolegacy_external_runfiles --distinct_host_configuration=false --enable_platform_specific_config --action_env=LC_ALL --action_env=LANG --action_env=NO_PROXY --action_env=HTTP_PROXY --action_env=HTTPS_PROXY --action_env=no_proxy --action_env=http_proxy --action_env=https_proxy --define=version=0.0.0.dev0
INFO: Found applicable config definition build:linux in file /home/foo/github/plaidml/bzl/bazel.rc: --cpu=linux_x86_64 --crosstool_top=//toolchain:toolchain --define=compiler=gcc --host_crosstool_top=//toolchain:toolchain --build_tag_filters=-latex,-macos,-pytorch,-skip_linux,-windows
src/main/tools/process-wrapper-legacy.cc:58: "execvp(None, ...)": No such file or directory
INFO: Call stack for the definition of repository 'com_intel_plaidml_conda_unix' which is a conda_repo (rule definition at /home/foo/github/plaidml/vendor/conda/repo.bzl:32:14):
 - /home/foo/github/plaidml/bzl/workspace.bzl:35:5
 - /home/foo/github/plaidml/WORKSPACE:22:1
ERROR: An error occurred during the fetch of repository 'com_intel_plaidml_conda_unix':
   conda_repo failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(None, ...)": No such file or directory
)
INFO: Call stack for the definition of repository 'zlib' which is a http_archive (rule definition at /home/foo/github/plaidml/vendor/bazel/repo.bzl:51:16):
 - /home/foo/github/plaidml/bzl/workspace.bzl:161:5
 - /home/foo/github/plaidml/WORKSPACE:22:1
INFO: Call stack for the definition of repository 'jsonnet' which is a http_archive (rule definition at /home/foo/github/plaidml/vendor/bazel/repo.bzl:51:16):
 - /home/foo/github/plaidml/bzl/workspace.bzl:84:5
 - /home/foo/github/plaidml/WORKSPACE:22:1
INFO: Call stack for the definition of repository 'crosstool_ng_linux_x86_64_gcc_8.3.0' which is a http_archive (rule definition at /home/foo/github/plaidml/vendor/bazel/repo.bzl:51:16):
 - /home/foo/github/plaidml/bzl/workspace.bzl:47:5
 - /home/foo/github/plaidml/WORKSPACE:22:1
ERROR: /home/foo/github/plaidml/BUILD:45:1: //:py3_runtime depends on @com_intel_plaidml_conda_unix//:python in repository @com_intel_plaidml_conda_unix which failed to fetch. no such package '@com_intel_plaidml_conda_unix//': conda_repo failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(None, ...)": No such file or directory
)
ERROR: Analysis of target '//plaidml:wheel' failed; build aborted: no such package '@com_intel_plaidml_conda_unix//': conda_repo failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(None, ...)": No such file or directory
)
INFO: Elapsed time: 80.085s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (43 packages loaded, 298 targets configured)

**Comment by flaub** [comment]
I think this means you don't have conda installed. Or, it's having trouble finding out where it was installed.

**Comment by powderluv** [comment]
Yes. I had conda but the env had to be updated with environment.yml. 

thx.
